// ui-nexus-design-system/playbook/react/src/components/toggle/toggle.tsx
import React from 'react';

import { NexusToggle } from '@nexus/react';

interface ToggleComponentProps {
  disabled: boolean;
  labelActive: string;
  labelInactive: string;
  required: boolean;
  size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  toggled: boolean;
}

const ToggleComponent: React.FC<ToggleComponentProps> = (props) => {
  return <NexusToggle {...props}></NexusToggle>;
};

ToggleComponent.defaultProps = {
  disabled: false,
  labelActive: '',
  labelInactive: '',
  required: false,
  size: 'md',
  toggled: false
};

export default ToggleComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/toggle/toggle.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-toggle',
  templateUrl: './toggle.component.html',
  styleUrls: ['./toggle.component.scss']
})
export class ToggleComponent {
  @Input() size: string = 'md';

  @Input() disabled: boolean = false;

  @Input() labelActive: string = '';

  @Input() labelInactive: string = '';

  @Input() toggled: boolean = false;

  @Input() required: boolean = false;
}

<nexus-toggle [size]="size" [disabled]="disabled" [labelActive]="labelActive" [labelInactive]="labelInactive"
  [toggled]="toggled" [required]="required">
</nexus-toggle>
