// ui-nexus-design-system/playbook/react/src/components/slider/slider.tsx
import React from 'react';

import { NexusFormField, NexusLabel, NexusSlider } from '@nexus/react';

interface SliderComponentProps {
  disabled: boolean;
  max: number;
  min: number;
  required: boolean;
}

const SliderComponent: React.FC<SliderComponentProps> = (props) => (
  <NexusFormField>
    <NexusSlider {...props} data-testid="slider"></NexusSlider>
  </NexusFormField>
);

SliderComponent.defaultProps = {
  disabled: false,
  max: 100,
  min: 0,
  required: false
};

export default SliderComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/slider/slider.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-slider',
  templateUrl: './slider.component.html',
  styleUrls: ['./slider.component.scss']
})
export class SliderComponent {
  @Input() max: number = 100;

  @Input() min: number = 0;

  @Input() disabled: boolean = false;
}

<nexus-form-field>
  <nexus-slider data-testid="slider" [max]="max" [min]="min" [disabled]="disabled"></nexus-slider>
</nexus-form-field>
