// ui-nexus-design-system/playbook/angular/src/app/sb/components/card/02_backgroundColor.component.ts
import { Component } from '@angular/core';
import { BackgroundColor } from '../../constants';

@Component({
  selector: 'app-card-with-bg-color',
  templateUrl: './02_backgroundColor.component.html'
})
export default class CardWithBackgroundColorComponent {
  backgroundColor = BackgroundColor;
}

<div class="nexus-row">
    <div class="nexus-col-xs-6 nexus-col-sm-6 nexus-col-md-6 nexus-col-lg-6 nexus-col-xl-6">
        <nexus-card bg-color="#BACAF7" clickable="true" height="316px">
            <nexus-card-body>
                <h2 class="nexus-overline nexus-rhythm-1">{{backgroundColor.suggestedOffer}}</h2>
                <h3 class="nexus-h4 nexus-rhythm-1">{{backgroundColor.offerDetail}}</h3>
            </nexus-card-body>
            <nexus-card-footer>
                <a href="javascript:void(0)" class="nexus-btn nexus-btn-fluid">{{backgroundColor.enroll}}</a>
            </nexus-card-footer>
        </nexus-card>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/card/02_backgroundColor.tsx
import React from 'react';
import { NexusCard, NexusCardBody, NexusCardFooter } from '@nexus/react';
import { Link } from 'react-router-dom';
import { BackgroundColor } from '../../constants';

const BgColorComponent: React.FC = () => (
    <div className="nexus-row">
      <div className="nexus-col-xs-6 nexus-col-sm-6 nexus-col-md-6 nexus-col-lg-6 nexus-col-xl-6">
        <NexusCard data-testid="bg-color" bg-color="#BACAF7" clickable={true} height="316px">
          <NexusCardBody>
            <h2 data-testid="bg-color-overline" className="nexus-overline nexus-rhythm-1">{BackgroundColor.suggestedOffer}</h2>
            <h3 data-testid="bg-color-body" className="nexus-h4 nexus-rhythm-1">{BackgroundColor.offerDetail}</h3>
          </NexusCardBody>
          <NexusCardFooter>
            <Link to="" data-testid="bg-color-btn-Enroll" className="nexus-btn nexus-btn-fluid">{BackgroundColor.enroll}</Link>
          </NexusCardFooter>
        </NexusCard>
      </div>
    </div>
);

export default BgColorComponent;
