// ui-nexus-design-system/playbook/angular/src/app/sb/components/badge/02_appearence.component.ts
import { Component } from '@angular/core';
import { appearence } from '../../constants';

@Component({
  selector: 'app-badge-variant',
  templateUrl: './02_appearence.component.html'
})
export default class AppearenceComponent {
  badgeVariant = appearence;
}

<div class="nexus-body nexus-center-xs nexus-mt-1">
    <!-- Default Badge Example -->
    <div class="nexus-row nexus-mt-1 nexus-mt-1">
        <div class="nexus-col-xs-1">
            <div class="nexus-row">
                <div class="nexus-col-xs-4 nexus-center-xs">
                    <span>{{badgeVariant.default}}</span>
                </div>
            </div>
        </div>
        <div class="nexus-col-xs-2">
            <div class="nexus-row">
                <div class="nexus-col-xs-1">
                    <nexus-badge>{{badgeVariant.oneDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge>{{badgeVariant.twoDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge>{{badgeVariant.threeDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge>{{badgeVariant.fourDigit}}</nexus-badge>
                </div>
            </div>
        </div>
    </div>

    <!-- Success Badge Example -->
    <div class="nexus-row nexus-mt-1 nexus-mt-1">
        <div class="nexus-col-xs-1">
            <div class="nexus-row">
                <div class="nexus-col-xs-4 nexus-center-xs">
                    <span>{{badgeVariant.success}}</span>
                </div>
            </div>
        </div>
        <div class="nexus-col-xs-2">
            <div class="nexus-row">
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="success">{{badgeVariant.oneDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="success">{{badgeVariant.twoDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="success">{{badgeVariant.threeDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="success">{{badgeVariant.fourDigit}}</nexus-badge>
                </div>
            </div>
        </div>
    </div>

    <!-- Warning Badge Example -->
    <div class="nexus-row nexus-mt-1 nexus-mt-1">
        <div class="nexus-col-xs-1">
            <div class="nexus-row">
                <div class="nexus-col-xs-4 nexus-center-xs">
                    <span>{{badgeVariant.warning}}</span>
                </div>
            </div>
        </div>
        <div class="nexus-col-xs-2">
            <div class="nexus-row">
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="warning">{{badgeVariant.oneDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="warning">{{badgeVariant.twoDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="warning">{{badgeVariant.threeDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="warning">{{badgeVariant.fourDigit}}</nexus-badge>
                </div>
            </div>
        </div>
    </div>

    <!-- Error Badge Example -->
    <div class="nexus-row nexus-mt-1 nexus-mt-1">
        <div class="nexus-col-xs-1">
            <div class="nexus-row">
                <div class="nexus-col-xs-4 nexus-center-xs">
                    <span>{{badgeVariant.error}}</span>
                </div>
            </div>
        </div>
        <div class="nexus-col-xs-2">
            <div class="nexus-row">
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="error">{{badgeVariant.oneDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="error">{{badgeVariant.twoDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="error">{{badgeVariant.threeDigit}}</nexus-badge>
                </div>
                <div class="nexus-col-xs-1">
                    <nexus-badge variant="error">{{badgeVariant.fourDigit}}</nexus-badge>
                </div>
            </div>
        </div>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/badge/02_appearence.tsx
import React from 'react';
import { appearence } from '../../constants';
import { NexusBadge } from '@nexus/react';

export const AppearenceComponent: React.FC = () => (
    <div className="nexus-body nexus-center-xs nexus-mt-1">
        <div className="nexus-row nexus-mt-1 nexus-mt-1">
            <div className="nexus-col-xs-1">
                <div className="nexus-row">
                    <div className="nexus-col-xs-4 nexus-center-xs">
                        <span>{appearence.default}</span>
                    </div>
                </div>
            </div>
            <div className="nexus-col-xs-2">
                <div className="nexus-row">
                    <div className="nexus-col-xs-1">
                        <NexusBadge>{appearence.oneDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge>{appearence.twoDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge>{appearence.threeDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge>{appearence.fourDigit}</NexusBadge>
                    </div>
                </div>
            </div>
        </div>

        <div className="nexus-row nexus-mt-1 nexus-mt-1">
            <div className="nexus-col-xs-1">
                <div className="nexus-row">
                    <div className="nexus-col-xs-4 nexus-center-xs">
                        <span>{appearence.success}</span>
                    </div>
                </div>
            </div>
            <div className="nexus-col-xs-2">
                <div className="nexus-row">
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="success">{appearence.oneDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="success">{appearence.twoDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="success">{appearence.threeDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="success">{appearence.fourDigit}</NexusBadge>
                    </div>
                </div>
            </div>
        </div>

        <div className="nexus-row nexus-mt-1 nexus-mt-1">
            <div className="nexus-col-xs-1">
                <div className="nexus-row">
                    <div className="nexus-col-xs-4 nexus-center-xs">
                        <span>{appearence.warning}</span>
                    </div>
                </div>
            </div>
            <div className="nexus-col-xs-2">
                <div className="nexus-row">
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="warning">{appearence.oneDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="warning">{appearence.twoDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="warning">{appearence.threeDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="warning">{appearence.fourDigit}</NexusBadge>
                    </div>
                </div>
            </div>
        </div>

        <div className="nexus-row nexus-mt-1 nexus-mt-1">
            <div className="nexus-col-xs-1">
                <div className="nexus-row">
                    <div className="nexus-col-xs-4 nexus-center-xs">
                        <span>{appearence.error}</span>
                    </div>
                </div>
            </div>
            <div className="nexus-col-xs-2">
                <div className="nexus-row">
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="error">{appearence.oneDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="error">{appearence.twoDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="error">{appearence.threeDigit}</NexusBadge>
                    </div>
                    <div className="nexus-col-xs-1">
                        <NexusBadge variant="error">{appearence.fourDigit}</NexusBadge>
                    </div>
                </div>
            </div>
        </div>
    </div>
);


export default AppearenceComponent;
