// ui-nexus-design-system/playbook/react/src/sb/components/form-field/01_form-field.tsx
import React, { useState } from 'react';
import { NexusFormField, NexusLabel, NexusInput } from '@nexus/react';
import { formField } from '../../constants';

const FormFieldComponent: React.FC = () => {
  const [value, setValue] = useState('');

  return (
      <NexusFormField>
        <NexusLabel data-testid="label-first-name">{formField.title}</NexusLabel>
        <NexusInput
          data-testid="form-field-textbox"
          value={value}
          onInput={(event: any) => setValue(event.target.value)}
        ></NexusInput>
      </NexusFormField>
  );
};

export default FormFieldComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/form-field/01_form-field.component.ts
import { Component, Input } from '@angular/core';
import { FormControl } from '@angular/forms';
import { formField } from '../../constants';
@Component({
  selector: 'app-form-field-primary',
  templateUrl: './01_form-field.component.html'
})
export default class FormFieldComponent {
  @Input() showErrors: boolean;

  @Input() showMessages: boolean;

  reactiveValue = new FormControl('');

  title = formField.title;
}

<nexus-form-field [showErrors]="showErrors" [showMessages]="showMessages">
  <nexus-label data-testid="label-first-name">{{ title }}</nexus-label>
  <nexus-input
    data-testid="form-field-textbox"
    [formControl]="reactiveValue"
    [value]="reactiveValue.value"
  ></nexus-input>
</nexus-form-field>
