// ui-nexus-design-system/playbook/react/src/components/pin-entry/pin-entry.tsx
import React from 'react';
import { NexusPinEntry } from '@nexus/react';

interface PinEntryComponentProps {
  length: number;
  disabled: boolean;
  type: 'text' | 'password' | 'tel';
}

const PinEntryComponent: React.FC<PinEntryComponentProps> = (props) => (
  <NexusPinEntry {...props} data-testid="pin-entry"></NexusPinEntry>
);

PinEntryComponent.defaultProps = {
  length: 3,
  disabled: false,
  type: 'text'
};

export default PinEntryComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/pin-entry/pin-entry.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-pin-entry',
  templateUrl: './pin-entry.component.html',
  styleUrls: ['./pin-entry.component.scss']
})
export class PinEntryComponent {
  @Input() length: number = 3;

  @Input() disabled: boolean;

  @Input() type: string;
}

<nexus-pin-entry data-testid="pin-entry" [length]="length" [disabled]="disabled" [type]="type"></nexus-pin-entry>
