// ui-nexus-design-system/playbook/angular/src/app/components/toast/toast.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-toast',
  templateUrl: './toast.component.html',
  styleUrls: ['./toast.component.scss']
})
export class ToastComponent {
  @Input() autoClose: number;

  @Input() closeable: boolean = false;

  @Input() show: boolean = true;

  @Input() variant: string = 'info';
}

<p class="nexus-h5">Toast Default</p>
<div class="nexus-rhythm-2">
  <nexus-toast
    [autoClose]="autoClose"
    [closeable]="closeable"
    [show]="show"
    [variant]="variant"
    data-testid="information-toast-message"
    >Default message.</nexus-toast
  >
</div>

<p class="nexus-h5">Toast Variants</p>

<div class="nexus-rhythm-2">
  <nexus-toast data-testid="information-toast-message">Information message.</nexus-toast>
</div>

<div class="nexus-rhythm-2">
  <nexus-toast data-testid="success-toast-message" class="nexus-rhythm-2" variant="success"
    >Success message.</nexus-toast
  >
</div>

<div class="nexus-rhythm-2">
  <nexus-toast data-testid="warning-toast-message" class="nexus-rhythm-2" variant="warning"
    >Warning message.</nexus-toast
  >
</div>

<div class="nexus-rhythm-2">
  <nexus-toast data-testid="error-toast-message" class="nexus-rhythm-2" variant="error">Error message.</nexus-toast>
</div>

// ui-nexus-design-system/playbook/react/src/components/toast/toast.tsx
import React from 'react';

import { NexusToast } from '@nexus/react';

interface ToastComponentProps {
  autoClose: number;
  closeable: boolean;
  show: boolean;
  position: 'top' | 'bottom' | undefined;
  variant: 'info' | 'success' | 'warning' | 'error' | 'custom';
}

const ToastComponent: React.FC<ToastComponentProps> = (props) => {
  return (
    <>
      <h5 className="nexus-h5">Toast Default</h5>
      <div className="nexus-rhythm-2">
        <NexusToast {...props} data-testid="information-toast-message">
          Default message.
        </NexusToast>
      </div>

      <h5 className="nexus-h5">Toast Variants</h5>
      <div className="nexus-rhythm-2">
        <NexusToast data-testid="information-toast-message">Information message.</NexusToast>
      </div>

      <div className="nexus-rhythm-2">
        <NexusToast data-testid="success-toast-message" className="nexus-rhythm-2" variant="success">
          Success message.
        </NexusToast>
      </div>

      <div className="nexus-rhythm-2">
        <NexusToast data-testid="warning-toast-message" className="nexus-rhythm-2" variant="warning">
          Warning message.
        </NexusToast>
      </div>

      <div className="nexus-rhythm-2">
        <NexusToast data-testid="error-toast-message" className="nexus-rhythm-2" variant="error">
          Error message.
        </NexusToast>
      </div>
    </>
  );
};

ToastComponent.defaultProps = {
  closeable: false,
  show: true,
  position: undefined,
  variant: 'info'
};

export default ToastComponent;
