// ui-nexus-design-system/playbook/angular/src/app/components/toast-examples/toast-examples.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-toast-examples',
  templateUrl: './toast-examples.component.html',
  styleUrls: ['./toast-examples.component.scss']
})
export class ToastExamplesComponent {
  show: boolean = false;
}

<p class="nexus-h5">Dynamic Toast</p>

<button data-testid="btn-trigger-toast" class="nexus-btn-primary nexus-btn-large nexus-rhythm-4" (click)="show = true">Trigger toast</button>
<nexus-toast data-testid="btn-trigger-toast-info" *ngIf="show" closeable="true" (closeEvent)="show = false">Information message.</nexus-toast>


<div class="nexus-rhythm-2">
    <nexus-toast data-testid="disappear-toast" class="nexus-rhythm-2" variant="custom" icon-src="./assets/icons/action/ic_3d_rotation_24px.svg"
        auto-close=5000>Test
        This message will disappear in 5 sec.</nexus-toast>
</div>

<div class="nexus-rhythm-2">
    <nexus-toast data-testid="float-bottom-toast" class="nexus-rhythm-2" variant="info" position="bottom">Float at the bottom of the page.</nexus-toast>
</div>

<div class="nexus-rhythm-2">
    <nexus-toast data-testid="float-top-toast" class="nexus-rhythm-2" variant="info" position="top">Float at the top of the page.</nexus-toast>
</div>

// ui-nexus-design-system/playbook/react/src/components/toast/toast-examples.tsx
import React, { useState } from 'react';
import infoIcon from '@nexus/core/dist/assets/icons/content/ic_sort_24px.svg';
import { NexusToast } from '@nexus/react';

const ToastExampleComponent: React.FC = () => {
  const [show, setShow] = useState(false);

  return (
    <>
      <p className="nexus-h5">Dynamic Toast</p>
      <button
        data-testid="btn-trigger-toast"
        className="nexus-btn-primary nexus-btn-large nexus-rhythm-4" onClick={() => setShow(true)}>Trigger toast</button>
      {show && <NexusToast
        data-testid="btn-trigger-toast-info"
        closeable={true} onCloseEvent={() => setShow(false)}>Information message.</NexusToast>}

      <NexusToast
        data-testid="float-top-toast"
        className="nexus-rhythm-2" variant="info" position="top">Float at the top of the page.</NexusToast>

      <NexusToast
        data-testid="float-bottom-toast"
        className="nexus-rhythm-2" variant="info" position="bottom">Float at the bottom of the page.</NexusToast>

      <NexusToast
        data-testid="disappear-toast"
        class="nexus-rhythm-2" variant="custom" icon-src={infoIcon}
        auto-close={5000}>Test
        This message will disappear in 5 sec.
      </NexusToast>
    </>
  );
};

export default ToastExampleComponent;
