// ui-nexus-design-system/playbook/react/src/sb/components/search/01_search.tsx
import React, { useState } from 'react';

import { NexusIcon, NexusInput, NexusSearch, NexusSearchList, NexusSearchListItem } from '@nexus/react';
import { DefaultSearch } from '../../constants';

const SearchComponent: React.FC = () => {
  const items = [{ name: 'Item 1' }, { name: 'Item 2' }, { name: 'Item 3' }];

  const [filtereditem, setFiltereditem] = useState(items);
  const Performfilter = (e: any) => {
    const keyword = e.target.value;

    if (keyword !== '') {
      const results = items.filter((item) => item.name.toLowerCase().indexOf(keyword.toLowerCase()) !== -1);
      setFiltereditem(results);
    } else {
      setFiltereditem([...items]);
    }
  };
  return (
    <NexusSearch>
      <NexusInput data-testid="search-bar" onKeyUp={Performfilter} autocomplete="off" placeholder={DefaultSearch.placeholder}>
        <NexusIcon data-testid="search-icon" src={DefaultSearch.searchIconSrc}></NexusIcon>
      </NexusInput>
      <NexusSearchList>
        <div>
          {filtereditem.length > 0 && (
            <div>
              {filtereditem.map((item) => (
                <NexusSearchListItem data-testid="search-list" key={item.name}>
                  <button>{item.name}</button>
                </NexusSearchListItem>
              ))}
            </div>
          )}
        </div>
      </NexusSearchList>
    </NexusSearch>
  );
};

export default SearchComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/search/01_search.component.ts
import { Component, OnInit } from '@angular/core';
import { DefaultSearch } from '../../constants';

@Component({
  selector: 'app-search',
  templateUrl: './01_search.component.html'
})
export default class SearchComponent implements OnInit {
  Items: any = [];

  filteredItem: any = [];

  defaultSearch = DefaultSearch;

  ngOnInit(): void {
    this.Items.push('Item 1');
    this.Items.push('Item 2');
    this.Items.push('Item 3');
    this.filteredItem = this.Items;
  }

  performFilter(event: any) {
    const filterBy = event.target.value.toLocaleLowerCase();
    this.filteredItem = this.Items.filter((item: any) => item.toLocaleLowerCase().indexOf(filterBy) !== -1);
  }
}

<nexus-search data-testid="search-bar">
    <nexus-input (keyup)="performFilter($event)" autocomplete="off" [placeholder]="defaultSearch.placeholder">
      <nexus-icon data-testid="search-icon" [src]="defaultSearch.searchIconSrc"></nexus-icon>
    </nexus-input>
    <nexus-search-list>
      <nexus-search-list-item *ngFor="let item of filteredItem">
        <button>{{ item }}</button>
      </nexus-search-list-item>
    </nexus-search-list>
  </nexus-search>
