// ui-nexus-design-system/playbook/react/src/components/form-field/form-field.tsx
import React, { useState } from 'react';
import { NexusFormField, NexusLabel, NexusInput } from '@nexus/react';
import Note from '../notecontainer/note';

const FormFieldComponent: React.FC = () => {
    const [value, setValue] = useState('');

    return (
        <div>
            <NexusFormField>
                <NexusLabel
                    data-testid="label-first-name"
                >
                    First name
                </NexusLabel>
                <NexusInput
                    data-testid="form-field-textbox"
                    value={value} onInput={(event: any) => setValue(event.target.value)}>
                </NexusInput>
            </NexusFormField>
            <Note noteType="eventNote" />
        </div>
    );
};

export default FormFieldComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/form-field/form-field.component.ts
import { Component, Input } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-form-field',
  templateUrl: './form-field.component.html',
  styleUrls: ['./form-field.component.scss']
})
export class FormFieldComponent {
  @Input() showErrors: boolean;

  @Input() showMessages: boolean;

  reactiveValue = new FormControl('');
}

<nexus-form-field [showErrors]="showErrors" [showMessages]="showMessages">
  <nexus-label data-testid="label-first-name">First name</nexus-label>
  <nexus-input
    data-testid="form-field-textbox"
    [formControl]="reactiveValue"
    [value]="reactiveValue.value"
  ></nexus-input>
</nexus-form-field>
