// ui-nexus-design-system/playbook/angular/src/app/sb/components/notification/01_notification.component.ts
import { Component, Input } from '@angular/core';
import { notification } from '../../constants';

@Component({
  selector: 'app-notification',
  templateUrl: './01_notification.component.html'
})
export default class NotificationComponent {
  @Input() variant: string = notification.variant;

  message: string = notification.text;
}

<div class="nexus-row nexus-around-xs">
  <div class="nexus-col-xs-1">
    <div class="nexus-row nexus-mt-2">
      <div class="nexus-col-xs-4">
        <nexus-notification data-testid="notification-info" [variant]="variant">{{ message }}</nexus-notification>
      </div>
    </div>
  </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/notification/01_notification.tsx
import React from 'react';
import { notification } from '../../constants';
import PropTypes from 'prop-types';
import { NexusNotification } from '@nexus/react';
import { typVariant } from '@nexus/core/dist/types/components/nexus-notification/nexus-notification';

const NotificationComponent: React.FC = (props) => {
  const { message = notification.text, variant = notification.variant } = { ...props };

  return (
    <div className="nexus-row nexus-around-xs">
      <div className="nexus-col-xs-1">
        <div className="nexus-row nexus-mt-2">
          <div className="nexus-col-xs-4">
            <NexusNotification data-testid="notification-message" {...props} variant={variant as typVariant}>
              {message}
            </NexusNotification>
          </div>
        </div>
      </div>
    </div>
  );
}

NotificationComponent.propTypes = {
  variant: PropTypes.string,
  message: PropTypes.string
};

export default NotificationComponent;
