// ui-nexus-design-system/playbook/angular/src/app/sb/components/notification/02_overlay.component.ts
import { Component } from '@angular/core';
import { notificationOverlay } from '../../constants';

@Component({
  selector: 'app-notification-overlay',
  templateUrl: './02_overlay.component.html'
})
export default class NotificationOverlayComponent {
  bgColor: string = '';

  bgImage: string = './assets/images/card-header-image.png';

  clickable: boolean = false;

  height: string = '';

  notificationOverlay = notificationOverlay;
}

<nexus-card [bgColor]="bgColor" [clickable]="clickable" [height]="height">
  <nexus-card-avatar>
    <img [src]="notificationOverlay.srcImg" [alt]="notificationOverlay.username" />
  </nexus-card-avatar>
  <nexus-card-header>
    <nexus-card-header-title>{{notificationOverlay.username}}</nexus-card-header-title>
    <nexus-notification data-testid="notification-info" [variant]="notificationOverlay.variant">{{notificationOverlay.text}}</nexus-notification>
    <nexus-card-header-button>
      <button class="nexus-btn-icon" id="btn" title="btn">
        <nexus-icon [src]="notificationOverlay.iconSrc"></nexus-icon>
      </button>
    </nexus-card-header-button>
  </nexus-card-header>
</nexus-card>

// ui-nexus-design-system/playbook/react/src/sb/components/notification/02_overlay.tsx
import React from 'react';
import PropTypes from 'prop-types';
import { notificationOverlay } from '../../constants';
import {
    NexusCard,
    NexusCardAvatar,
    NexusCardHeader,
    NexusCardHeaderButton,
    NexusCardHeaderTitle,
    NexusIcon,
    NexusNotification
} from '@nexus/react';

import CardHeaderImage from '@nexus/core/dist/assets/images/card-header-image.png';
import ButtonIcon from '@nexus/core/dist/assets/icons/navigation/ic_more_horiz_24px.svg';
import { typVariant } from '@nexus/core/dist/types/components/nexus-notification/nexus-notification';


const NotificationOverlayComponent: React.FC = (props) => {
    const { variant = notificationOverlay.variant } = { ...props };

    return (
        <div className="nexus-rhythm-4">
            <NexusCard clickable={false}>
                <NexusCardAvatar>
                    <img src={CardHeaderImage} alt="Michael Bay" />
                </NexusCardAvatar>
                <NexusCardHeader>
                    <NexusCardHeaderTitle>Michael Bay</NexusCardHeaderTitle>
                    <NexusNotification data-testid="notification-message" {...props} variant={variant as typVariant}>
                        {notificationOverlay.text}
                    </NexusNotification>
                    <NexusCardHeaderButton>
                        <button className="nexus-btn-icon" id="btn" title="btn">
                            <NexusIcon src={ButtonIcon} />
                        </button>
                    </NexusCardHeaderButton>
                </NexusCardHeader>
            </NexusCard>
        </div>
    );
}

NotificationOverlayComponent.propTypes = {
    variant: PropTypes.string,
    message: PropTypes.string
};

export default NotificationOverlayComponent;
