// ui-nexus-design-system/playbook/react/src/sb/components/toggle/05_switchSize.tsx
import React from 'react';
import { size } from '../../constants';

import { NexusToggle } from '@nexus/react';

const SwitchSize: React.FC = () => {
  return (
    <>
      <div className="nexus-row nexus-around-xs">
        <div className="nexus-col-lg-4">
          <p className="nexus-h6">{size.xs}</p>
          <NexusToggle data-testid="toggle-size-xs" size="xs" />
        </div>
        <div className="nexus-col-lg-4">
          <p className="nexus-h6">{size.sm}</p>
          <NexusToggle data-testid="toggle-size-sm" size="sm" />
        </div>
        <div className="nexus-col-lg-4">
          <p className="nexus-h6">{size.md}</p>
          <NexusToggle data-testid="toggle-size-md" size="md" />
        </div>
        <div className="nexus-col-lg-4">
          <p className="nexus-h6">{size.lg}</p>
          <NexusToggle data-testid="toggle-size-lg" size="lg" />
        </div>
        <div className="nexus-col-lg-4">
          <p className="nexus-h6">{size.xl}</p>
          <NexusToggle data-testid="toggle-size-xl" size="xl" />
        </div>
      </div>
    </>
  );
};

export default SwitchSize;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/toggle/05_switchSize.component.ts
import { Component } from '@angular/core';
import { size } from '../../constants';

@Component({
  selector: 'app-switch-size',
  templateUrl: './05_switchSize.component.html'
})
export default class SwitchSizeComponent {
  size = size;
}

<div class="nexus-row nexus-around-xs">
    <div class="nexus-col-lg-4">
        <p class="nexus-h6">{{size.xs}}</p>
        <nexus-toggle data-testid="toggle-size-xs" size="xs"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-4">
        <p class="nexus-h6">{{size.sm}}</p>
        <nexus-toggle data-testid="toggle-size-sm" size="sm"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-4">
        <p class="nexus-h6">{{size.md}}</p>
        <nexus-toggle data-testid="toggle-size-md" size="md"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-4">
        <p class="nexus-h6">{{size.lg}}</p>
        <nexus-toggle data-testid="toggle-size-lg" size="lg"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-4">
        <p class="nexus-h6">{{size.xl}}</p>
        <nexus-toggle data-testid="toggle-size-xl" size="xl"></nexus-toggle>
    </div>
</div>
