// ui-nexus-design-system/playbook/react/src/sb/components/toggle/06_buttonSize.tsx
import React from 'react';
import { size } from '../../constants';

import { NexusToggle } from '@nexus/react';

const ButtonSizeComponent: React.FC = () => {
  return (
    <>
      <div className="nexus-row">
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">{size.xs}</p>
          <NexusToggle data-testid="toggle-btn-size-xs" type="button" label-inactive="hide" label-active="show" size="xs" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">{size.sm}</p>
          <NexusToggle data-testid="toggle-btn-size-sm" type="button" label-inactive="hide" label-active="show" size="sm" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">{size.md}</p>
          <NexusToggle data-testid="toggle-btn-size-md" type="button" label-inactive="hide" label-active="show" size="md" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">{size.lg}</p>
          <NexusToggle data-testid="toggle-btn-size-lg" type="button" label-inactive="hide" label-active="show" size="lg" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">{size.xl}</p>
          <NexusToggle data-testid="toggle-btn-size-xl" type="button" label-inactive="hide" label-active="show" size="xl" />
        </div>
      </div>        </>
  );
};

export default ButtonSizeComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/toggle/06_buttonSize.component.ts
import { Component } from '@angular/core';
import { size } from '../../constants';

@Component({
  selector: 'app-button-size',
  templateUrl: './06_buttonSize.component.html'
})
export default class ButtonSizeComponent {
  size = size;
}

<div class="nexus-row">
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">{{size.xs}}</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="xs"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">{{size.sm}}</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="sm"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">{{size.md}}</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="md"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">{{size.lg}}</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="lg"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">{{size.xl}}</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="xl"></nexus-toggle>
    </div>
</div>
