// ui-nexus-design-system/playbook/angular/src/app/components/search/search.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {
  Items: any = [];

  filteredItem: any = [];

  ngOnInit(): void {
    this.Items.push('Item 1');
    this.Items.push('Item 2');
    this.Items.push('Item 3');
    this.filteredItem = this.Items;
  }

  performFilter(event: any) {
    const filterBy = event.target.value.toLocaleLowerCase();
    this.filteredItem = this.Items.filter((item: any) => item.toLocaleLowerCase().indexOf(filterBy) !== -1);
  }
}

<nexus-search data-testid="search-bar">
  <nexus-input (keyup)="performFilter($event)" autocomplete="off" placeholder="Search">
    <nexus-icon data-testid="search-icon" src="./assets/icons/action/ic_search_24px.svg"></nexus-icon>
  </nexus-input>
  <nexus-search-list>
    <nexus-search-list-item *ngFor="let item of filteredItem">
      <button>{{ item }}</button>
    </nexus-search-list-item>
  </nexus-search-list>
</nexus-search>

// ui-nexus-design-system/playbook/react/src/components/search/search.tsx
import React, { useState } from 'react';

import { NexusIcon, NexusInput, NexusSearch, NexusSearchList, NexusSearchListItem } from '@nexus/react';

import ActionIcSearch24px from '@nexus/core/dist/assets/icons/action/ic_search_24px.svg';

const SearchComponent: React.FC = () => {
  const items = [{ name: 'Item 1' }, { name: 'Item 2' }, { name: 'Item 3' }];

  const [filtereditem, setFiltereditem] = useState(items);
  const Performfilter = (e: any) => {
    const keyword = e.target.value;

    if (keyword !== '') {
      const results = items.filter((item) => item.name.toLowerCase().indexOf(keyword.toLowerCase()) !== -1);
      setFiltereditem(results);
    } else {
      setFiltereditem([...items]);
    }
  };
  return (
    <NexusSearch>
      <NexusInput data-testid="search-bar" onKeyUp={Performfilter} autocomplete="off" placeholder="Search">
        <NexusIcon data-testid="search-icon" src={ActionIcSearch24px}></NexusIcon>
      </NexusInput>
      <NexusSearchList>
        <div>
          {filtereditem.length > 0 && (
            <div>
              {filtereditem.map((item) => (
                <NexusSearchListItem data-testid="search-list" key={item.name}>
                  <button>{item.name}</button>
                </NexusSearchListItem>
              ))}
            </div>
          )}
        </div>
      </NexusSearchList>
    </NexusSearch>
  );
};

export default SearchComponent;
