// ui-nexus-design-system/playbook/react/src/sb/components/toast/01_toast.tsx
import React from 'react';
import { defaultToast } from '../../constants';
import PropTypes from 'prop-types';
import { NexusToast } from '@nexus/react';
import { typVariant1 } from '@nexus/core/dist/types/components/nexus-toast/nexus-toast';

const ToastComponent: React.FC = (props) => {
  const { variant = 'default' } = { ...props };


  return (
    <NexusToast
      show={defaultToast.show}
      closeable={defaultToast.closeable}
      {...props} data-testid="nexus-toast" variant={variant as typVariant1}>
      {defaultToast.message}
    </NexusToast>
  );
};

ToastComponent.propTypes = {
  closeable: PropTypes.bool,
  show: PropTypes.bool,
  position: PropTypes.string,
  variant: PropTypes.string
};

ToastComponent.defaultProps = {
  variant: 'default'
}

export default ToastComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/toast/01_toast.component.ts
import { Component, Input } from '@angular/core';
import { defaultToast } from '../../constants';

@Component({
  selector: 'app-toast',
  templateUrl: './01_toast.component.html'
})
export default class ToastComponent {
  @Input() autoClose: number;

  @Input() closeable: boolean = defaultToast.closeable;

  @Input() show: boolean = defaultToast.show;

  @Input() variant: string = defaultToast.variant;

  @Input() iconSrc: string = defaultToast.iconSrc;

  @Input() position: string = defaultToast.position;

  message = defaultToast.message;
}

  <nexus-toast
    [iconSrc]="iconSrc"
    [position]="position"
    [autoClose]="autoClose"
    [closeable]="closeable"
    [show]="show"
    [variant]="variant"
    data-testid="information-toast-message">{{message}}</nexus-toast>
