// ui-nexus-design-system/playbook/react/src/sb/components/toast/02_variants.tsx
import React from 'react';
import { toastVariants } from '../../constants';
import { NexusToast } from '@nexus/react';

const ToastVariantComponent: React.FC = () => {

  return (
      <>
        <NexusToast
            data-testid="toast-info"
            closeable={toastVariants.closeable}
            show={toastVariants.show}
            variant='info'>{toastVariants.info}</NexusToast>
        <div className='nexus-pt-1 nexus-pb-1'></div>
        <NexusToast
            data-testid="toast-error"
           closeable={toastVariants.closeable}
           show={toastVariants.show}
            variant='error'>{toastVariants.error}</NexusToast>
        <div className='nexus-pt-1 nexus-pb-1'></div>
        <NexusToast
            data-testid="toast-success"
           closeable={toastVariants.closeable}
           show={toastVariants.show}
            variant='success'>{toastVariants.success}</NexusToast>
        <div className='nexus-pt-1 nexus-pb-1'></div>
        <NexusToast
            data-testid="toast-warning"
           closeable={toastVariants.closeable}
           show={toastVariants.show}
            variant='warning'>{toastVariants.warning}</NexusToast>
        <div className='nexus-pt-1 nexus-pb-1'></div>
        <NexusToast
            data-testid="toast-custom"
           closeable={toastVariants.closeable}
           show={toastVariants.show}
            variant='custom'
            iconSrc={toastVariants.iconSrc}>{toastVariants.custom}</NexusToast>
      </>
  );
};

export default ToastVariantComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/toast/02_variants.component.ts
import { Component } from '@angular/core';
import { toastVariants } from '../../constants';

@Component({
  selector: 'app-toast-variants',
  templateUrl: './02_variants.component.html'
})
export default class ToastVariantComponent {
  toastVariants = toastVariants;
}

<div class="nexus-row">
    <div class="nexus-col-xs-4 nexus-mt-2 neuxs-mb-1">
        <nexus-toast data-testid="toast-info" [show]="toastVariants.show" [closeable]="toastVariants.closeable"
            variant="info">{{toastVariants.info}}</nexus-toast>
    </div>
    <div class="nexus-col-xs-4 nexus-mt-2 neuxs-mb-1">
        <nexus-toast data-testid="toast-error" [show]="toastVariants.show" [closeable]="toastVariants.closeable"
            variant="error">{{toastVariants.error}}</nexus-toast>
    </div>
    <div class="nexus-col-xs-4 nexus-mt-2 neuxs-mb-1">
        <nexus-toast data-testid="toast-success" [show]="toastVariants.show" [closeable]="toastVariants.closeable"
            variant="success">{{toastVariants.success}}</nexus-toast>
    </div>
    <div class="nexus-col-xs-4 nexus-mt-2 neuxs-mb-1">
        <nexus-toast data-testid="toast-warning" [show]="toastVariants.show" [closeable]="toastVariants.closeable"
            variant="warning">{{toastVariants.warning}}</nexus-toast>
    </div>
    <div class="nexus-col-xs-4 nexus-mt-2 neuxs-mb-2">
        <nexus-toast data-testid="toast-custom" [show]="toastVariants.show" [closeable]="toastVariants.closeable"
            [iconSrc]="toastVariants.iconSrc" variant="custom">{{toastVariants.custom}}</nexus-toast>
    </div>
</div>
