// ui-nexus-design-system/playbook/react/src/sb/components/stepper/01_stepper.tsx
import React from 'react';
import PropTypes from 'prop-types';
import { DefaultStepper } from '../../constants';
import { NexusStepper, NexusStepperItem } from '@nexus/react';

const StepperComponent: React.FC = (props) => {
  const { steppertype = "row" } = { ...props };
  return (
    <div className="nexus-center-xs nexus-pt-3 nexus-ml-6">
      <NexusStepper steppertype={steppertype}>
        <NexusStepperItem status="complete">
          <button aria-label={'step1'}>{DefaultStepper.source}</button>
        </NexusStepperItem>
        <NexusStepperItem status="active">
          <button aria-current={'step'}>{DefaultStepper.dataExploration}</button>
        </NexusStepperItem>
        <NexusStepperItem status="default">
          <button aria-label={'step3'}>{DefaultStepper.featureSets}</button>
        </NexusStepperItem>
        <NexusStepperItem status="warning">
          <button aria-label={'step4'}>{DefaultStepper.training}</button>
        </NexusStepperItem>
        <NexusStepperItem>
          <button aria-label={'step5'}>{DefaultStepper.test}</button>
        </NexusStepperItem>
      </NexusStepper>
    </div>
  );
};

StepperComponent.propTypes = {
  steppertype: PropTypes.string
}

export default StepperComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/stepper/01_stepper.component.ts
import { Component, Input } from '@angular/core';
import { DefaultStepper } from '../../constants';

@Component({
  selector: 'app-stepper',
  templateUrl: './01_stepper.component.html'
})
export default class StepperComponent {
  @Input() steppertype: string;

  DefaultStepper = DefaultStepper;
}

<div class="nexus-center-xs nexus-pt-3 nexus-pl-6">
  <nexus-stepper [steppertype]="steppertype">
    <nexus-stepper-item status="complete">
      <button aria-label="step1" class="step-item-target">{{DefaultStepper.source}}</button>
    </nexus-stepper-item>
    <nexus-stepper-item status="active">
      <button aria-current="step">{{DefaultStepper.dataExploration}}</button>
    </nexus-stepper-item>
    <nexus-stepper-item status="default">
      <button aria-label="step3">{{DefaultStepper.featureSets}}</button>
    </nexus-stepper-item>
    <nexus-stepper-item status="warning">
      <button aria-label="step4">{{DefaultStepper.training}}</button>
    </nexus-stepper-item>
    <nexus-stepper-item>
      <button aria-label="step5">{{DefaultStepper.test}}</button>
    </nexus-stepper-item>
  </nexus-stepper>
</div>
