// ui-nexus-design-system/playbook/react/src/components/stepper/stepper.tsx
import React from 'react';
import { NexusStepper, NexusStepperItem } from '@nexus/react';

interface StepperComponentProps {
  steppertype: 'row' | 'column';
}

const StepperComponent: React.FC<StepperComponentProps> = (props) => {
  const { steppertype } = props;
  return (
    <>
      <NexusStepper steppertype={steppertype}>
        <NexusStepperItem status="complete">
          <button aria-label={'step1'}>Source data</button>
        </NexusStepperItem>
        <NexusStepperItem status="active">
          <button aria-current={'step'}>Data exploration</button>
        </NexusStepperItem>
        <NexusStepperItem status="default">
          <button aria-label={'step3'}>Feature sets</button>
        </NexusStepperItem>
        <NexusStepperItem status="warning">
          <button aria-label={'step4'}>Training</button>
        </NexusStepperItem>
        <NexusStepperItem>
          <button aria-label={'step5'}>Test & analysis</button>
        </NexusStepperItem>
      </NexusStepper>
    </>
  );
};
export default StepperComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/stepper/stepper.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-stepper',
  templateUrl: './stepper.component.html',
  styleUrls: ['./stepper.component.scss']
})
export class StepperComponent implements OnInit {
  @Input() steppertype: string;

  constructor() {}

  ngOnInit(): void {}
}

<nexus-stepper [steppertype]="steppertype">
  <nexus-stepper-item status="complete">
    <button aria-label="step1" class="step-item-target">Source data</button>
  </nexus-stepper-item>
  <nexus-stepper-item status="active">
    <button aria-current="step">Data exploration</button>
  </nexus-stepper-item>
  <nexus-stepper-item status="default">
    <button aria-label="step3">Feature sets</button>
  </nexus-stepper-item>
  <nexus-stepper-item status="warning">
    <button aria-label="step4">Training</button>
  </nexus-stepper-item>
  <nexus-stepper-item>
    <button aria-label="step5">Test & analysis</button>
  </nexus-stepper-item>
</nexus-stepper>
