// ui-nexus-design-system/playbook/react/src/sb/components/tree/01_tree.tsx
import React from 'react';
import { DefaultTree } from '../../constants';
import { NexusTree, NexusTreeTrigger, NexusTreeContent } from '@nexus/react';

interface TreeComponentProps {
  open: boolean;
}

const TreeComponent: React.FC<TreeComponentProps> = (props) => {
  const { open } = { ...props };

  return (
    <NexusTree open={open}>
      <NexusTreeTrigger data-testid="tree-trigger">{DefaultTree.title}</NexusTreeTrigger>
      <NexusTreeContent>
        <ul data-testid="tree-content-item">
          <li>{DefaultTree.option_1}</li>
          <li>{DefaultTree.option_2}</li>
          <li>{DefaultTree.option_3}</li>
        </ul>
      </NexusTreeContent>
    </NexusTree>
  );
};

TreeComponent.defaultProps = {
  open: false
};

export default TreeComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/tree/01_tree.component.ts
import { Component, Input } from '@angular/core';
import { DefaultTree } from '../../constants';

@Component({
  selector: 'app-tree',
  templateUrl: './01_tree.component.html'
})
export default class TreeComponent {
  @Input() open: boolean = false;

  defaultTree = DefaultTree;
}

<nexus-tree [open]="open">
  <nexus-tree-trigger>{{defaultTree.title}}</nexus-tree-trigger>
  <nexus-tree-content>
    <ul>
      <li>{{defaultTree.option_1}}</li>
      <li>{{defaultTree.option_2}}</li>
      <li>{{defaultTree.option_3}}</li>
    </ul>
  </nexus-tree-content>
</nexus-tree>
