// ui-nexus-design-system/playbook/angular/src/app/sb/components/table/02_tableBasic.component.ts
import { Component } from '@angular/core';
import { rowData, columnDefs } from '../../constants';

@Component({
  selector: 'app-table-basic',
  templateUrl: './02_tableBasic.component.html'
})
export default class TableBasicComponent {
  tHeadSection = columnDefs.map((item) => item.label);

  tData = rowData.map((row) => Object.values(row));
}

<table class="nexus-table">
    <thead>
        <tr>
            <th *ngFor="let header of tHeadSection;">{{header}}</th>
        </tr>
    </thead>
    <tbody>
        <tr *ngFor="let row of tData">
            <td *ngFor="let value of row">{{value}}</td>
        </tr>
    </tbody>
</table>

// ui-nexus-design-system/playbook/react/src/sb/components/table/02_tableBasic.tsx
import React from 'react';
import { columnDefs, rowData } from '../../constants';

const BasicTableComponent: React.FC = () => {
    const tHeadSection = columnDefs.map((item, idx) => <th key={idx}>{item.label}</th>);
    const tBodySection = rowData.map((row, idx) => <tr key={idx}>{Object.values(row).map((value, idy) => <td key={idy}>{value}</td>)}</tr>);

    return (
        <table className='nexus-table'>
            <thead>
                <tr>
                    {tHeadSection}
                </tr>
            </thead>
            <tbody>
                {tBodySection}
            </tbody>
        </table>
    )
}

export default BasicTableComponent;
