// ui-nexus-design-system/playbook/angular/src/app/sb/components/toast/03_autoClose.component.ts
import { Component } from '@angular/core';
// eslint-disable-next-line no-restricted-imports
import { startWith, Subject, switchMap, timer } from 'rxjs';

@Component({
  selector: 'app-toast-auto-close',
  templateUrl: './03_autoClose.component.html'
})
export default class ToastAutoCloseComponent {
  timeLeft: number = 20;

  interval;

  constructor() {
    this.startTimer();
  }

  restartTimer(event) {
    this.timeLeft = 20;
    this.startTimer();
  }

  startTimer() {
    this.interval = setInterval(() => {
      if (this.timeLeft > 0) {
        this.timeLeft -= 1;
      }
    }, 1000);
  }
}

<div class="nexus-center-xs nexus-mt-5">
    <div *ngIf="timeLeft <= 1; else elseBlock">
        <button class="nexus-mt-1 nexus-btn nexus-btn-primary" (click)="restartTimer($event)">Reset</button>
      </div>
      <ng-template #elseBlock>
        <nexus-toast
        data-testid='toast-with-auto-close'
        show
        [autoClose]="timeLeft * 1000"
        variant="info">The toast will diappear after {{timeLeft}}s.</nexus-toast>
      </ng-template>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/toast/03_autoClose.tsx
import React, { useEffect, useState } from 'react';
import { toastAutoClose } from '../../constants';
import { NexusToast } from '@nexus/react';

const ToastWithAutoCloseComponent: React.FC = () => {
    const [timer, setTimer] = useState(toastAutoClose.timeLeft);
    useEffect(() => {
        if(timer > 0) {
            setTimeout(() => setTimer(timer - 1), 1000)
        }},[timer]
    );

    return (
        <div className='nexus-center-xs nexus-pt-5'>
            {timer < 1 ? <button className='nexus-mt-2 nexus-btn nexus-btn-primary' onClick={() => setTimer(20)}>Reset</button> :
            <NexusToast data-testid='toast-with-auto-close' autoClose={timer * 1000}>
                {toastAutoClose.message} {timer}s.
            </NexusToast>}
        </div>
    );
};


export default ToastWithAutoCloseComponent;
