// ui-nexus-design-system/playbook/react/src/components/search/search-examples.tsx
import React, { useState } from 'react';

import { NexusIcon, NexusInput, NexusSearch, NexusSearchList, NexusSearchListItem,NexusTable } from '@nexus/react';

import ActionIcSearch24px from '@nexus/core/dist/assets/icons/action/ic_search_24px.svg';

const SearchExampleComponent: React.FC = () => {
  const items = [{ name: 'Ford' },  { name: 'Porsche' },{ name: 'Tesla' }];

  const [filtereditem, setFiltereditem] = useState(items);
  const Performfilter = (e: any) => {
    const keyword = e.target.value;

    if (keyword !== '') {
      const results = items.filter((item) => item.name.toLowerCase().indexOf(keyword.toLowerCase()) !== -1);
      setFiltereditem(results);
    } else {
      setFiltereditem([...items]);
    }
  };
  const columnDefs = [
    {
      field: 'make',
      label: 'Automobile Make',
      isSortable: true
    },
    {
      field: 'model',
      label: 'Automobile Model',
      isSortable: true
    },
    {
      field: 'year',
      label: 'Manufactured Year',
      isSortable: true
    },
    {
      field: 'owner',
      label: 'Automobile Owner',
      isSortable: false
    },
    {
      field: 'location',
      label: 'Automobile Location'
    },
    {
      field: 'price',
      label: 'Automobile Price',
      isSortable: false,
      cellRenderer: (value: any) => `<i style="color: ${value < 46000 ? 'red' : 'green'}">
      ${
        value < 46000 ? '<nexus-icon size="xs" src="./assets/icons/alert/ic_warning_24px.svg"></nexus-icon>' : ''
      } ${value} </i>`,
      headerClass: 'text-right',
      cellClass: 'text-right'
    }
  ];

  let rowData = [
    {
      make: 'Tesla',
      model: 'Model Y',
      year: '2020',
      owner: 'Iron Man',
      location: 'PA',
      price: 35600
    },
    {
      make: 'Ford',
      model: 'F150',
      year: '2015',
      owner: 'Captain America',
      location: 'LA',
      price: 32600
    },
    {
      make: 'Porsche',
      model: 'Boxster',
      year: '2010',
      owner: 'Captain Marvel',
      location: 'PA',
      price: 72600
    },
    {
      make: 'Tesla',
      model: 'Model Y',
      year: '2015',
      owner: 'Spiderman',
      location: 'NY',
      price: 24600
    },
    {
      make: 'Ford',
      model: 'F150',
      year: '2021',
      owner: 'Black Widow',
      location: 'NY',
      price: 35600
    }
  ];
  let columnData = JSON.parse(JSON.stringify(columnDefs));
  columnData = columnData.map((col: any) => {
    col.isSortable = false;
    return col;
  });
  const [customRowListData, setCustomRowListData] = useState(rowData.slice(0, 5));
  const columnList = Object.keys(rowData[0]);
  const RefreshTable = (e: any) => {
    let rowDataNew =[];
    const newLocal = document.querySelector('input') as HTMLInputElement;
   const selectedItem= newLocal.value;
    if(selectedItem!==null && selectedItem !==undefined && selectedItem!=='')
    {

    rowDataNew =  rowData.filter(function(newValue) {
      return newValue.make === selectedItem;
    }); 
  }
  else
  {
    rowDataNew=rowData;
  }
  rowData=rowDataNew;

    setCustomRowListData(rowData);


}
  return (
    <>
    <NexusSearch >
      <NexusInput data-testid="search-bar" onKeyUp={Performfilter} autocomplete="off" placeholder="Search">
        <NexusIcon data-testid="search-icon" onClick={RefreshTable} src={ActionIcSearch24px}></NexusIcon>
      </NexusInput>
      <NexusSearchList onClick={RefreshTable}>
        <div>
          {filtereditem.length > 0 && (
            <div>
              {filtereditem.map((item) => (
                <NexusSearchListItem data-testid="search-list" key={item.name}>
                  <button>{item.name}</button>
                </NexusSearchListItem>
              ))}
            </div>
          )}
        </div>
      </NexusSearchList>
    </NexusSearch>
    <br />
    <NexusTable
        type="custom"
        id="tblNexus"
        columns={columnData}
        pagination={true}
        pageSize={5}
        totalItems={rowData.length}
      >
              <div slot="tbody">
          {customRowListData.length > 0 &&
            customRowListData.map((element: any, rowidx) => (
              <>
                <tr

                >
                  {Object.values(columnList).map((ele: any, cidx) => (
                    <td>

                      {element[ele]}
                    </td>
                  ))}
                </tr>
              </>
            ))}
        </div>
        </NexusTable>
    </>
  );
};


export default SearchExampleComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/search-examples/search-examples.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-search-examples',
  templateUrl: './search-examples.component.html'
})
export class SearchExamplesComponent implements OnInit {
  @Input() currentPage: number = 1;

  @Input() maxHeight: string = null;

  @Input() pagination: boolean = true;

  @Input() pageSize: string = '5';

  @Input() pageSizeLabel: string = 'Items Per Page';

  @Input() type: string = 'basic';

  columnDefs: any = [
    {
      field: 'make',
      label: 'Make',
      isSortable: false
    },
    {
      field: 'model',
      label: 'Model',
      isSortable: false

    },
    {
      field: 'year',
      label: 'Year',
      isSortable: false

    },
    {
      field: 'owner',
      label: 'Car Owner',
      isSortable: false

    },
    {
      field: 'location',
      label: 'Location',
      isSortable: false

    },
    {
      field: 'price',
      label: 'Sale Price',
      isSortable: false,
      cellRenderer: (value) => `<i style="color: ${value < 55050 ? 'red' : 'green'}">
      ${
  value < 55050 ? '<nexus-icon size="xs" src="./assets/icons/alert/ic_warning_24px.svg"></nexus-icon>' : ''
} ${value} </i>`
    }
  ];

  rowData: any = [
    {
      make: 'Toyota',
      model: 'Outback',
      year: '2020',
      price: 35500,
      owner: 'Iron Man',
      location: 'PA'
    },
    {
      make: 'Tesla',
      model: 'Model 3',
      year: '2022',
      price: 32500,
      owner: 'Captain America',
      location: 'LA'
    },
    {
      make: 'Nissan',
      model: 'Altima',
      year: '2010',
      price: 72500,
      owner: 'Captain Marvel',
      location: 'PA'
    },
    {
      make: 'Toyota',
      model: 'Outback',
      year: '2015',
      price: 24500,
      owner: 'Spiderman',
      location: 'NY'
    },
    {
      make: 'Tesla',
      model: 'Model 3',
      year: '2021',
      price: 35050,
      owner: 'Black Widow',
      location: 'NY'
    }
  ];


  Items: any = [];

  filteredItem: any = [];

  rowDataNew: any = [];

  ngOnInit(): void {
    this.Items.push('Nissan');
    this.Items.push('Tesla');
    this.Items.push('Toyota');
    this.filteredItem = this.Items;
  }

  performFilter(event: any) {
    const filterBy = event.target.value.toLocaleLowerCase();
    this.filteredItem = this.Items.filter((item: any) => item.toLocaleLowerCase().indexOf(filterBy) !== -1);
  }


  refreshTable(event: any) {
    const selectedItem = document.querySelector('input').value;
    if (selectedItem !== null && selectedItem !== '')
    {
      this.rowDataNew = this.rowData.filter((newValue) => newValue.make === selectedItem);
    }
    else
    {
      this.rowDataNew = this.rowData;
    }

    const table = document.getElementById('tblNexus');
    const tBody = table && table.getElementsByTagName('tbody')[0];
    if (tBody) {
      tBody.innerHTML = '';
    }
    const columnList = Object.keys(this.rowDataNew[0]);
    for (const row of this.rowDataNew) {
      const rowCount = tBody.rows.length;
      const tableRow = tBody.insertRow(rowCount);
      columnList.forEach((_key, index, arr) => {
        const cell = tableRow.insertCell(index);

        cell.innerHTML = row[arr[index]];
      });
    }
  }
}

<nexus-search data-testid="search-bar">
    <nexus-input (keyup)="performFilter($event)" autocomplete="off" placeholder="Search">
      <nexus-icon (click)="refreshTable($event)"  data-testid="search-icon" src="./assets/icons/action/ic_search_24px.svg"></nexus-icon>
    </nexus-input>
    <nexus-search-list (click)="refreshTable($event)">
      <nexus-search-list-item  *ngFor="let item of filteredItem">
        <button>{{ item }}</button>
      </nexus-search-list-item>
    </nexus-search-list>
  </nexus-search>
  <br/>
  <nexus-table id="tblNexus"
    [rows]="rowData"
    [columns]="columnDefs"
    [pagination]="pagination"
    [pageSize]="pageSize"
    [pageSizeLabel]="pageSizeLabel"
  >
  </nexus-table>
