// ui-nexus-design-system/playbook/angular/src/app/sb/components/tooltip/01_tooltip.component.ts
import { Component, Input } from '@angular/core';
import { DefaultToolTip } from '../../constants';

@Component({
  selector: 'app-tooltip',
  templateUrl: './01_tooltip.component.html'
})
export default class TooltipComponent {
  @Input() placement: string = DefaultToolTip.placement;

  @Input() allowClick: boolean = DefaultToolTip.allowClick;

  DefaultToolTip = DefaultToolTip;
}

<div class="nexus-center-xs nexus-mt-5">
  <nexus-tooltip [placement]="placement" [allowClick]="allowClick">
    <nexus-tooltip-trigger>
      Get Help
      <nexus-icon [src]="DefaultToolTip.helpIconSrc"></nexus-icon>
      <span class="nexus-visually-hidden">{{DefaultToolTip.tooltipTrigger}}</span>
    </nexus-tooltip-trigger>

    <nexus-tooltip-content>{{DefaultToolTip.tooltipContent}}</nexus-tooltip-content>
  </nexus-tooltip>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/tooltip/01_tooltip.tsx
import React from 'react';
import { DefaultToolTip } from '../../constants';
import PropTypes from 'prop-types';
import { NexusTooltip, NexusTooltipTrigger, NexusIcon, NexusTooltipContent } from '@nexus/react';


const TooltipComponent: React.FC = (props) => {

  return (
    <div className="nexus-center-xs nexus-mt-6">
    <NexusTooltip {...props}>
      <NexusTooltipTrigger> Get help
        <NexusIcon data-testid="tooltip-icon" src={DefaultToolTip.helpIconSrc}></NexusIcon>
        <span data-testid="tooltip-content-main" className="nexus-visually-hidden">
          {DefaultToolTip.tooltipTrigger}
        </span>
      </NexusTooltipTrigger>

      <NexusTooltipContent data-testid="tooltip-content">{DefaultToolTip.tooltipContent}</NexusTooltipContent>
    </NexusTooltip>
    </div>
  );
};

TooltipComponent.propTypes = {
  allowClick: PropTypes.bool,
  placement: PropTypes.string
};

export default TooltipComponent;
