// ui-nexus-design-system/playbook/angular/src/app/sb/components/tooltip/02_position.component.ts
import { Component } from '@angular/core';
import { TooltipPosition } from '../../constants';

@Component({
  selector: 'app-tooltip-position-variant',
  templateUrl: './02_position.component.html'
})
export default class TooltipPositionVariantComponent {
  TooltipPosition = TooltipPosition;
}

<div class="nexus-center-xs nexus-mt-2">
    <div class="nexus-row">
        <div class="nexus-col-xs-2">
            <nexus-tooltip placement="bottom" [allowClick]="TooltipPosition.allowClick">
                <nexus-tooltip-trigger>
                    <button class="nexus-btn nexus-btn-large nexus-btn-link">
                        {{TooltipPosition.bottomText}} <nexus-icon
                        [src]="TooltipPosition.iconSrc"></nexus-icon>
                        <span class="nexus-visually-hidden">{{TooltipPosition.tooltipTriggerContent}}</span>
                    </button>
                </nexus-tooltip-trigger>
                <nexus-tooltip-content>{{TooltipPosition.tooltipContent}}</nexus-tooltip-content>
            </nexus-tooltip>
        </div>

        <div class="nexus-col-xs-2">
            <nexus-tooltip placement="top" [allowClick]="TooltipPosition.allowClick">
                <nexus-tooltip-trigger>
                    <button class="nexus-btn nexus-btn-large nexus-btn-primary">
                        {{TooltipPosition.topText}} <nexus-icon
                        [src]="TooltipPosition.iconSrc"></nexus-icon>
                        <span class="nexus-visually-hidden">{{TooltipPosition.tooltipTriggerContent}}</span>
                    </button>
                </nexus-tooltip-trigger>
                <nexus-tooltip-content>{{TooltipPosition.tooltipContent}}</nexus-tooltip-content>
            </nexus-tooltip>
        </div>
    </div>
    <div class="nexus-mt-2 nexus-mb-2"></div>
    <div class="nexus-row">
        <div class="nexus-col-xs-2">
            <nexus-tooltip placement="left" [allowClick]="TooltipPosition.allowClick">
                <nexus-tooltip-trigger>
                    <button class="nexus-btn nexus-btn-large">
                        {{TooltipPosition.leftText}} <nexus-icon
                        [src]="TooltipPosition.iconSrc"></nexus-icon>
                        <span class="nexus-visually-hidden">{{TooltipPosition.tooltipTriggerContent}}</span>
                    </button>
                </nexus-tooltip-trigger>
                <nexus-tooltip-content>{{TooltipPosition.tooltipContent}}</nexus-tooltip-content>
            </nexus-tooltip>
        </div>

        <div class="nexus-col-xs-2">
            <nexus-tooltip placement="right" [allowClick]="TooltipPosition.allowClick">
                <nexus-tooltip-trigger>
                    <button class="nexus-btn nexus-btn-large nexus-btn-primary">
                        {{TooltipPosition.rightText}} <nexus-icon
                            [src]="TooltipPosition.iconSrc"></nexus-icon>
                        <span class="nexus-visually-hidden">{{TooltipPosition.tooltipTriggerContent}}</span>
                    </button>
                </nexus-tooltip-trigger>
                <nexus-tooltip-content>{{TooltipPosition.tooltipContent}}</nexus-tooltip-content>
            </nexus-tooltip>
        </div>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/tooltip/02_position.tsx
import React from 'react';
import { TooltipPosition } from '../../constants';
import { NexusTooltip, NexusTooltipTrigger, NexusIcon, NexusTooltipContent } from '@nexus/react';


const TooltipPositionComponent: React.FC = () => {

    return (
        <div className="nexus-center-xs nexus-mt-2">
            <div className='nexus-row'>
                <div className='nexus-col-xs-2'>
                    <NexusTooltip placement='bottom'>
                        <NexusTooltipTrigger>
                            <button className='nexus-btn btn nexus-btn-large'>
                                {TooltipPosition.bottomText}
                                <NexusIcon data-testid="tooltip-icon" src={TooltipPosition.iconSrc}></NexusIcon>
                                <span data-testid="tooltip-content-main" className="nexus-visually-hidden">
                                    {TooltipPosition.tooltipTriggerContent}
                                </span>
                            </button>
                        </NexusTooltipTrigger>

                        <NexusTooltipContent data-testid="tooltip-content">{TooltipPosition.tooltipContent}</NexusTooltipContent>
                    </NexusTooltip>
                </div>
                <div className='nexus-col-xs-2'>
                    <NexusTooltip placement='top'>
                        <NexusTooltipTrigger>
                            <button className='nexus-btn btn nexus-btn-large nexus-btn-primary'>
                                {TooltipPosition.topText}
                                <NexusIcon data-testid="tooltip-icon" src={TooltipPosition.iconSrc}></NexusIcon>
                                <span data-testid="tooltip-content-main" className="nexus-visually-hidden">
                                {TooltipPosition.tooltipContent}
                                </span>
                            </button>
                        </NexusTooltipTrigger>

                        <NexusTooltipContent data-testid="tooltip-content">{TooltipPosition.tooltipContent}</NexusTooltipContent>
                    </NexusTooltip>
                </div>
            </div>

            <div className="nexus-mt-2 nexus-mb-2"></div>

            <div className='nexus-row'>
                <div className='nexus-col-xs-2'>
                    <NexusTooltip placement='left'>
                        <NexusTooltipTrigger>
                            <button className='nexus-btn btn nexus-btn-large'>
                                {TooltipPosition.leftText}
                                <NexusIcon data-testid="tooltip-icon" src={TooltipPosition.iconSrc}></NexusIcon>
                                <span data-testid="tooltip-content-main" className="nexus-visually-hidden">
                                    {TooltipPosition.tooltipTriggerContent}
                                </span>
                            </button>
                        </NexusTooltipTrigger>

                        <NexusTooltipContent data-testid="tooltip-content">{TooltipPosition.tooltipContent}</NexusTooltipContent>
                    </NexusTooltip>
                </div>
                <div className='nexus-col-xs-2'>
                    <NexusTooltip placement='right'>
                        <NexusTooltipTrigger>
                            <button className='nexus-btn nexus-btn-large nexus-btn-primary'>
                                {TooltipPosition.rightText}
                                <NexusIcon data-testid="tooltip-icon" src={TooltipPosition.iconSrc}></NexusIcon>
                                <span data-testid="tooltip-content-main" className="nexus-visually-hidden">
                                    {TooltipPosition.tooltipTriggerContent}
                                </span>
                            </button>
                        </NexusTooltipTrigger>

                        <NexusTooltipContent data-testid="tooltip-content">{TooltipPosition.tooltipContent}</NexusTooltipContent>
                    </NexusTooltip>
                </div>
            </div>
        </div>
    );
};


export default TooltipPositionComponent;
