// ui-nexus-design-system/playbook/angular/src/app/components/progress-bar/progress-bar.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-progress-bar',
  templateUrl: './progress-bar.component.html',
  styleUrls: ['./progress-bar.component.scss']
})
export class ProgressBarComponent {
  @Input() value: number;

  @Input() indeterminate: boolean = false;

  @Input() error: boolean = false;

  @Input() circle: boolean = false;
}

<nexus-progress-bar [value]="value" [indeterminate]="indeterminate" [error]="error" [circle]="circle">
</nexus-progress-bar>

// ui-nexus-design-system/playbook/react/src/components/progress-bar/progress-bar.tsx
import React from 'react';

import { NexusProgressBar } from '@nexus/react';

interface ProgressBarComponentProps {
  circle: boolean;
  error: boolean;
  indeterminate: boolean;
  value: number;
}

const ProgressBarComponent: React.FC<ProgressBarComponentProps> = (props) => {
  const { circle, error, indeterminate, value } = { ...props };

  return (
    <NexusProgressBar circle={circle} error={error} indeterminate={indeterminate} value={value}></NexusProgressBar>
  );
};

ProgressBarComponent.defaultProps = {
  circle: false,
  error: false,
  indeterminate: false,
  value: 50
};

export default ProgressBarComponent;
