// ui-nexus-design-system/playbook/angular/src/app/components/chip-examples/chip-examples.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-chip-examples',
  templateUrl: './chip-examples.component.html',
  styleUrls: ['./chip-examples.component.scss']
})
export class ChipExamplesComponent {
  triggerRemovableClickCall = () => {};
}

<p class="nexus-h5">Disabled</p>
<nexus-chip data-testid="chipDsabl" disabled="true">Chip text</nexus-chip>

<p class="nexus-h5">Removable</p>
<nexus-chip data-testid="chipRemvbl" removable="true" (triggerRemovableClick)="triggerRemovableClickCall()">Chip text</nexus-chip>

<p class="nexus-h5">Success</p>
<nexus-chip data-testid="chipSuccess" success="true">Chip text</nexus-chip>

<p class="nexus-h5">Chip Group</p>
<p>Chips should normally be placed inside of the ChipGroup component. This wrapper provides styling so that the Chips will display inline with one another.</p>

<nexus-chip-group><nexus-chip data-testid="chipGroup1">Chip 1</nexus-chip><nexus-chip data-testid="chipGroup2">Chip 2</nexus-chip><nexus-chip data-testid="chipGroup3">Chip 3</nexus-chip></nexus-chip-group>

<p class="nexus-h5">Dark Theme</p>
<div class="nexus-theme-dark" style="padding: 1em">
  <nexus-chip data-testid="chipDT" removable="true">Chip text</nexus-chip>
</div>

// ui-nexus-design-system/playbook/react/src/components/chip/chip-examples.tsx
import React from 'react';

import { NexusChip, NexusChipGroup } from '@nexus/react';

const ChipExampleComponent: React.FC = () => {
  const onTriggerRemovableClickCall = () => {
    // Do something
  };

  return (
    <>
      <p className="nexus-h5">Disabled</p>
      <NexusChip
        data-testid="chip-disabled"
        disabled={true}>Chip text
      </NexusChip>

      <p className="nexus-h5">Removable</p>
      <NexusChip
        data-testid="chip-removable"
        removable={true} onTriggerRemovableClick={() => { onTriggerRemovableClickCall() }}>Chip text
      </NexusChip>

      <p className="nexus-h5">Success</p>
      <NexusChip
        data-testid="chip-success"
        success={true}>Chip text
      </NexusChip>

      <p className="nexus-h5">Chip Group</p>
      <p>Chips should normally be placed inside of the ChipGroup component. This wrChipExampleComponenter provides styling so that the Chips will display inline with one another.</p>

      <NexusChipGroup>
        <NexusChip
          data-testid="chip-group-1"
        >
          Chip 1
        </NexusChip>
        <NexusChip
          data-testid="chip-group-2"
        >
          Chip 2
        </NexusChip>
        <NexusChip
          data-testid="chip-group-3"
        >
          Chip 3
        </NexusChip>
      </NexusChipGroup>

      <p className="nexus-h5">Dark Theme</p>
      <div className="nexus-theme-dark" style={{ padding: '1em' }}>
        <NexusChip
          data-testid="chip-theme-dark-removable"
          removable={true}>Chip text</NexusChip>
      </div>
    </>
  )
};
export default ChipExampleComponent;
