// ui-nexus-design-system/playbook/angular/src/app/components/chip/chip.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-chip',
  templateUrl: './chip.component.html',
  styleUrls: ['./chip.component.scss']
})
export class ChipComponent {
  @Input() disabled: boolean = false;

  @Input() removable: boolean = false;

  @Input() success: boolean = false;

  @Input() error: boolean = false;

  @Input() text: string = 'Chip Text';
}

<nexus-chip data-testid="chipChip" [disabled]="disabled" [removable]="removable" [error]="error" [success]="success">
  {{ text }}
</nexus-chip>

// ui-nexus-design-system/playbook/react/src/components/chip/chip.tsx
import React from 'react';
import { NexusChip } from '@nexus/react';
import Note from '../notecontainer/note';

interface ChipComponentProps {
  disabled: boolean;
  error: boolean;
  removable: boolean;
  success: boolean;
  text: string;
}

const ChipComponent: React.FC<ChipComponentProps> = (props) => {
  const { disabled, error, removable, success, text } = { ...props };

  return (
    <>
      <NexusChip disabled={disabled} error={error} removable={removable} success={success}>
        {text}
      </NexusChip>
      <Note noteType="onNote" />
    </>
  );
};

ChipComponent.defaultProps = {
  disabled: false,
  error: false,
  removable: false,
  success: false,
  text: 'Chip Text'
};

export default ChipComponent;
