// ui-nexus-design-system/playbook/react/src/sb/components/dropdown/01_dropdown.tsx
import React from 'react';
import PropTypes from 'prop-types';
import { NexusDropdown, NexusIcon, NexusOption } from '@nexus/react';
import NavigationIcMoreVert24px from '@nexus/core/dist/assets/icons/navigation/ic_more_vert_24px.svg';

const DropdownComponent: React.FC = (props) => {
  const { placement = 'left', type = 'basic', height = 150, width = 180, show = false } = { ...props };
  return (
    <>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint Lorem ipsum dolor sit amet
        <NexusDropdown placement={placement} dropdown-type={type} height={height} width={width} show={show}>
          <NexusIcon slot={'trigerer'} id={'iconId'} src={NavigationIcMoreVert24px}></NexusIcon>
          <NexusOption>Option 1</NexusOption>
          <NexusOption>Option 2</NexusOption>
          <NexusOption>Option 3</NexusOption>
        </NexusDropdown>
      </p>
    </>
  );
};

DropdownComponent.propTypes = {
  show: PropTypes.bool,
  placement: PropTypes.string,
  height: PropTypes.number,
  width: PropTypes.number,
  type: PropTypes.string
};

export default DropdownComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/dropdown/01_dropdown.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-dropdown',
  templateUrl: './01_dropdown.component.html'
})
export default class DropdownComponent {
  @Input() show: boolean;

  @Input() placement: string;

  @Input() dropdownType: string;

  @Input() height: number;

  @Input() width: number;
}

<p>
  Lorem ipsum dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint Lorem ipsum dolor sit
  amet<nexus-dropdown
    [dropdown-type]="dropdownType"
    [placement]="placement"
    [height]="height"
    [width]="width"
    [show]="show"
  >
    <nexus-icon slot="trigerer" id="iconId" src="./assets/icons/navigation/ic_more_vert_24px.svg"></nexus-icon>
    <nexus-option label="Option 1" value="Option1">Option 1</nexus-option>
    <nexus-option label="Option 2" value="Option2">Option 2</nexus-option>
    <nexus-option label="Option 3" value="Option3">Option 3</nexus-option>
  </nexus-dropdown>
</p>
