// ui-nexus-design-system/playbook/angular/src/app/sb/components/chip/01_chip.component.ts
import { Component, Input } from '@angular/core';
import { chip as defaultChip } from '../../constants';

@Component({
  selector: 'app-chip',
  templateUrl: './01_chip.component.html'
})
export default class ChipComponent {
  @Input() disabled: boolean = false;

  @Input() removable: boolean = false;

  @Input() success: boolean = false;

  @Input() error: boolean = false;

  @Input() text: string = defaultChip.text;
}

<div class="nexus-center-xs nexus-mt-5">
    <div class="nexus-row nexus-around-xs">
    <nexus-chip data-testid="chipChip" [disabled]="disabled" [removable]="removable" [error]="error"
        [success]="success"> {{ text }} </nexus-chip>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/chip/01_chip.tsx
import React from 'react';
import { chip } from '../../constants';
import { NexusChip } from '@nexus/react';
import PropTypes from 'prop-types';


const ChipComponent: React.FC = (props) => {
  const { disabled = false, error = false, removable = false, success = false, text = chip.text } = { ...props };
  return (
    <div className="nexus-center-xs nexus-mt-5">
      <div className="nexus-row nexus-around-xs">
        <NexusChip
          disabled={disabled}
          error={error}
          removable={removable}
          success={success}>{text}</NexusChip>
      </div>
    </div>
  );
};

ChipComponent.propTypes = {
  disabled: PropTypes.bool,
  error: PropTypes.bool,
  removable: PropTypes.bool,
  success: PropTypes.bool,
  text: PropTypes.string
};

export default ChipComponent;
