// ui-nexus-design-system/playbook/angular/src/app/sb/components/radio/02_group.component.ts
import { Component, Input } from '@angular/core';
import { radio, group } from '../../constants';

@Component({
  selector: 'app-group',
  templateUrl: './02_group.component.html'
})
export default class GroupComponent {
  @Input() name = radio.name;

  @Input() disabled: boolean = false;

  group = group;
}

<div class="nexus-col-xs ">
    <nexus-label>{{group.label}}</nexus-label>

    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="disabled">
            {{group.first}}
        </nexus-radio>
    </div>
    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="disabled">
            {{group.second}}
        </nexus-radio>
    </div>
    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="disabled">
            {{group.third}}
        </nexus-radio>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/chip/02_group.tsx
import React from 'react';
import { chipGroup } from '../../constants';
import { NexusChip, NexusChipGroup } from '@nexus/react';

const ChipGroupComponent: React.FC = () => (
    <div className="nexus-center-xs nexus-mt-5">
        <div className="nexus-row nexus-around-xs">
            <NexusChipGroup>
                <NexusChip data-testid="chip-group-1">{chipGroup.first}</NexusChip>
                <NexusChip data-testid="chip-group-2">{chipGroup.second}</NexusChip>
                <NexusChip data-testid="chip-group-3">{chipGroup.third}</NexusChip>
            </NexusChipGroup>
        </div>
    </div>
);

export default ChipGroupComponent;
