// ui-nexus-design-system/playbook/angular/src/app/sb/components/chip/04_removable.component.ts
import { Component } from '@angular/core';
import { removable } from '../../constants';

@Component({
  selector: 'app-chip-removable',
  templateUrl: './04_removable.component.html'
})
export default class RemovableChipComponent {
  show = true;

  data = removable;

  triggerRemovableClickCall = (event) => {
    this.show = false;
  };

  triggerCheckBoxSelection = (event) => {
    this.show = event.target.checked;
  };
}

<div class="nexus-center-xs nexus-mt-5">
    <div class="nexus-row">
        <div class="nexus-col-xs-2 nexus-pl-5">
            <nexus-checkbox (click)="triggerCheckBoxSelection($event)" [checked]="show">{{data.text}}</nexus-checkbox>
        </div>
        <ng-container *ngIf="show">
            <div class="nexus-col-xs-2 nexus-pl-5">
                <nexus-chip data-testid="Item-1" id="Item-1" removable="true"
                    (triggerRemovableClick)="triggerRemovableClickCall($event)">{{data.checkboxText}}</nexus-chip>
            </div>
        </ng-container>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/chip/04_removable.tsx
import React, { useState } from 'react';
import { removable } from '../../constants';
import { NexusCheckbox, NexusChip } from '@nexus/react';


const RemovableChipComponent: React.FC = () => {
    const [show, setShow] = useState(true);

    const triggerCloseEvent = () => {
        setShow(false);
    }

    const checkBoxSelection = (event: any) => {
        setShow(event.target.checked === true);
    }

    return (<div className="nexus-center-xs nexus-mt-5">
        <div className="nexus-row">
            <div className='nexus-col-xs-2 nexus-pl-5'>
                <NexusCheckbox checked={show} onClick={(event) => checkBoxSelection(event)}>{removable.checkboxText}</NexusCheckbox>
            </div>
            {show ? <div className='nexus-col-xs-2' >
                <NexusChip
                    id="Item-1"
                    data-testid="Item-1"
                    removable
                    onTriggerRemovableClick={() => triggerCloseEvent()}>{removable.text}</NexusChip>
            </div>: ''}
        </div>
    </div>);
};

export default RemovableChipComponent;
