// ui-nexus-design-system/playbook/angular/src/app/sb/components/chip/05_darkTheme.component.ts
import { Component } from '@angular/core';
import { chipDarkTheme } from '../../constants';

@Component({
  selector: 'app-chip-dark-theme',
  templateUrl: './05_darkTheme.component.html'
})
export default class ChipOnDarkThemeComponent {
  darkTheme = chipDarkTheme;
}

<div class="nexus-theme-dark" style="padding: 1em">
    <nexus-chip data-testid="chipDT" removable="true">{{darkTheme.text}}</nexus-chip>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/chip/05_darkTheme.tsx
import React from 'react';
import { chipDarkTheme } from '../../constants';
import { NexusChip } from '@nexus/react';

const ChipOnDarkThemeComponent: React.FC = () => {
    return (
        <div className="nexus-theme-dark" style={{ padding: '1em' }}>
            <NexusChip
                data-testid="chip-theme-dark-removable"
                removable={true}>{chipDarkTheme.text}</NexusChip>
        </div>
    )
};
export default ChipOnDarkThemeComponent;
