// ui-nexus-design-system/playbook/react/src/sb/components/pin-entry/02_pinEntryDisabled.tsx
import React from 'react';
import { NexusPinEntry } from '@nexus/react';


const PinEntryDisabledComponent: React.FC = () => (
    <div className='nexus-center-xs nexus-mt-5'>
        <NexusPinEntry length={4} disabled type='tel' data-testid="pin-entry"></NexusPinEntry>
    </div>
);


export default PinEntryDisabledComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/pin-entry/02_pinEntryDisabled.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-pin-entry-disabled',
  templateUrl: './02_pinEntryDisabled.component.html'
})
export default class PinEntryDisabledComponent {
}

<div class="nexus-center-xs nexus-mt-5">
    <nexus-pin-entry data-testid="pin-entry-disabled" length=4 disabled type="number">
    </nexus-pin-entry>
</div>
