// ui-nexus-design-system/playbook/react/src/sb/components/accordion/01_accordion.tsx
import React, { useState } from 'react';
import { accordion } from '../../constants';
import { NexusAccordion, NexusAccordionTrigger, NexusAccordionContent } from '@nexus/react';
import PropTypes from 'prop-types';
import { propSize } from '@nexus/core/dist/types/components/nexus-accordion/nexus-accordion';

export const AccordionComponent: React.FC = (props) => {
  const { open = accordion.open, size = accordion.size as propSize, align = 'start' } = { ...props };
  const [openAcccordion, setAccordionOpen] = useState(open);

  return (
    <NexusAccordion open={openAcccordion} onToggleEvent={() => setAccordionOpen(!openAcccordion)} size={size}>
      <NexusAccordionTrigger align={align}>
        <h1 className="nexus-body">{accordion.title}</h1>
      </NexusAccordionTrigger>
      <NexusAccordionContent>{accordion.description}</NexusAccordionContent>
    </NexusAccordion>
  );
};

AccordionComponent.propTypes = {
  open: PropTypes.bool,
  size: PropTypes.string
};

AccordionComponent.defaultProps = {
  open: false,
  size: 'md',
  align: 'start'
};

export default AccordionComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/accordion/01_accordion.component.ts
import { Component, Input } from '@angular/core';
import { accordion } from '../../constants';

@Component({
  selector: 'app-accordion',
  templateUrl: './01_accordion.component.html'
})
export default class AccordionComponent {
  @Input() align: string = accordion.align;

  @Input() open: boolean = accordion.open;

  @Input() size: string = accordion.size;

  accordion = accordion;
}

<nexus-accordion [open]="open" (toggleEvent)="open = !open" [size]="size" [align]="align">
  <nexus-accordion-trigger [align]="align">
    <h1 class="nexus-body">{{accordion.title}}</h1>
  </nexus-accordion-trigger>
  <nexus-accordion-content>
    {{accordion.description}}
  </nexus-accordion-content>
</nexus-accordion>
