// ui-nexus-design-system/playbook/react/src/sb/components/button/02_size.tsx
import React from 'react';
import { buttonSizeVariant } from '../../constants';


const SizeComponent: React.FC = () => {
    return (
        <div className="nexus-center-xs nexus-mt-2">
            <button data-testid="nexus-button-medium" className="nexus-btn nexus-btn-medium">{buttonSizeVariant.medium}</button>
            <div className="nexus-mt-2 nexus-mb-2"></div>

            <button data-testid="nexus-button-medium" className="nexus-btn nexus-btn-primary nexus-btn-large">{buttonSizeVariant.large}</button>
            <div className="nexus-mt-2 nexus-mb-2"></div>

            <div className="nexus-row nexus-around-xs">
                <div className="nexus-col-xs-3">
                    <button data-testid="nexus-button-primary" className="nexus-btn nexus-btn-fluid nexus-around-xs">{buttonSizeVariant.fluid}</button>
                </div>
            </div>
        </div>
    );
};

export default SizeComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/button/02_size.component.ts
import { Component } from '@angular/core';
import { buttonSizeVariant } from '../../constants';

@Component({
  selector: 'app-button-size-variants',
  templateUrl: './02_size.component.html'
})
export default class SizeComponent {
  buttonSizeVariant = buttonSizeVariant;
}

<div class="nexus-center-xs nexus-mt-2">
    <button data-testid="nexus-button-medium" class="nexus-btn nexus-btn-medium">{{buttonSizeVariant.medium}}</button>
    <div class="nexus-mt-2 nexus-mb-2"></div>

    <button data-testid="nexus-button-medium" class="nexus-btn nexus-btn-primary nexus-btn-large">{{buttonSizeVariant.large}}</button>
    <div class="nexus-mt-2 nexus-mb-2"></div>

    <div class="nexus-row nexus-around-xs">
        <div class="nexus-col-xs-3">
            <button data-testid="nexus-button-primary" class="nexus-btn nexus-btn-fluid nexus-around-xs">{{buttonSizeVariant.fluid}}</button>
        </div>
    </div>
</div>
