// ui-nexus-design-system/playbook/react/src/sb/components/button/04_darkTheme.tsx
import React from 'react';
import { darkTheme } from '../../constants';
import { Link } from 'react-router-dom';

const DarkThemeComponent: React.FC = () => {
  return (
    <div className="nexus-row nexus-center-xs">
      <div className="nexus-col-xs-4 nexus-col-md-8">
        <div className="nexus-theme-dark nexus-pt-2 nexus-pb-2">
          <div className="nexus-row nexus-center-xs">
            <div className="nexus-col-xs-4 nexus-col-md-2 nexus-mt-2">
              <button data-testid="button-theme-dark-default" className="nexus-btn nexus-ml-1">
                {darkTheme.default}
              </button>
            </div>
            <div className="nexus-col-xs-4 nexus-col-md-2 nexus-mt-2">
              <button
                data-testid="button-theme-dark-primary"
                className="nexus-btn nexus-btn-primary nexus-ml-1 nexus-mr-1"
              >
                {darkTheme.primary}
              </button>
            </div>
            <div className="nexus-col-xs-4 nexus-col-md-2 nexus-mt-2">
              <button
                data-testid="button-theme-dark-primary"
                className="nexus-btn nexus-btn-warn nexus-ml-1 nexus-mr-1"
              >
                {darkTheme.warn}
              </button>
            </div>
            <div className="nexus-col-xs-4 nexus-col-md-2 nexus-mt-3">
              <a
                href="./?path=/docs/component-buttons-and-indicators-button--d-dark-theme"
                data-testid="theme-dark-nexus-link"
                className="nexus-link nexus-ml-1 nexus-mr-2"
              >
                {darkTheme.link}
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DarkThemeComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/button/04_darkTheme.component.ts
import { Component } from '@angular/core';
import { darkTheme } from '../../constants';

@Component({
  selector: 'app-button-dark-theme',
  templateUrl: './04_darkTheme.component.html'
})
export default class DarkThemeComponent {
  darkTheme = darkTheme;
}

<div class="nexus-row nexus-center-xs">
  <div class="nexus-col-xs-4 nexus-col-md-8">
    <div class="nexus-theme-dark nexus-pt-2 nexus-pb-2">
      <div class="nexus-row nexus-center-xs">
        <div class="nexus-col-xs-4 nexus-col-md-2 nexus-mt-2">
          <button data-testid="button-theme-dark-default" class="nexus-btn">{{ darkTheme.default }}</button>
        </div>
        <div class="nexus-col-xs-4 nexus-col-md-2 nexus-mt-2">
          <button data-testid="button-theme-dark-primary" class="nexus-btn nexus-btn-primary nexus-ml-2 nexus-mr-2">
            {{ darkTheme.primary }}
          </button>
        </div>
        <div class="nexus-col-xs-4 nexus-col-md-2 nexus-mt-2">
          <button data-testid="button-theme-dark-primary" class="nexus-btn nexus-btn-warn nexus-ml-2 nexus-mr-2">
            {{ darkTheme.warn }}
          </button>
        </div>
        <div class="nexus-col-xs-4 nexus-col-md-2 nexus-mt-3">
          <a href="./?path=/docs/component-buttons-and-indicators-button--d-dark-theme"
            data-testid="theme-dark-nexus-link"
            class="nexus-link nexus-ml-2 nexus-mr-2"
            >{{ darkTheme.link }}
            </a>
        </div>
      </div>
    </div>
  </div>
</div>
