// ui-nexus-design-system/playbook/react/src/sb/components/button/06_floatingButton.tsx
import { NexusIcon } from '@nexus/react';
import React from 'react';
import { floatingButton } from '../../constants';


const FloatingButtonComponent: React.FC = () => {
    return (
        <div className="nexus-mt-5">
            <div className="nexus-row nexus-center-xs">
                <div className="nexus-col-xs-4 nexus-col-md-4">
                    <div className="nexus-row nexus-center-xs">
                        <div className="nexus-col-xs-2  nexus-col-md-4">
                            <button data-testid="nexus-button-with-icon" className="nexus-btn-icon">
                                <NexusIcon src="./assets/icons/action/ic_settings_24px.svg"></NexusIcon>
                                <span className="nexus-visually-hidden">Settings</span>
                            </button>
                        </div>
                        <div className="nexus-col-xs-2">
                            <h5 className="nexus-h5">{floatingButton.icon}</h5>
                        </div>
                    </div>

                </div>
                <div className="nexus-col-xs-4 nexus-col-md-4">
                    <div className="nexus-row nexus-center-xs">
                        <div className="nexus-col-xs-2 nexus-col-md-4">
                            <button data-testid="nexus-btn-floating" className="nexus-fab">
                                <NexusIcon src="./assets/icons/action/ic_settings_24px.svg"></NexusIcon>
                                <span className="nexus-visually-hidden">Settings</span>
                            </button>
                        </div>
                        <div className="nexus-col-xs-2 nexus-col-md-4">
                            <h5 className="nexus-h5">{floatingButton.floatingIconButton}</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default FloatingButtonComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/button/06_floatingButton.component.ts
import { Component } from '@angular/core';
import { floatingButton } from '../../constants';

@Component({
  selector: 'app-button-floating-button',
  templateUrl: './06_floatingButton.component.html'
})
export default class FloatingButtonComponent {
  floatingButtons = floatingButton;
}

<div class="nexus-mt-5">
    <div class="nexus-row nexus-center-xs">
        <div class="nexus-col-xs-4 nexus-col-md-4">
            <div class="nexus-row nexus-center-xs">
                <div class="nexus-col-xs-2  nexus-col-md-4">
                    <button data-testid="nexus-button-with-icon" class="nexus-btn-icon">
                        <nexus-icon src="./assets/icons/action/ic_settings_24px.svg"></nexus-icon>
                        <span class="nexus-visually-hidden">Settings</span>
                    </button>
                </div>
                <div class="nexus-col-xs-2">
                    <h5 class="nexus-h5">{{floatingButtons.icon}}</h5>
                </div>
            </div>

        </div>
        <div class="nexus-col-xs-4 nexus-col-md-4">
            <div class="nexus-row nexus-center-xs">
                <div class="nexus-col-xs-2 nexus-col-md-4">
                    <button data-testid="nexus-btn-floating" class="nexus-fab">
                        <nexus-icon src="./assets/icons/action/ic_settings_24px.svg"></nexus-icon>
                        <span class="nexus-visually-hidden">Settings</span>
                    </button>
                </div>
                <div class="nexus-col-xs-2 nexus-col-md-4">
                    <h5 class="nexus-h5">{{floatingButtons.floatingIconButton}}</h5>
                </div>
            </div>
        </div>
    </div>
</div>
