// ui-nexus-design-system/playbook/react/src/sb/components/button/07_tabbed.tsx
import React from "react";
import { tabbed } from "../../constants";
import { NexusIcon } from "@nexus/react";

const TabbedComponent: React.FC = () => (
    <div className="nexus-row nexus-body">
        <div className="nexus-col-xs-4">
            <div className="nexus-center-xs nexus-mt-3">
                <button className="nexus-btn nexus-btn-medium nexus-btn-primary nexus-overline">
                    <NexusIcon src={tabbed.micIconSrc} size="md"></NexusIcon>
                    {tabbed.on}
                </button>
                <button className="nexus-btn nexus-btn-medium nexus-overline">
                    <NexusIcon src={tabbed.micOffIconSrc} size="md"></NexusIcon>
                    {tabbed.off}
                </button>
            </div>
        </div>
        <div className="nexus-col-xs-4">
            <div className="nexus-center-xs nexus-mt-2">
                <button
                    className="nexus-btn nexus-btn-medium nexus-overline"
                    style={{ backgroundColor: tabbed.successColor, color: tabbed.textColor, border: `1px solid ${tabbed.successColor}` }}
                >
                    <NexusIcon src={tabbed.showIconSrc} size="md"></NexusIcon>
                    {tabbed.show}
                </button>
                <button className="nexus-btn nexus-btn-medium nexus-btn-warn nexus-overline">
                    <NexusIcon src={tabbed.hideIconSrc} size="md"></NexusIcon>
                    {tabbed.hide}
                </button>
            </div>
        </div>
    </div>
)

export default TabbedComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/button/07_tabbed.component.ts
import { Component } from '@angular/core';
import { tabbed } from '../../constants';

@Component({
  selector: 'app-button-tabbed',
  templateUrl: './07_tabbed.component.html',
  styles: [
    `.btn-success {
      background-color: ${tabbed.successColor};
      color: ${tabbed.textColor};
      border: 1px solid ${tabbed.successColor};
    }`
  ]
})
export default class TabbedButtonComponent {
  tabbedInfo = tabbed;
}

<div class="nexus-row nexus-body">
    <div class="nexus-col-xs-4">
        <div class="nexus-center-xs nexus-mt-3">
            <button class="nexus-btn nexus-btn-medium nexus-btn-primary nexus-overline">
                <nexus-icon [src]="tabbedInfo.micIconSrc" size="md"></nexus-icon>
                {{tabbedInfo.on}}
            </button>
            <button class="nexus-btn nexus-btn-medium nexus-overline">
                <nexus-icon [src]="tabbedInfo.micOffIconSrc" size="md"></nexus-icon>
                {{tabbedInfo.off}}
            </button>
        </div>
    </div>
    <div class="nexus-col-xs-4">
        <div class="nexus-center-xs nexus-mt-2">
            <button class="nexus-btn nexus-btn-medium nexus-overline btn-success">
                <nexus-icon [src]="tabbedInfo.showIconSrc" size="md"></nexus-icon>
                {{tabbedInfo.show}}
            </button>
            <button class="nexus-btn nexus-btn-medium nexus-btn-warn nexus-overline">
                <nexus-icon [src]="tabbedInfo.hideIconSrc" size="md"></nexus-icon>
                {{tabbedInfo.hide}}
            </button>
        </div>
    </div>
</div>
