// ui-nexus-design-system/playbook/angular/src/app/components/pie-chart/pie-chart.component.ts
/* eslint-disable max-lines */
/* eslint-disable id-length */

import { Component, OnInit, ElementRef } from '@angular/core';

@Component({
  selector: 'app-pie-chart',
  templateUrl: './pie-chart.component.html',
  styleUrls: ['./pie-chart.component.scss']
})
export class PieChartComponent implements OnInit {
  public chartData: Array<any> = [
    { artist: 'The Beatles',
      units: 183 },
    { artist: 'Garth Brooks',
      units: 148 },
    { artist: 'Elvis Presley',
      units: 146.5 },
    { artist: 'The Eagles',
      units: 120 },
    { artist: 'Led Zeppelin',
      units: 111.5 },
    { artist: 'Billy Joel',
      units: 84.5 },
    { artist: 'Michael Jackson',
      units: 84 },
    { artist: 'Elton John',
      units: 78.5 },
    { artist: 'Pink Floyd',
      units: 75 },
    { artist: 'AC/DC',
      units: 72 },
    { artist: 'George Strait',
      units: 69 },
    { artist: 'Barbara Streisand',
      units: 68.5 },
    { artist: 'The Rolling Stones',
      units: 66.5 },
    { artist: 'Aerosmith',
      units: 66.5 },
    { artist: 'Bruce Springsteen',
      units: 65.5 }
  ];

  private gridlines = false;

  private inverse = false;

  private showLegend = false;

  private showPieLegend = true;

  private vertices = true;

  private htmlElement: HTMLElement;

  constructor(public elRef: ElementRef) {
    this.htmlElement = this.elRef.nativeElement;

    this.gridlines = false;
    this.inverse = false;
    this.showLegend = false;
    this.showPieLegend = true;
    this.vertices = true;
  }

  public changeXLabel(args: any, value: any): any {
    this.getChartEl(args).xLabel = value;
    const xLabelInput = this.htmlElement.querySelector('#xLabelInput') as HTMLInputElement;
    xLabelInput.value = '';
  }

  public changeYLabel(args: any, value: any): any {
    this.getChartEl(args).yLabel = value;
    const yLabelInput = this.htmlElement.querySelector('#yLabelInput') as HTMLInputElement;
    yLabelInput.value = '';
  }

  public getChartEl(id: string): any {
    return document.querySelector(id);
  }

  public randomizer(): any {
    return Math.floor(Math.random() * 500) - 250;
  }

  public selectArcStroke(args: string): any {
    const arcStroke = this.htmlElement.querySelector('#arcStroke') as HTMLInputElement;
    this.getChartEl(args).stroke = arcStroke.value;
  }

  public selectAxisLabelFontSize(args: string): void {
    const axisLabelFontSize = this.htmlElement.querySelector('#axisLabelFontSize') as HTMLInputElement;
    this.getChartEl(args).axisLabelFontSize = axisLabelFontSize.value;
  }

  public selectAxisTickFontSize(args: string): void {
    const axisTickFontSize = this.htmlElement.querySelector('#axisTickFontSize') as HTMLInputElement;
    this.getChartEl(args).axisTickFontSize = axisTickFontSize.value;
  }

  public selectAxisTickFontFamily(args: string): void {
    const axisTickFontFamily = this.htmlElement.querySelector('#axisTickFontFamily') as HTMLInputElement;
    this.getChartEl(args).axisTickFontFamily = axisTickFontFamily.value;
  }

  public selectBarStroke(args: string): void {
    const barStroke = this.htmlElement.querySelector('#barStroke') as HTMLInputElement;
    this.getChartEl(args).barStroke = barStroke.value;
  }

  public selectBarStrokeWidth(args: string): void {
    const barStrokeWidth = this.htmlElement.querySelector('#barStrokeWidth') as HTMLInputElement;
    this.getChartEl(args).barStrokeWidth = barStrokeWidth.value;
  }

  public selectColorScheme(args: string): void {
    const colorScheme = this.htmlElement.querySelector('#colorScheme') as HTMLInputElement;
    this.getChartEl(args).colorScheme = colorScheme.value;
  }

  public selectInnerRadius(args: string): void {
    const innerRadius = this.htmlElement.querySelector('#innerRadius') as HTMLInputElement;
    this.getChartEl(args).innerRadius = innerRadius.value;
  }

  public selectInterpolation(args: string): void {
    const interpolation = this.htmlElement.querySelector('#interpolation') as HTMLInputElement;
    this.getChartEl(args).interpolation = interpolation.value;
  }

  public selectLegendFontSize(args: string): void {
    const legendFontSize = this.htmlElement.querySelector('#legendFontSize') as HTMLInputElement;
    this.getChartEl(args).legendFontSize = legendFontSize.value;
  }

  public selectLinearDomain(args: string): void {
    const val = this.htmlElement.querySelector('#linearDomain') as HTMLInputElement;
    const el = this.getChartEl(args);
    if (val.value === 'percent') {
      el.linearTickFormat = 'percent1d';
    } else {
      el.linearTickFormat = 'localestring';
    }
    this.getChartEl(args).linearDomain = val.value;
  }

  public selectLineStroke(args: string): void {
    const val = this.htmlElement.querySelector('#lineStroke') as HTMLInputElement;
    this.getChartEl(args).strokeWidth = val.value;
  }

  public selectMargin(marginAttribute: string, args: any): any {
    const val = this.htmlElement.querySelector(`#${marginAttribute}`) as HTMLInputElement;
    const el = this.getChartEl(args);
    el[marginAttribute] = val.value;
  }

  public selectMaxBarWidth(args: string): void {
    const val = this.htmlElement.querySelector('#maxBarWidth') as HTMLInputElement;
    this.getChartEl(args).maxBarWidth = val.value;
  }

  public selectXTickSize(args: string): void {
    const val = this.htmlElement.querySelector('#xTickSize') as HTMLInputElement;
    this.getChartEl(args).xTickSize = val.value;
  }

  public selectYTickSize(args: string): void {
    const val = this.htmlElement.querySelector('#yTickSize') as HTMLInputElement;
    this.getChartEl(args).yTickSize = val.value;
  }

  public toggleGridlines(args: string): void {
    this.gridlines = !this.gridlines;
    this.getChartEl(args).gridlines = this.gridlines;
  }

  public toggleInverse(args: string): void {
    this.inverse = !this.inverse;
    this.getChartEl(args).inverse = this.inverse;

    if (this.inverse) {
      this.htmlElement.querySelector('div.chart').classList.add('inverse');
    } else {
      this.htmlElement.querySelector('div.chart').classList.remove('inverse');
    }
  }

  public toggleLegend(args: string): void {
    if (args === 'nexus-pie-chart') {
      this.showPieLegend = !this.showPieLegend;
      this.getChartEl(args).legend = this.showPieLegend;

      return;
    }

    this.showLegend = !this.showLegend;

    this.getChartEl(args).legend = this.showLegend;
  }

  public toggleOrientation(args: string): void {
    const orientationValue = this.htmlElement.querySelector('#orientation') as HTMLInputElement;
    const val = orientationValue.value || 'vertical';
    const el = this.getChartEl(args);
    let xLabel: any;
    let yLabel: any;

    // horizontal orientation
    if (val === 'horizontal') {
      if (args === 'nexus-stacked-bar-chart') {
        xLabel = 'Production';
        yLabel = 'Year';
      } else {
        xLabel = 'Price';
        yLabel = 'Ticker Symbol';
      }
    } else if (args === 'nexus-stacked-bar-chart') {
      xLabel = 'Year';
      yLabel = 'Production';
    } else {
      xLabel = 'Ticker Symbol';
      yLabel = 'Price';
    }

    el.orientation = val;
    el.xLabel = xLabel;
    el.yLabel = yLabel;
  }

  public toggleVertices(args: string): void {
    this.vertices = !this.vertices;
    this.getChartEl(args).vertices = this.vertices;
  }

  public generatePieChartData(numWedges: number): any {
    return this.chartData.slice(0, numWedges);
  }

  public selectTopN(num: number): any {
    this.getChartEl('nexus-pie-chart').chartData = this.generatePieChartData(num);
  }

  public addListeners(): void {
    const chartComponent = this.htmlElement.querySelector('#nexus-pie-chart') as HTMLInputElement;
    chartComponent.addEventListener('nexus-pie-chart-loaded', (evt) => {
      this.htmlElement.querySelector('nexus-pie-chart').chartData = this.generatePieChartData(3);
    });
  }

  ngOnInit(): void {
    this.selectTopN(5);
  }
}

<div id="wrapper" class="nexus-row">
    <!-- interaction controls -->
    <div id="control-container" class="nexus-col-xs-4 nexus-col-lg-3">
      <div class="control-category">Options</div>

      <div class="control-item">
        <nexus-checkbox name="inverse" id="inverse" (change)="toggleInverse('nexus-pie-chart')">Inverse</nexus-checkbox>
      </div>

      <div class="control-item">
        <nexus-checkbox checked name="show-legend" id="showLegend" (change)="toggleLegend('nexus-pie-chart')"
          >Legend</nexus-checkbox
        >
      </div>

      <div class="control-item">
        <nexus-label for="colorScheme" class="select">Color Scheme</nexus-label>
        <select name="color-scheme" id="colorScheme" (input)="selectColorScheme('nexus-pie-chart')">
          <option value="category10" selected>Category 10</option>
          <option value="accent">Accent</option>
          <option value="paired">Paired</option>
          <option value="set1">Set 1</option>
          <option value="set2">Set 2</option>
          <option value="set3">Set 3</option>
          <option value="black">Black</option>
          <option value="gray">Gray</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="legendFontSize" class="select">Legend Font Size</nexus-label>
        <select name="legend_font_size" id="legendFontSize" (input)="selectLegendFontSize('nexus-pie-chart')">
          <option value="10">10px</option>
          <option value="12" selected>12px</option>
          <option value="14">14px</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="innerRadius" class="select">Inner Radius</nexus-label>
        <select name="inner_radius" id="innerRadius" (input)="selectInnerRadius('nexus-pie-chart')">
          <option value="0" selected>0%</option>
          <option value=".25">25%</option>
          <option value=".50">50%</option>
          <option value=".75">75%</option>
          <option value=".95">95%</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="marginBottom" class="select">Margin Bottom</nexus-label>
        <select name="margin-bottom" id="marginBottom" (input)="selectMargin('marginBottom', 'nexus-pie-chart')">
          <option value="0" selected>0px</option>
          <option value="25">25px</option>
          <option value="50">50px</option>
          <option value="100">100px</option>
          <option value="150">150px</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="marginLeft" class="select">Margin Left</nexus-label>
        <select name="margin_left" id="marginLeft" (input)="selectMargin('marginLeft', 'nexus-pie-chart')">
          <option value="0" selected>0px</option>
          <option value="25">25px</option>
          <option value="50">50px</option>
          <option value="100">100px</option>
          <option value="150">150px</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="marginRight" class="select">Margin Right</nexus-label>
        <select name="margin_right" id="marginRight" (input)="selectMargin('marginRight', 'nexus-pie-chart')">
          <option value="0" selected>0px</option>
          <option value="25">25px</option>
          <option value="50">50px</option>
          <option value="100">100px</option>
          <option value="150">150px</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="marginTop" class="select">Margin Top</nexus-label>
        <select name="margin_top" id="marginTop" (input)="selectMargin('marginTop', 'nexus-pie-chart')">
          <option value="0" selected>0px</option>
          <option value="25">25px</option>
          <option value="50">50px</option>
          <option value="100">100px</option>
          <option value="150">150px</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="arcStroke" class="select">Wedge Stroke</nexus-label>
        <select name="arc-stroke" id="arcStroke" (input)="selectArcStroke('nexus-pie-chart')">
          <option value="transparent">transparent</option>
          <option value="#ffffff" selected>white</option>
          <option value="#000000">black</option>
          <option value="#999999">gray</option>
        </select>
      </div>

      <div class="control-item">
        <nexus-label for="lineStroke" class="select">Wedge Stroke Width</nexus-label>
        <select name="line_stroke" id="lineStroke" (input)="selectLineStroke('nexus-pie-chart')">
          <option value="1" selected>1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
      </div>
    </div>

    <!-- chart container -->
    <div id="chart-container" class="nexus-col-xs-4 nexus-col-lg-9 position">
      <div class="page-title">&lt;nexus-pie-chart&gt;</div>
      <div class="hoz-group">
        <div class="btn-item">
          <button type="button" class="nexus-btn" (click)="selectTopN(5)">Top 5</button>
        </div>
        <div class="btn-item">
          <button type="button" class="nexus-btn" (click)="selectTopN(10)">Top 10</button>
        </div>
        <div class="btn-item">
          <button type="button" class="nexus-btn" (click)="selectTopN(15)">Top 15</button>
        </div>
      </div>

      <div class="chart">
        <nexus-pie-chart
          legend
          legend-width="125"
          legend-metric="artist"
          responsive
          stroke="#ffffff"
          tooltips
          value-format="localestring1d"
          value-metric="units"
          [chartData]="chartData"
        ></nexus-pie-chart>
      </div>
    </div>
  </div>

// ui-nexus-design-system/playbook/react/src/components/pie-chart/pie-chart.tsx
import React, { useEffect, useRef, useState } from 'react';
import { NexusPieChart, NexusCheckbox, NexusInput, NexusLabel, NexusSelect } from '@nexus/react';
import './pie-chart.scss';
import { JSX } from '@nexus/core';

const musicSalesData: any = [
  { artist: 'The Beatles', units: 183 },
  { artist: 'Garth Brooks', units: 148 },
  { artist: 'Elvis Presley', units: 146.5 },
  { artist: 'The Eagles', units: 120 },
  { artist: 'Led Zeppelin', units: 111.5 },
  { artist: 'Billy Joel', units: 84.5 },
  { artist: 'Michael Jackson', units: 84 },
  { artist: 'Elton John', units: 78.5 },
  { artist: 'Pink Floyd', units: 75 },
  { artist: 'AC/DC', units: 72 },
  { artist: 'George Strait', units: 69 },
  { artist: 'Barbara Streisand', units: 68.5 },
  { artist: 'The Rolling Stones', units: 66.5 },
  { artist: 'Aerosmith', units: 66.5 },
  { artist: 'Bruce Springsteen', units: 65.5 }
];

const initialValue: JSX.NexusPieChart = {
  chartData: musicSalesData,
  legend: false,
  legendWidth: 125,
  legendMetric: 'artist',
  responsive: true,
  stroke: 'white',
  tooltips: true,
  colorScheme: 'category10',
  valueFormat: 'localestring1d',
  valueMetric: 'units',
  innerRadius: 0,
  inverse: false,
  marginBottom: 0,
  marginLeft: 0,
  marginRight: 0,
  marginTop: 0,
  legendFontSize: 10,
  strokeWidth: 1
};

const App = () => {
  const chartElement = useRef(null);

  const [chartOptions, setChartOptions] = useState<JSX.NexusPieChart>(initialValue);
  const updateState = (field: keyof JSX.NexusPieChart, target: any) => {
    console.log('target', target);
    let value = '';
    if (target.type === 'checkbox') {
      value = target.checked;
    } else {
      value = target.value;
    }
    setChartOptions({
      ...chartOptions,
      [field]: value
    });
  };

  useEffect(() => {
    console.log(chartOptions);
  }, [chartOptions]);

  const selectTopN = (num: number) => {
    setChartOptions({
      ...chartOptions,
      chartData: musicSalesData.slice(0, num)
    });
  };

  interface IOptions {
    label: string;
    value: any;
  }

  /**
   *
   * @param component : Returns the component wrapped in a class for styling purpose
   */
  const wrapInControlItem = (component: React.ReactElement) => (
    <div className='control-item'>{component}</div>
  );
  /**
   *
   * @param field one of NexusPieChart Props
   * @param options options can be of anytype
   * @param label Label to be displayed above
   */
  const renderNexusSelect = (field: keyof JSX.NexusPieChart, options: any[], label: string) => (
    <>
      {' '}
      <NexusLabel className="select">{label}</NexusLabel>
      <NexusSelect value={chartOptions[field]?.toString()} onInput={(e: any) => updateState(field, e.target)}>
        {renderOptions(options)}
      </NexusSelect>
    </>
  );
  /**
   *
   * @param field one of NexusPieChart Props
   * @param options options can be IOptions type
   * @param label Label to be displayed above
   */
  const renderSelctWithCustomOptions = (field: keyof JSX.NexusPieChart, options: IOptions[], label: string) => (
    <>
      {' '}
      <NexusLabel className="select">{label}</NexusLabel>
      <NexusSelect value={chartOptions[field]?.toString()} onInput={(e: any) => updateState(field, e.target)}>
        {renderOptionsWithDifferentValue(options)}
      </NexusSelect>
    </>
  );
  /**
   * Returns <Option> by looping through the array
   * @param options array of any type
   */
  const renderOptions = (options: any[]) =>
    options.map((singleOption) => <option value={singleOption}>{singleOption}</option>);
  const renderOptionsWithDifferentValue = (options: IOptions[]) =>
    options.map((singleOption) => <option value={singleOption.value}>{singleOption.label}</option>);

  /**
   * Returns NexusInput
   * @param label : string, label to be displayed
   * @param field : Props of NexusPieChart component
   */
  const renderNexusInput = (label: string, field: keyof JSX.NexusPieChart) => (
    <>
      <NexusLabel>{label}</NexusLabel>
      <NexusInput
        id="hideX"
        value={chartOptions[field]?.toString()}
        onInput={(e: any) => updateState(field, e.target)}
      />
    </>
  );
  /**
   * Returns a NexusCheckBox
   * @param field : Props of NexusPieChart component
   * @param label : string, label to be displayed
   */
  const renderCheckBox = (field: keyof JSX.NexusPieChart, label: string) => (
    <NexusCheckbox checked={chartOptions[field] as boolean} onClick={(e: any) => updateState(field, e.target)}>
      {label}
    </NexusCheckbox>
  );

  return (
    <>
      <div id="wrapper" className="nexus-row">
        <div className={`nexus-col-xs-4 nexus-col-lg-3 control-container`}>
          <div className='control-category'>Options</div>
          {wrapInControlItem(renderCheckBox('inverse', 'Inverse'))}
          {wrapInControlItem(renderCheckBox('legend', 'Legend'))}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'innerRadius',
              [
                { value: '0', label: '0' },
                { value: '0.25', label: '25%' },
                { value: '0.5', label: '50%' },
                { value: '0.75', label: '75%' },
                { value: '0.95', label: '95%' }
              ],
              'Inner Radius'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'colorScheme',
              [
                { value: 'category10', label: 'category 10' },
                { value: 'accent', label: 'Accent' },
                { value: 'paired', label: 'Paired' },
                { value: 'set1', label: 'set 1' },
                { value: 'set2', label: 'set 2' },
                { value: 'set3', label: 'set 3' },
                { value: 'black', label: 'Black' },
                { value: 'gray', label: 'Gray' }
              ],
              'Color Scheme'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'legendFontSize',
              [
                { value: '10', label: '10px' },
                { value: '12', label: '12px' },
                { value: '14', label: '14px' }
              ],
              'Legend Font Size'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginBottom',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Bottom'
            )
          )}

          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginLeft',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Left'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginRight',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Right'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginTop',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Top'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'stroke',
              [
                { value: 'transparent', label: 'transparent' },
                { value: '#ffffff', label: 'White' },
                { value: '#000000', label: 'Black' },
                { value: '#999999', label: 'Gray' }
              ],
              'Wedge Stroke'
            )
          )}
          {wrapInControlItem(renderNexusSelect('strokeWidth', [1, 2, 3, 4, 5], 'Wedge Stroke Width'))}
        </div>
        <div id="control-container" className={`nexus-col-xs-4 nexus-col-lg-9 chart-container`}>
          <div className='page-title'>&lt;nexus-pie-chart&gt;</div>
          <div className='hoz-group'>
            <span className='btn-item'>
              <button type="button" className="nexus-btn" onClick={() => selectTopN(5)}>
                Top 5
              </button>
            </span>
            <span className="btn-item">
              <button type="button" className="nexus-btn" onClick={() => selectTopN(10)}>
                Top 10
              </button>
            </span>
            <span className="btn-item">
              <button type="button" className="nexus-btn" onClick={() => selectTopN(15)}>
                Top 15
              </button>
            </span>
          </div>
          <div className={chartOptions['inverse'] ? 'chart-inverse' : 'chart'}>
            <NexusPieChart
              legend={chartOptions.legend}
              legendWidth={chartOptions.legendWidth}
              legendMetric={chartOptions.legendMetric}
              responsive
              stroke={chartOptions.stroke}
              tooltips={chartOptions.tooltips}
              valueFormat={chartOptions.valueFormat}
              valueMetric={chartOptions.valueMetric}
              innerRadius={chartOptions.innerRadius}
              chartData={chartOptions.chartData}
              inverse={chartOptions.inverse}
              colorScheme={chartOptions.colorScheme}
              legendFontSize={chartOptions.legendFontSize}
              marginBottom={chartOptions.marginBottom}
              marginLeft={chartOptions.marginLeft}
              marginRight={chartOptions.marginRight}
              marginTop={chartOptions.marginTop}
              strokeWidth={chartOptions.strokeWidth}
              ref={chartElement}
            ></NexusPieChart>
          </div>
        </div>
      </div>
    </>
  );
};

export default App;
