// ui-nexus-design-system/playbook/react/src/sb/components/header/01_header.tsx
import React from 'react';
import {Link} from 'react-router-dom';
import { NexusHeader, NexusHeaderMenu, NexusMenuItem, NexusHeaderLogo, NexusIcon } from '@nexus/react';
import Logo from '@nexus/core/dist/assets/images/nexus-logo.svg';

const HeaderComponent: React.FC = () => (
  <NexusHeader class="nexus-header-sticky">
    <NexusHeaderLogo>
      <Link to='#'>
        <NexusIcon
          data-testid="nexus-header-logo"
          src={Logo} />
        <span className="nexus-visually-hidden">Home</span>
      </Link>
    </NexusHeaderLogo>

    <NexusHeaderMenu
      data-testid="nexus-hamburger-icon"
    >
      <NexusMenuItem>
        <Link to='#' data-testid="menu-item1">Item 1</Link>
      </NexusMenuItem>

      <NexusMenuItem>
        <Link to='#' data-testid="menu-item2">Item 2</Link>
      </NexusMenuItem>

      <NexusMenuItem>
        <Link to='#' data-testid="menu-item3">Item 3</Link>
      </NexusMenuItem>
    </NexusHeaderMenu>
  </NexusHeader>
);

export default HeaderComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/header/01_header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './01_header.component.html'
})
export default class HeaderComponent {}

<nexus-header class="nexus-header-sticky">
  <nexus-header-logo>
    <a href="javascript:void(0)">
      <nexus-icon data-testid="nexus-header-logo" src="./assets/images/nexus-logo.svg"></nexus-icon>
      <span class="nexus-visually-hidden">Home</span>
    </a>
  </nexus-header-logo>

  <nexus-header-menu data-testid="nexus-hamburger-icon">
    <nexus-menu-item data-testid="menu-item1">
      <a href="javascript:void(0)">Item 1</a>
    </nexus-menu-item>

    <nexus-menu-item data-testid="menu-item2">
      <a href="javascript:void(0)">Item 2</a>
    </nexus-menu-item>

    <nexus-menu-item data-testid="menu-item3">
      <a href="javascript:void(0)">Item 3</a>
    </nexus-menu-item>
  </nexus-header-menu>
</nexus-header>
