// ui-nexus-design-system/playbook/react/src/sb/components/header/02_withAvatar.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import { NexusHeader, NexusHeaderMenu, NexusMenuItem, NexusHeaderLogo, NexusIcon, NexusAvatar } from '@nexus/react';
import Logo from '@nexus/core/dist/assets/images/nexus-logo.svg';
import AvatarImage from '@nexus/core/dist/assets/images/avatar.png';

const WithAvatar: React.FC = () => (
    <NexusHeader class="nexus-header-sticky">
        <NexusHeaderLogo>
            <Link to='#'>
                <NexusIcon
                    data-testid="nexus-header-logo"
                    src={Logo} />
                <span className="nexus-visually-hidden">Home</span>
            </Link>
        </NexusHeaderLogo>

        <NexusHeaderMenu
            data-testid="nexus-hamburger-icon"
        >
            <NexusMenuItem>
                <Link to='#' data-testid="menu-item1">Home</Link>
            </NexusMenuItem>

            <NexusMenuItem>
                <Link to='#' data-testid="menu-item2">Dashboard</Link>
            </NexusMenuItem>

            <NexusMenuItem>
                <NexusAvatar
                    userName={'Jane Doe'}
                    avatarNotification={''}
                    avatarImageSrc={''}
                    avatarClassName={''}
                    avatarSize={'lg'}
                    avatarStatus={'online'}
                    description={''}
                    avatarNameDisplay={true}
                    avatarDark={false}
                    avatarLogoIcon={''}
                    avatar-image-src={AvatarImage}
                    className="nexus-pt-2"
                />
            </NexusMenuItem>
        </NexusHeaderMenu>
    </NexusHeader>
);

export default WithAvatar;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/header/02_withAvatar.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-with-header',
  templateUrl: './02_withAvatar.component.html'
})
export default class HeaderWithAvatarComponent {
}

<nexus-header class="nexus-header-sticky">
  <nexus-header-logo>
    <a href="javascript:void(0)">
      <nexus-icon data-testid="nexus-header-logo" src="./assets/images/nexus-logo.svg"></nexus-icon>
      <span class="nexus-visually-hidden">Home</span>
    </a>
  </nexus-header-logo>

  <nexus-header-menu data-testid="nexus-hamburger-icon">
    <nexus-menu-item data-testid="menu-item1">
      <a href="javascript:void(0)">Home</a>
    </nexus-menu-item>

    <nexus-menu-item data-testid="menu-item2">
      <a href="javascript:void(0)">Dashboard</a>
    </nexus-menu-item>

    <nexus-menu-item data-testid="menu-item3">
      <nexus-avatar class="nexus-pt-2" avatar-image-src="./assets/images/avatar.png" avatar-size="lg"
        avatar-status="online" avatar-name-display="true" user-name="Jane Doe">
      </nexus-avatar>


    </nexus-menu-item>
  </nexus-header-menu>
</nexus-header>
