// ui-nexus-design-system/playbook/angular/src/app/sb/components/radio/02_group.component.ts
import { Component, Input } from '@angular/core';
import { radio, group } from '../../constants';

@Component({
  selector: 'app-group',
  templateUrl: './02_group.component.html'
})
export default class GroupComponent {
  @Input() name = radio.name;

  @Input() disabled: boolean = false;

  group = group;
}

<div class="nexus-col-xs ">
    <nexus-label>{{group.label}}</nexus-label>

    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="disabled">
            {{group.first}}
        </nexus-radio>
    </div>
    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="disabled">
            {{group.second}}
        </nexus-radio>
    </div>
    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="disabled">
            {{group.third}}
        </nexus-radio>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/radio/02_group.tsx
import React, { useState } from 'react';
import { group } from '../../constants';


import { NexusLabel, NexusRadio } from '@nexus/react';

const RadioExampleComponent: React.FC = () => {
    const [value1, setValue1] = useState('');

    return (
        <>
            <section className="nexus-rhythm-5">
                <NexusLabel>{group.label}</NexusLabel>
                <div className="nexus-col-xs-1">

                    <NexusRadio
                        data-testid="option1"
                        checked={value1 === 'option1'}
                        name="frameworks"
                        disabled={false}
                        onInput={(event: any) => setValue1(event.target.value)}
                        aria-hidden="true"
                    >
                        {group.first}
                    </NexusRadio>
                </div>

                <div className="nexus-col-xs-1">

                    <NexusRadio
                        data-testid="option2"
                        checked={value1 === 'option2'}
                        name="frameworks"
                        disabled={false}
                        onInput={(event: any) => setValue1(event.target.value)}
                        aria-hidden="true"
                    >
                        {group.second}
                    </NexusRadio>
                </div>

                <div className="nexus-col-xs-1">
                    <NexusRadio
                        data-testid="disled-option3"
                        checked={value1 === 'option3'}
                        name="frameworks"
                        disabled={false}
                        onInput={(event: any) => setValue1(event.target.value)}
                        aria-hidden="true"
                    >
                        {group.third}
                    </NexusRadio>
                </div>

            </section>
        </>
    );
};

export default RadioExampleComponent;
