// ui-nexus-design-system/playbook/angular/src/app/sb/components/radio/04_variants.component.ts
import { Component, Input } from '@angular/core';
import { radio, variants } from '../../constants';

@Component({
  selector: 'app-variants',
  templateUrl: './04_variants.component.html'
})
export default class VariantsComponent {
  @Input() name = radio.name;

  @Input() disabled: boolean = true;

  variants = variants;
}

<div class="nexus-col-xs ">
    <nexus-label>{{variants.first}}</nexus-label>

    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" name="variants">
            {{variants.default}}</nexus-radio>
    </div>
    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" name="variants" checked="true">
            {{variants.checked}}</nexus-radio>
    </div>

    <nexus-label>{{variants.second}}</nexus-label>
    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" name="variantDisabled" [disabled]="true">
            {{variants.disabled}}</nexus-radio>
    </div>
    <div class="nexus-col-xs-1">
        <nexus-radio data-testid="radio-btn-opt1" name="variantDisabled" checked [disabled]="true">
            {{variants.both}}</nexus-radio>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/radio/04_variants.tsx
import React, { useState } from 'react';
import { variants } from '../../constants';

import { NexusLabel, NexusRadio } from '@nexus/react';

const RadioExampleComponent: React.FC = () => {
    const [value1, setValue1] = useState('option2');
    const [value2, setValue2] = useState('option4');

    return (
        <>
            <div className="nexus-col-xs ">

                <NexusLabel>{variants.first}</NexusLabel>

                <div className="nexus-col-xs-1">
                    <NexusRadio
                        data-testid="option1"
                        checked={value1 === 'option1'}
                        name="variants"
                        disabled={false}
                        onInput={(event: any) => setValue1(event.target.value)}
                        aria-hidden="true"
                    >
                        {variants.default}
                    </NexusRadio>
                </div>

                <div className="nexus-col-xs-1">
                    <NexusRadio
                        data-testid="option2"
                        checked={value1 === 'option2'}
                        name="variants"
                        disabled={false}
                        onInput={(event: any) => setValue1(event.target.value)}
                        aria-hidden="true"
                    >
                        {variants.checked}
                    </NexusRadio>
                </div>

                <NexusLabel>{variants.second}</NexusLabel>

                <div className="nexus-col-xs-1">
                    <NexusRadio
                        data-testid="option3"
                        checked={value2 === 'option3'}
                        name="variantDisabled"
                        disabled={true}
                        onInput={(event: any) => setValue2(event.target.value)}
                        aria-hidden="true"
                    >
                        {variants.disabled}
                    </NexusRadio>
                </div>

                <div className="nexus-col-xs-1">
                    <NexusRadio
                        data-testid="option4"
                        checked={value2 === 'option4'}
                        name="variantDisabled"
                        disabled={true}
                        onInput={(event: any) => setValue2(event.target.value)}
                        aria-hidden="true"
                    >
                        {variants.both}
                    </NexusRadio>
                </div>
            </div>
        </>
    );
};

export default RadioExampleComponent;
