// ui-nexus-design-system/playbook/angular/src/app/components/bar-chart/bar-chart.component.ts
/* eslint-disable indent */
/* eslint-disable max-lines */
import { Component, OnInit, ElementRef } from '@angular/core';

@Component({
  selector: 'app-bar-chart',
  templateUrl: './bar-chart.component.html',
  styleUrls: ['./bar-chart.component.scss']
})
export class BarChartComponent implements OnInit {
  public data: Array<any> = [
    {
      ticker: 'KO',
      name: 'Coca-Cola',
      value: 52.36
    },
    {
      ticker: 'BZH',
      name: 'Beazer Homes',
      value: 11.11
    },
    {
      ticker: 'ADM',
      name: 'Arch-Dan-Mid',
      value: 37.17
    },
    {
      ticker: 'ABCB',
      name: 'Ameris Bancorp',
      value: 36.44
    },
    {
      ticker: 'ORCL',
      name: 'Oracle',
      value: 53.75
    },
    {
      ticker: 'MIL',
      name: 'MILD',
      value: 37.17
    },
    {
      ticker: 'HCL',
      name: 'HCL',
      value: 36.44
    },
    {
      ticker: 'MFL',
      name: 'Madras',
      value: 53.75
    },
    {
      ticker: 'PLNT',
      name: 'Planet Fitness',
      value: 77.27
    }
  ];

  public gridlines: any;

  public inverse: any;

  public showLegend: any;

  public showPieLegend: any;

  public vertices: any;

  public hideYAxis: any;

  public showYLabel: any;

  public showYTicks: any;

  public hideXAxis: any;

  public showXLabel: any;

  public showXTicks: any;

  private htmlElement: HTMLElement;

  constructor(public elRef: ElementRef) {
    this.htmlElement = this.elRef.nativeElement;

    this.gridlines = false;
    this.inverse = false;
    this.showLegend = false;
    this.showPieLegend = true;
    this.vertices = true;

    this.hideYAxis = false;
    this.showYLabel = true;
    this.showYTicks = true;

    this.hideXAxis = false;
    this.showXLabel = true;
    this.showXTicks = true;
  }

  public changeXLabel(args: any, value: any): any {
    this.getChartEl(args).xLabel = value;
    const xLabelInput = this.htmlElement.querySelector('#xLabelInput') as HTMLInputElement;
    xLabelInput.value = '';
  }

  public changeYLabel(args: any, value: any): any {
    this.getChartEl(args).yLabel = value;
    const yLabelInput = this.htmlElement.querySelector('#yLabelInput') as HTMLInputElement;
    yLabelInput.value = '';
  }

  public getChartEl(id: string): any {
    return document.querySelector(id);
  }

  public randomizer(): any {
    return Math.floor(Math.random() * 500) - 250;
  }

  public selectArcStroke(args: string): any {
    const arcStroke = this.htmlElement.querySelector('#arcStroke') as HTMLInputElement;
    this.getChartEl(args).stroke = arcStroke.value;
  }

  public selectAxisLabelFontSize(args: string): void {
    const axisLabelFontSize = this.htmlElement.querySelector('#axisLabelFontSize') as HTMLInputElement;
    this.getChartEl(args).axisLabelFontSize = axisLabelFontSize.value;
  }

  public selectAxisTickFontSize(args: string): void {
    const axisTickFontSize = this.htmlElement.querySelector('#axisTickFontSize') as HTMLInputElement;
    this.getChartEl(args).axisTickFontSize = axisTickFontSize.value;
  }

  public selectAxisTickFontFamily(args: string): void {
    const axisTickFontFamily = this.htmlElement.querySelector('#axisTickFontFamily') as HTMLInputElement;
    this.getChartEl(args).axisTickFontFamily = axisTickFontFamily.value;
  }

  public selectBarStroke(args: string): void {
    const barStroke = this.htmlElement.querySelector('#barStroke') as HTMLInputElement;
    this.getChartEl(args).barStroke = barStroke.value;
  }

  public selectBarStrokeWidth(args: string): void {
    const barStrokeWidth = this.htmlElement.querySelector('#barStrokeWidth') as HTMLInputElement;
    this.getChartEl(args).barStrokeWidth = barStrokeWidth.value;
  }

  public selectColorScheme(args: string): void {
    const colorScheme = this.htmlElement.querySelector('#colorScheme') as HTMLInputElement;
    this.getChartEl(args).colorScheme = colorScheme.value;
  }

  public selectInnerRadius(args: string): void {
    const innerRadius = this.htmlElement.querySelector('#innerRadius') as HTMLInputElement;
    this.getChartEl(args).innerRadius = innerRadius.value;
  }

  public selectInterpolation(args: string): void {
    const interpolation = this.htmlElement.querySelector('#interpolation') as HTMLInputElement;
    this.getChartEl(args).interpolation = interpolation.value;
  }

  public selectLegendFontSize(args: string): void {
    const legendFontSize = this.htmlElement.querySelector('#legendFontSize') as HTMLInputElement;
    this.getChartEl(args).legendFontSize = legendFontSize.value;
  }

  public selectLinearDomain(args: string): void {
    const val = this.htmlElement.querySelector('#linearDomain') as HTMLInputElement;
    const el = this.getChartEl(args);
    if (val.value === 'percent') {
      el.linearTickFormat = 'percent1d';
    } else {
      el.linearTickFormat = 'localestring';
    }
    this.getChartEl(args).linearDomain = val.value;
  }

  public selectLineStroke(args: string): void {
    const val = this.htmlElement.querySelector('#lineStroke') as HTMLInputElement;
    this.getChartEl(args).strokeWidth = val.value;
  }

  public selectMargin(marginAttribute: string, args: any): any {
    const val = this.htmlElement.querySelector(`#${marginAttribute}`) as HTMLInputElement;
    const el = this.getChartEl(args);
    el[marginAttribute] = val.value;
  }

  public selectMaxBarWidth(args: string): void {
    const val = this.htmlElement.querySelector('#maxBarWidth') as HTMLInputElement;
    this.getChartEl(args).maxBarWidth = val.value;
  }

  public selectXTickSize(args: string): void {
    const val = this.htmlElement.querySelector('#xTickSize') as HTMLInputElement;
    this.getChartEl(args).xTickSize = val.value;
  }

  public selectYTickSize(args: string): void {
    const val = this.htmlElement.querySelector('#yTickSize') as HTMLInputElement;
    this.getChartEl(args).yTickSize = val.value;
  }

  public toggleGridlines(args: string): void {
    this.gridlines = !this.gridlines;
    this.getChartEl(args).gridlines = this.gridlines;
  }

  public toggleInverse(args: string): void {
    this.inverse = !this.inverse;
    this.getChartEl(args).inverse = this.inverse;

    if (this.inverse) {
      this.htmlElement.querySelector('div.chart').classList.add('inverse');
    } else {
      this.htmlElement.querySelector('div.chart').classList.remove('inverse');
    }
  }

  public toggleLegend(args: string): void {
    if (args === 'nexus-pie-chart') {
      this.showPieLegend = !this.showPieLegend;
      this.getChartEl(args).legend = this.showPieLegend;

      return;
    }

    this.showLegend = !this.showLegend;

    this.getChartEl(args).legend = this.showLegend;
  }

  public toggleOrientation(args: string): void {
    const orientationValue = this.htmlElement.querySelector('#orientation') as HTMLInputElement;
    const val = orientationValue.value || 'vertical';
    const el = this.getChartEl(args);
    let xLabel: any;
    let yLabel: any;

    // horizontal orientation
    if (val === 'horizontal') {
      if (args === 'nexus-stacked-bar-chart') {
        xLabel = 'Production';
        yLabel = 'Year';
      } else {
        xLabel = 'Price';
        yLabel = 'Ticker Symbol';
      }
    } else if (args === 'nexus-stacked-bar-chart') {
      xLabel = 'Year';
      yLabel = 'Production';
    } else {
      xLabel = 'Ticker Symbol';
      yLabel = 'Price';
    }

    el.orientation = val;
    el.xLabel = xLabel;
    el.yLabel = yLabel;
  }

  public toggleVertices(args: string): void {
    this.vertices = !this.vertices;
    this.getChartEl(args).vertices = this.vertices;
  }

  public toggleShowHideXAxis(args: string): void {
    this.hideXAxis = !this.hideXAxis;
    const el = this.getChartEl(args);

    if (this.hideXAxis) {
      el.xLabel = '';
      el.hideXAxis = true;
      el.hideXTicks = true;

      this.showXLabel = false;
      this.showXTicks = false;

      const xLabelItem = this.htmlElement.querySelector('#xLabel') as HTMLInputElement;
      xLabelItem.checked = false;
      xLabelItem.disabled = true;

      const xTicksItem = this.htmlElement.querySelector('#xTicks') as HTMLInputElement;
      xTicksItem.checked = false;
      xTicksItem.disabled = true;
    } else {
      el.xLabel = 'Date';
      el.hideXAxis = false;
      el.hideXTicks = false;

      this.showXLabel = true;
      this.showXTicks = true;

      const xLabelItem1 = this.htmlElement.querySelector('#xLabel') as HTMLInputElement;
      xLabelItem1.checked = true;
      xLabelItem1.disabled = false;

      const xTicksItem1 = this.htmlElement.querySelector('#xTicks') as HTMLInputElement;
      xTicksItem1.checked = true;
      xTicksItem1.disabled = false;
    }
  }

  public toggleShowHideXLabel(args: string): void {
    this.showXLabel = !this.showXLabel;
    let label: any;
    label = '';
    switch (args) {
      default:
        label = 'Date';
        break;
    }
    this.getChartEl(args).xLabel = this.showXLabel ? label : '';
  }

  public toggleShowHideXTicks(args: string): void {
    this.showXTicks = !this.showXTicks;
    this.getChartEl(args).hideXTicks = !this.showXTicks;
  }

  public toggleShowHideYAxis(args: string): void {
    this.hideYAxis = !this.hideYAxis;
    const el = this.getChartEl(args);

    if (this.hideYAxis) {
      el.yLabel = '';
      el.hideYAxis = true;
      el.hideYTicks = true;

      this.showYLabel = false;
      this.showYTicks = false;

      const yLabelItem2 = this.htmlElement.querySelector('#yLabel') as HTMLInputElement;
      yLabelItem2.checked = false;
      yLabelItem2.disabled = true;

      const yTicksItem2 = this.htmlElement.querySelector('#yTicks') as HTMLInputElement;
      yTicksItem2.checked = false;
      yTicksItem2.disabled = true;
    } else {
      el.yLabel = 'Score';
      el.hideYAxis = false;
      el.hideYTicks = false;

      this.showYLabel = true;
      this.showYTicks = true;

      const yLabelItem3 = this.htmlElement.querySelector('#yLabel') as HTMLInputElement;
      yLabelItem3.checked = true;
      yLabelItem3.disabled = false;
      const yTicksItem3 = this.htmlElement.querySelector('#yTicks') as HTMLInputElement;
      yTicksItem3.checked = true;
      yTicksItem3.disabled = false;
    }
  }

  public toggleShowHideYLabel(args: string): void {
    this.showYLabel = !this.showYLabel;
    this.getChartEl(args).yLabel = this.showYLabel ? 'Score' : '';
  }

  public toggleShowHideYTicks(args: string): void {
    this.showYTicks = !this.showYTicks;
    this.getChartEl(args).hideYTicks = !this.showYTicks;
  }

  public generateBarChartData(numBars: number): any {
    this.data.sort((aItem, bItem) => aItem.ticker > bItem.ticker ? 1 : -1);

    return this.data.slice(0, numBars);
  }

  public selectNumBars(numBars: number): any {
    this.getChartEl('nexus-bar-chart').chartData = this.generateBarChartData(numBars);
  }

  public addListeners(): void {
    const xLabelInputMethod = this.htmlElement.querySelector('#xLabelInput') as HTMLInputElement;
    xLabelInputMethod.addEventListener('keyup', (evt) => {
      if (evt.key === 'Enter') {
        const evtVal = evt.target as HTMLInputElement;
        this.changeXLabel('nexus-bar-chart', evtVal.value);
      }
    });

    const yLabelInputMethod = this.htmlElement.querySelector('#yLabelInput') as HTMLInputElement;
    yLabelInputMethod.addEventListener('keyup', (evt) => {
      if (evt.key === 'Enter') {
        const evtVal = evt.target as HTMLInputElement;
        this.changeYLabel('nexus-bar-chart', evtVal.value);
      }
    });
  }

  ngOnInit(): void {
    this.htmlElement.querySelector('nexus-bar-chart').chartData = this.generateBarChartData(3);
    this.addListeners();
    this.selectNumBars(9);
  }
}

<div class="nexus-row">
    <div class="nexus-col-xs-1 nexus-col-md-2 nexus-col-lg-3">
        <nexus-label for="xTickSize" class="select">Tick Size / Length</nexus-label>
        <select name="x-tick-size" id="xTickSize" (input)="selectXTickSize('nexus-bar-chart')">
            <option value="2" selected>2</option>
            <option value="4">4</option>
            <option value="10">10</option>
            <option value="12">12</option>
            <option value="16">16</option>
        </select>

        <div class="control-item">
            <nexus-label for="xLabelInput" class="select">Label</nexus-label>
            <nexus-input type="text" placeholder="Enter text" id="xLabelInput"></nexus-input>
        </div>

        <!-- Y axis -->
        <div class="control-category">Y-axis</div>
        <div class="control-item">
            <nexus-checkbox name="y-label" id="yLabel" checked (change)="toggleShowHideYLabel('nexus-bar-chart')">Show
                Label</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-checkbox name="y-ticks" id="yTicks" checked (change)="toggleShowHideYTicks('nexus-bar-chart')">Show
                Tick
                Values</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-checkbox name="hide-y" id="hideY" (change)="toggleShowHideYAxis('nexus-bar-chart')">Hide Entire
                Y-axis</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-label for="yTickSize" class="select">Tick Size / Length</nexus-label>
            <select name="y-tick-size" id="yTickSize" (input)="selectYTickSize('nexus-bar-chart')">
                <option value="2" selected>2</option>
                <option value="4">4</option>
                <option value="10">10</option>
                <option value="12">12</option>
                <option value="16">16</option>
            </select>
        </div>
        <div class="control-item">
            <nexus-label for="yLabelInput" class="select">Label</nexus-label>
            <nexus-input type="text" placeholder="Enter text" id="yLabelInput"></nexus-input>
        </div>

        <!-- miscellaneous options -->
        <div class="control-category">Options</div>

        <div class="control-item">
            <nexus-checkbox name="show-gridlines" id="showGridlines"
                (change)="toggleGridlines('nexus-bar-chart')">Gridlines</nexus-checkbox>
        </div>

        <div class="control-item">
            <nexus-checkbox name="inverse" id="inverse"
                (change)="toggleInverse('nexus-bar-chart')">Inverse</nexus-checkbox>
        </div>

        <div class="control-item">
            <nexus-checkbox name="show-legend" id="showLegend"
                (change)="toggleLegend('nexus-bar-chart')">Legend</nexus-checkbox>
        </div>

        <!-- other axis stuff -->
        <div class="control-item">
            <nexus-label for="axisLabelFontSize" class="select">Axis Label Font Size</nexus-label>
            <select name="axis-label-font-size" id="axisLabelFontSize"
                (input)="selectAxisLabelFontSize('nexus-bar-chart')">
                <option value="9">9px</option>
                <option value="12">12px</option>
                <option value="14" selected>14px</option>
                <option value="16">16px</option>
                <option value="20">20px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="axisTickFontFamily" class="select">Axis Tick Font Family</nexus-label>
            <select name="axis-tick-font-family" id="axisTickFontFamily"
                (input)="selectAxisTickFontFamily('nexus-bar-chart')">
                <option value="sans" selected>sans-serif</option>
                <option value="serif">serif</option>
                <option value="monospace">monospace</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="axisTickFontSize" class="select">Axis Tick Font Size</nexus-label>
            <select name="axis-tick-font-size" id="axisTickFontSize"
                (input)="selectAxisTickFontSize('nexus-bar-chart')">
                <option value="8">8px</option>
                <option value="9">9px</option>
                <option value="10" selected>10px</option>
                <option value="12">12px</option>
            </select>
        </div>

        <!-- bar stuff -->
        <div class="control-item">
            <nexus-label for="barStroke" class="select">Bar Stroke</nexus-label>
            <select name="bar_stroke" id="barStroke" (input)="selectBarStroke('nexus-bar-chart')">
                <option value="transparent" selected>transparent</option>
                <option value="#000000">black</option>
                <option value="#ffffff">white</option>
                <option value="#999999">gray</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="barStrokeWidth" class="select">Bar Stroke Width</nexus-label>
            <select name="bar_stroke_width" id="barStrokeWidth" (input)="selectBarStrokeWidth('nexus-bar-chart')">
                <option value="0">none</option>
                <option value="1" selected>1px</option>
                <option value="2">2px</option>
                <option value="5">5px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="maxBarWidth" class="select">Bar Width, Max</nexus-label>
            <select name="max_bar_width" id="maxBarWidth" (input)="selectMaxBarWidth('nexus-bar-chart')">
                <option value="5">5px</option>
                <option value="25">25px</option>
                <option value="50">50px</option>
                <option value="75" selected>75px</option>
                <option value="2000">fill space</option>
            </select>
        </div>

        <!-- color scheme --->
        <div class="control-item">
            <nexus-label for="colorScheme" class="select">Color Scheme</nexus-label>
            <select name="color-scheme" id="colorScheme" (input)="selectColorScheme('nexus-bar-chart')">
                <option value="category10" selected>Category 10</option>
                <option value="accent">Accent</option>
                <option value="paired">Paired</option>
                <option value="set1">Set 1</option>
                <option value="set2">Set 2</option>
                <option value="set3">Set 3</option>
                <option value="black">Black</option>
                <option value="gray">Gray</option>
            </select>
        </div>

        <!-- legend font size -->
        <div class="control-item">
            <nexus-label for="legendFontSize" class="select">Legend Font Size</nexus-label>
            <select name="legend_font_size" id="legendFontSize" (input)="selectLegendFontSize('nexus-bar-chart')">
                <option value="10">10px</option>
                <option value="12" selected>12px</option>
                <option value="14">14px</option>
            </select>
        </div>

        <!-- orientation -->
        <div class="control-item">
            <nexus-label for="orientation" class="select">Orientation</nexus-label>
            <select name="orient" id="orientation" (input)="toggleOrientation('nexus-bar-chart')">
                <option value="vertical" selected>vertical</option>
                <option value="horizontal">horizontal</option>
            </select>
        </div>

        <!-- top, right, bottom, left margins -->
        <div class="control-item">
            <nexus-label for="marginBottom" class="select">Margin Bottom></nexus-label>
            <select name="margin-bottom" id="marginBottom" (input)="selectMargin('marginBottom', 'nexus-bar-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="marginRight" class="select">Margin Right</nexus-label>
            <select name="margin_right" id="marginRight" (input)="selectMargin('marginRight', 'nexus-bar-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="marginLeft" class="select">Margin Left</nexus-label>
            <select name="margin_left" id="marginLeft" (input)="selectMargin('marginLeft', 'nexus-bar-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="marginTop" class="select">Margin Top></nexus-label>
            <select name="margin_top" id="marginTop" (input)="selectMargin('marginTop', 'nexus-bar-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>
    </div>
    <!-- chart container -->
    <div class="nexus-col-xs-3 nexus-col-md-6 nexus-col-lg-9 position">
        <div class="page-title">&lt;nexus-bar-chart&gt;</div>

        <p>Demonstrating a bar chart with stock ticker symbols / prices.</p>

        <div class="hoz-group">
            <div class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumBars(1)">1 Stock</button>
            </div>
            <div class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumBars(2)">2 Stocks</button>
            </div>
            <div class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumBars(3)">3 Stocks</button>
            </div>
            <div class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumBars(4)">4 Stocks</button>
            </div>
            <div class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumBars(5)">5 Stocks</button>
            </div>
        </div>

        <div class="chart">
            <nexus-bar-chart chart-id="myStvBarChart" legend-metric="name" linear-metric="value"
                linear-tick-format="USD" margin-left="35" ordinal-metric="ticker" responsive tooltips
                x-label="Ticker Symbol" y-label="Price"></nexus-bar-chart>
        </div>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/components/bar-chart/bar-chart.tsx
import React, { useEffect, useState } from 'react';

import { NexusBarChart, NexusCheckbox, NexusInput, NexusLabel, NexusSelect } from '@nexus/react';
import './bar-chart';
import { JSX } from '@nexus/core';
const barChartData = [
  { ticker: 'KO', name: 'Coca-Cola', value: 52.36 },
  { ticker: 'BZH', name: 'Beazer Homes', value: 11.11 },
  { ticker: 'ADM', name: 'Arch-Dan-Mid', value: 37.17 },
  { ticker: 'ABCB', name: 'Ameris Bancorp', value: 36.44 },
  { ticker: 'ORCL', name: 'Oracle', value: 53.75 },
  { ticker: 'MIL', name: 'MILD', value: 37.17 },
  { ticker: 'HCL', name: 'HCL', value: 36.44 },
  { ticker: 'MFL', name: 'Madras', value: 53.75 },
  { ticker: 'PLNT', name: 'Planet Fitness', value: 77.27 }
];
const initialValue: JSX.NexusBarChart = {
  chartData: barChartData,
  responsive: true,
  hideXAxis: false,
  xTickSize: 2,
  axisLabelFontSize: 10,
  axisTickFontFamily: 'interstate',
  axisTickFontSize: 12,
  xLabel: 'Ticker Symbol',
  yLabel: 'Price',
  hideXTicks: false,
  hideYAxis: false,
  yTickSize: 2,
  orientation: 'vertical',
  marginLeft: 50,
  marginRight: 10,
  marginBottom: 25,
  marginTop: 5,
  barStroke: 'transparent',
  barStrokeWidth: 1,
  maxBarWidth: 50,
  colorScheme: 'category10',
  gridlines: false,
  inverse: false,
  legend: true
};
interface IOptions {
  label: string;
  value: any;
}
const App = () => {
  const [chartOptions, setChartOptions] = useState<JSX.NexusBarChart>(initialValue);
  const updateState = (field: keyof JSX.NexusBarChart, value: any) =>
    setChartOptions({
      ...chartOptions,
      [field]: value
    });
  /**
   *
   * @param component : Returns the component wrapped in a class for styling purpose
   */
  const wrapInControlItem = (component: React.ReactElement) => (
    <div className='control-item'>{component}</div>
  );
  /**
   *
   * @param field one of NexusBarChart Props
   * @param options options can be of anytype
   * @param label Label to be displayed above
   */
  const renderNexusSelect = (field: keyof JSX.NexusBarChart, options: any[], label: string) => (
    <>
      {' '}
      <NexusLabel className="select">{label}</NexusLabel>
      <NexusSelect value={chartOptions[field]?.toString()} onInput={(e: any) => updateState(field, e.target.value)}>
        {renderOptions(options)}
      </NexusSelect>
    </>
  );
  /**
   *
   * @param field one of NexusBarChart Props
   * @param options options can be IOptions type
   * @param label Label to be displayed above
   */
  const renderSelctWithCustomOptions = (field: keyof JSX.NexusBarChart, options: IOptions[], label: string) => (
    <>
      {' '}
      <NexusLabel className="select">{label}</NexusLabel>
      <NexusSelect value={chartOptions[field]?.toString()} onInput={(e: any) => updateState(field, e.target.value)}>
        {renderOptionsWithDifferentValue(options)}
      </NexusSelect>
    </>
  );
  /**
   * Returns <Option> by looping through the array
   * @param options array of any type
   */
  const renderOptions = (options: any[]) =>
    options.map((singleOption) => <option value={singleOption}>{singleOption}</option>);
  const renderOptionsWithDifferentValue = (options: IOptions[]) =>
    options.map((singleOption) => <option value={singleOption.value}>{singleOption.label}</option>);

  /**
   * Returns NexusInput
   * @param label : string, label to be displayed
   * @param field : Props of NexusBarChart component
   */
  const renderNexusInput = (label: string, field: keyof JSX.NexusBarChart) => (
    <>
      <NexusLabel>{label}</NexusLabel>
      <NexusInput
        id="hideX"
        value={chartOptions[field]?.toString()}
        onInput={(e: any) => updateState(field, e.target.value)}
      />
    </>
  );
  /**
   * Returns a NexusCheckBox
   * @param field : Props of NexusBarChart component
   * @param label : string, label to be displayed
   */
  const renderCheckBox = (field: keyof JSX.NexusBarChart, label: string) => (
    <NexusCheckbox checked={chartOptions[field] as boolean} onClick={(e: any) => updateState(field, e.target.checked)}>
      {label}
    </NexusCheckbox>
  );

  const renderChart = () => (
    <div id="chart-container" className={`nexus-col-xs-4 nexus-col-lg-9 chart-container`}>
      <div className='page-title'>&lt;nexus-bar-chart&gt;</div>
      <p>Demonstrating a bar chart with stock ticker symbols / prices.</p>
      <div className={chartOptions['inverse'] ? 'chart-inverse' : 'chart'}>
        <NexusBarChart
          responsive
          chart-id="myStvBarChart"
          hideXAxis={chartOptions.hideXAxis}
          xTickSize={chartOptions.xTickSize}
          legendMetric="name"
          linearMetric="value"
          linear-tick-format="USD"
          margin-left="35"
          ordinal-metric="ticker"
          axisLabelFontSize={chartOptions.axisTickFontSize}
          axisTickFontFamily={chartOptions.axisTickFontFamily}
          axisTickFontSize={chartOptions.axisTickFontSize}
          x-label={chartOptions.xLabel}
          y-label={chartOptions.yLabel}
          hideXTicks={chartOptions.hideXTicks}
          hideYAxis={chartOptions.hideYAxis}
          yTickSize={chartOptions.yTickSize}
          chartData={chartOptions.chartData}
          orientation={chartOptions.orientation}
          marginLeft={chartOptions.marginLeft}
          marginRight={chartOptions.marginRight}
          marginBottom={chartOptions.marginBottom}
          marginTop={chartOptions.marginTop}
          barStroke={chartOptions.barStroke}
          barStrokeWidth={chartOptions.barStrokeWidth}
          maxBarWidth={chartOptions.maxBarWidth}
          colorScheme={chartOptions.colorScheme}
          gridlines={chartOptions.gridlines}
          inverse={chartOptions.inverse}
          legend={chartOptions.legend}
          tooltips={true}
        ></NexusBarChart>
      </div>
    </div>
  );
  useEffect(() => {
    console.log(chartOptions);
  }, [chartOptions]);
  return (
    <>
      <div id="wrapper" className="nexus-row">
        <div className={`nexus-col-xs-4 nexus-col-lg-3 control-category`}>
          <div className="control-category">X-axis</div>
          {wrapInControlItem(renderCheckBox('hideXAxis', 'Hide Entire X-axis'))}
          {wrapInControlItem(renderCheckBox('hideXTicks', 'Hide Tick Values'))}
          {wrapInControlItem(renderNexusSelect('xTickSize', [2, 4, 10, 12, 16], 'Tick Size / Length'))}
          {wrapInControlItem(renderNexusInput('X-label', 'xLabel'))}
          <div className="control-category">Y-axis</div>
          {wrapInControlItem(renderCheckBox('hideYAxis', 'Hide Entire Y-axis'))}
          {wrapInControlItem(renderCheckBox('hideYTicks', 'Hide Tick Values'))}
          {wrapInControlItem(renderNexusSelect('yTickSize', [2, 4, 10, 12, 16], 'Tick Size / Length'))}
          {wrapInControlItem(renderNexusInput('Y-label', 'yLabel'))}
          <div className="control-category">Options</div>
          {wrapInControlItem(renderCheckBox('gridlines', 'Show gridlines'))}
          {wrapInControlItem(renderCheckBox('inverse', 'Inverse'))}
          {wrapInControlItem(renderCheckBox('legend', 'Legend'))}
          <div className="control-category">Other axis stuff</div>
          {wrapInControlItem(renderNexusSelect('axisLabelFontSize', [9, 12, 14, 16, 20], 'Axis Label Font Size'))}
          {wrapInControlItem(
            renderNexusSelect(
              'axisTickFontFamily',
              ['interstate', 'sans-serif', 'serif', 'monospace'],
              'Axis Label Font Family'
            )
          )}
          {wrapInControlItem(renderNexusSelect('axisTickFontSize', [8, 9, 10, 12], 'Axis Tick Font Size'))}
          <div className="control-category">Bar Chart stuff</div>
          {wrapInControlItem(renderNexusSelect('barStrokeWidth', [0, 1, 2, 50], 'Bar Stroke Width'))}
          {wrapInControlItem(renderNexusSelect('maxBarWidth', [5, 25, 50, 75, 'fillSpace'], 'Max bar width'))}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'barStroke',
              [
                { label: 'Black', value: '#000000' },
                { label: 'White', value: '#fff' },
                { label: 'Gray', value: '#999999' }
              ],
              'Bar Stroke'
            )
          )}
          <div className="control-category">Color Scheme</div>
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'colorScheme',
              [
                { label: 'Category 10', value: 'category10' },
                { label: 'accent', value: 'Accent' },
                { label: 'Paired', value: 'paired' },
                { label: 'Set 1', value: 'set1' },
                { label: 'Set 2', value: 'set2' },
                { label: 'Set 3', value: 'set3' },
                { label: 'Black', value: 'black' }
              ],
              'Bar Stroke'
            )
          )}
          <div className="control-category">Orientation</div>
          {wrapInControlItem(renderNexusSelect('orientation', ['vertical', 'horizontal'], 'Orientation'))}
          <div className="control-category">Margin</div>
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginBottom',
              [
                { label: '25px', value: '25' },
                { label: '50px', value: '50' },
                { label: '75px', value: '75' }
              ],
              'Margin bottom'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginTop',
              [
                { label: '25px', value: '25' },
                { label: '50px', value: '50' },
                { label: '75px', value: '75' }
              ],
              'Margin top'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginLeft',
              [
                { label: '25px', value: '25' },
                { label: '50px', value: '50' },
                { label: '75px', value: '75' }
              ],
              'Margin left'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginRight',
              [
                { label: '25px', value: '25' },
                { label: '50px', value: '50' },
                { label: '75px', value: '75' }
              ],
              'Margin right'
            )
          )}
        </div>
        {renderChart()}
      </div>
    </>
  );
};

export default App;
