// ui-nexus-design-system/playbook/angular/src/app/sb/components/progress-bar/03_reports.component.ts
import { Component } from '@angular/core';
import { progressBarReport } from '../../constants';

@Component({
  selector: 'app-progress-bar-reports',
  templateUrl: './03_reports.component.html'
})
export default class ProgressBarPerfReportComponent {
  indeterminate = false;

  progressBarReport = progressBarReport;
}

<nexus-card [clickable]="false">
    <nexus-card-header>
        <nexus-card-header-title>{{progressBarReport.cardHeader}}</nexus-card-header-title>
    </nexus-card-header>
    <nexus-card-body>
        <div class="nexus-row">
            <div class="nexus-col-md-2">
                <h3 class="nexus-h5">{{progressBarReport.processor}}</h3>
            </div>
            <div class="nexus-col-md-1">
                <nexus-progress-bar [value]="progressBarReport.processorvalue" circle="true">
                <div class="nexus-pl-3 nexus-pt-4">{{progressBarReport.processorvalue}}%</div>
                </nexus-progress-bar>
            </div>

            <div class="nexus-col-md-2 nexus-pl-4">
                <h3 class="nexus-h5">{{progressBarReport.memory}}</h3>
            </div>
            <div class="nexus-col-md-1">
                <nexus-progress-bar [value]="progressBarReport.memoryValue" circle="true">
                    <div class="nexus-pl-3 nexus-pt-4">{{progressBarReport.memoryValue}}%</div>
                </nexus-progress-bar>
            </div>
        </div>

        <div class="nexus-row nexus-mt-4">
            <div class="nexus-col-md-2">
                <h3 class="nexus-h5">{{progressBarReport.graphics}}</h3>
            </div>
            <div class="nexus-col-md-1">
                <nexus-progress-bar [value]="progressBarReport.graphicsValue" circle="true">
                    <div class="nexus-pl-3 nexus-pt-4">{{progressBarReport.graphicsValue}}%</div></nexus-progress-bar>
            </div>

            <div class="nexus-col-md-2 nexus-pl-4">
                <h3 class="nexus-h5">{{progressBarReport.primaryHDD}}</h3>
            </div>
            <div class="nexus-col-md-1">
                <nexus-progress-bar [value]="progressBarReport.primaryHDDValue" circle="true">
                    <div class="nexus-pl-3 nexus-pt-4">{{progressBarReport.primaryHDDValue}}%</div>
                </nexus-progress-bar>
            </div>
        </div>
    </nexus-card-body>
</nexus-card>

// ui-nexus-design-system/playbook/react/src/sb/components/progress-bar/03_reports.tsx
import React from 'react';
import { progressBarReport } from '../../constants';
import { NexusCard, NexusCardBody, NexusCardHeader, NexusCardHeaderTitle, NexusProgressBar } from '@nexus/react';

const ProgressBarReportsComponent: React.FC = () => {

    return (

        <NexusCard clickable={false}>
            <NexusCardHeader>
                <NexusCardHeaderTitle>System Performance</NexusCardHeaderTitle>
            </NexusCardHeader>
            <NexusCardBody>

                <div className="nexus-row">
                    <div className="nexus-col-md-2">
                        <h3 className="nexus-h5">{progressBarReport.processor}</h3>
                    </div>
                    <div className="nexus-col-md-1">
                        <NexusProgressBar value={progressBarReport.processorvalue} circle={true}>
                            <div className="nexus-pl-3 nexus-pt-4">{progressBarReport.processorvalue}%</div>
                        </NexusProgressBar>
                    </div>

                    <div className="nexus-col-md-2 nexus-pl-4">
                        <h3 className="nexus-h5">{progressBarReport.memory}</h3>
                    </div>
                    <div className="nexus-col-md-1">
                        <NexusProgressBar value={progressBarReport.memoryValue} circle={true}>
                            <div className="nexus-pl-3 nexus-pt-4">{progressBarReport.memoryValue}%</div>
                        </NexusProgressBar>
                    </div>
                </div>

                <div className="nexus-row nexus-mt-4">
                    <div className="nexus-col-md-2">
                        <h3 className="nexus-h5">{progressBarReport.graphics}</h3>
                    </div>
                    <div className="nexus-col-md-1">
                        <NexusProgressBar value={progressBarReport.graphicsValue} circle={true}>
                            <div className="nexus-pl-3 nexus-pt-4">{progressBarReport.graphicsValue}%</div>
                        </NexusProgressBar>
                    </div>

                    <div className="nexus-col-md-2 nexus-pl-4">
                        <h3 className="nexus-h5">{progressBarReport.primaryHDD}</h3>
                    </div>
                    <div className="nexus-col-md-1">
                        <NexusProgressBar value={progressBarReport.primaryHDDValue} circle={true}>
                            <div className="nexus-pl-3 nexus-pt-4">{progressBarReport.primaryHDDValue}%</div>
                        </NexusProgressBar>
                    </div>
                </div>

            </NexusCardBody>
        </NexusCard>
    );
};

export default ProgressBarReportsComponent;
