// ui-nexus-design-system/playbook/react/src/sb/components/progress-bar/01_progress-bar.tsx
import React from 'react';
import PropTypes from 'prop-types';
import { progressBar } from '../../constants';
import { NexusProgressBar } from '@nexus/react';


const ProgressBarComponent: React.FC = (props) => {
  const { circle = progressBar.circle, error = progressBar.indeterminate, indeterminate = progressBar.indeterminate, value = progressBar.value } = { ...props };

  return (
    <NexusProgressBar circle={circle} error={error} indeterminate={indeterminate} value={value}></NexusProgressBar>
  );
};

ProgressBarComponent.propTypes = {
  circle: PropTypes.bool,
  error: PropTypes.bool,
  indeterminate: PropTypes.bool,
  value: PropTypes.number
};

export default ProgressBarComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/progress-bar/01_progress-bar.component.ts
import { Component, Input } from '@angular/core';
import { progressBar } from '../../constants';

@Component({
  selector: 'app-progress-bar',
  templateUrl: './01_progress-bar.component.html'
})
export default class ProgressBarComponent {
  @Input() value: number = progressBar.value;

  @Input() indeterminate: boolean = progressBar.indeterminate;

  @Input() error: boolean = progressBar.error;

  @Input() circle: boolean = progressBar.circle;
}

<nexus-progress-bar
    [value]="value"
    [indeterminate]="indeterminate"
    [error]="error"
    [circle]="circle">
</nexus-progress-bar>
