// ui-nexus-design-system/playbook/react/src/sb/components/progress-bar/02_infinite.tsx
import React, { useState } from 'react';
import { progressBarETA } from '../../constants';
import { NexusProgressBar } from '@nexus/react';

const ProgressBarEtaComponent: React.FC = () => {
  const [indeterminateState, setIndeterminateState] = useState(false);

  const triggerClickHandler = () => {
    setIndeterminateState(!indeterminateState);
  }

  return (
    <div className="nexus-center-xs nexus-pt-6">
      <div className="nexus-row">
        <div className="nexus-ml-6 nexus-col-md-4 nexus-mt-2">
          <NexusProgressBar indeterminate={indeterminateState} />
        </div>
        <div className="nexus-col-md-3">
          <button className="nexus-btn nexus-btn-large" onClick={() => triggerClickHandler()}>
            {indeterminateState ? progressBarETA.calculatingETA : progressBarETA.checkETA}
          </button>
        </div>
      </div>
    </div>
  );
};

export default ProgressBarEtaComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/progress-bar/02_infinite.component.ts
import { Component } from '@angular/core';
import { progressBarETA } from '../../constants';

@Component({
  selector: 'app-progress-bar-eta',
  templateUrl: './02_infinite.component.html'
})
export default class ProgressBarETAComponent {
  indeterminate = false;

  message = progressBarETA.checkETA;

  triggerClickHandler() {
    this.indeterminate = !this.indeterminate;
    this.message = this.indeterminate ? progressBarETA.calculatingETA : progressBarETA.checkETA;
  }
}

<div class="nexus-row">
    <div class="nexus-ml-6 nexus-col-md-4 nexus-mt-6">
        <nexus-progress-bar [indeterminate]="indeterminate"></nexus-progress-bar>
    </div>
    <div class="nexus-col-md-3 nexus-mt-5">
        <button class="nexus-btn nexus-btn-large" (click)="triggerClickHandler()">
            {{message}}
        </button>
    </div>
</div>
