// ui-nexus-design-system/playbook/angular/src/app/sb/components/toggle/04_types.component.ts
import { Component } from '@angular/core';
import { types } from '../../constants';

@Component({
  selector: 'app-types',
  templateUrl: './04_types.component.html'
})
export default class TypesComponent {
  types = types;
}

<p class="nexus-h6">{{types.default}}</p>
<nexus-toggle data-testid="toggle-default" label-inactive="hide" label-active="show" size="sm"></nexus-toggle>

<p class="nexus-h6">{{types.button}}</p>
<nexus-toggle data-testid="toggle-button" type="button" label-inactive="hide" label-active="show"
    size="sm"></nexus-toggle>

// ui-nexus-design-system/playbook/react/src/sb/components/toggle/04_types.tsx
import React from 'react';
import { types } from '../../constants';

import { NexusToggle } from '@nexus/react';

const TypesComponent: React.FC = () => {
  return (
    <>
      <p className="nexus-h6">{types.default}</p>
      <NexusToggle data-testid="toggle-default" labelInactive="hide" labelActive="show" size="sm"></NexusToggle>

      <p className="nexus-h6">{types.button}</p>
      <NexusToggle data-testid="toggle-button" type="button" labelInactive="hide" labelActive="show" size="sm"></NexusToggle>        </>
  );
};

export default TypesComponent;
