// ui-nexus-design-system/playbook/react/src/sb/components/notification/03_variants.tsx
import React from 'react';
import { notificationVariants } from '../../constants';
import { NexusNotification } from '@nexus/react';

const NotificationVariants: React.FC = () => {
    return (
        <div className='nexus-row'>
            <div className='nexus-col-xs-4'>
                <NexusNotification variant='info'>{notificationVariants.infoMessage}</NexusNotification>
            </div>
            <div className='nexus-col-xs-4'>
                <NexusNotification variant='success'>{notificationVariants.successMessage}</NexusNotification>
            </div>
            <div className='nexus-col-xs-4'>
                <NexusNotification variant='warning'>{notificationVariants.warnMessage}</NexusNotification>
            </div>
            <div className='nexus-col-xs-4'>
                <NexusNotification variant='error'>{notificationVariants.errorMessage}</NexusNotification>
            </div>
        </div>
    );
}


export default NotificationVariants;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/notification/03_variants.component.ts
import { Component } from '@angular/core';
import { notificationVariants } from '../../constants';

@Component({
  selector: 'app-notification-variants',
  templateUrl: './03_variants.component.html'
})
export default class NotificationComponent {
  notificationVariants = notificationVariants;
}

<div class="nexus-row nexus-around-xs">
    <div class="nexus-col-xs-1">
        <div class="nexus-row nexus-mt-2">
            <div class="nexus-col-xs-4">
                <nexus-notification data-testid="notification-info" variant="info">{{
                    notificationVariants.infoMessage}}</nexus-notification>
            </div>
            <div class="nexus-col-xs-4">
                <nexus-notification data-testid="notification-info" variant="success">{{
                    notificationVariants.successMessage}}</nexus-notification>
            </div>
            <div class="nexus-col-xs-4">
                <nexus-notification data-testid="notification-info" variant="warning">{{
                    notificationVariants.warnMessage}}</nexus-notification>
            </div>
            <div class="nexus-col-xs-4">
                <nexus-notification data-testid="notification-info" variant="error">{{
                    notificationVariants.errorMessage}}</nexus-notification>
            </div>
        </div>
    </div>
</div>
