// ui-nexus-design-system/playbook/angular/src/app/sb/components/stepper/02_status.component.ts
import { Component, Input } from '@angular/core';
import { StepperStatus } from '../../constants';

@Component({
  selector: 'app-stepper-status',
  templateUrl: './02_status.component.html'
})
export default class StepperStatusComponent {
  StepperStatus = StepperStatus;
}

<div class="nexus-center-xs nexus-pt-3 nexus-pl-6">
    <nexus-stepper>
        <nexus-stepper-item status="complete">
            <button aria-label="step1">{{StepperStatus.createJourney}}</button>
        </nexus-stepper-item>
        <nexus-stepper-item status="complete">
            <button aria-current="step">{{StepperStatus.addJourneyStep}}</button>
        </nexus-stepper-item>
        <nexus-stepper-item status="active">
            <a aria-label="step3">{{StepperStatus.linkToJourneyStep}}</a>
        </nexus-stepper-item>
        <nexus-stepper-item status="error">
            <button aria-label="step4">{{StepperStatus.bindActionsToActivity}}</button>
        </nexus-stepper-item>
        <nexus-stepper-item status="default">
            <button aria-label="step5">{{StepperStatus.activate}}</button>
        </nexus-stepper-item>
    </nexus-stepper>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/stepper/02_status.tsx
import React from 'react';
import { NexusStepper, NexusStepperItem } from '@nexus/react';
import { StepperStatus } from '../../constants';
import { Link } from 'react-router-dom';

const StepperItemStatusComponent: React.FC = () => {
  return (
    <div className="nexus-center-xs nexus-pt-3 nexus-ml-6">
      <NexusStepper>
        <NexusStepperItem status="complete">
          <button aria-label="step1">{StepperStatus.createJourney}</button>
        </NexusStepperItem>
        <NexusStepperItem status="complete">
          <button aria-current="step">{StepperStatus.addJourneyStep}</button>
        </NexusStepperItem>
        <NexusStepperItem status="active">
        <button aria-label="step4">{StepperStatus.linkToJourneyStep}</button>
        </NexusStepperItem>
        <NexusStepperItem status="error">
          <Link to="#" className='nexus-btn nexus-btn-icon'>{StepperStatus.bindActionsToActivity}</Link>
        </NexusStepperItem>
        <NexusStepperItem status="default">
          <button aria-label="step5">{StepperStatus.activate}</button>
        </NexusStepperItem>
      </NexusStepper>
    </div>
  );
};
export default StepperItemStatusComponent;
