// ui-nexus-design-system/playbook/angular/src/app/sb/components/pin-entry/01_pin-entry.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-pin-entry',
  templateUrl: './01_pin-entry.component.html'
})
export default class PinEntryComponent {
  @Input() length: number = 3;

  @Input() disabled: boolean;

  @Input() type: string;
}

<div class="nexus-center-xs nexus-mt-5">
    <nexus-pin-entry data-testid="pin-entry" [length]="length" [disabled]="disabled" [type]="type">
    </nexus-pin-entry>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/pin-entry/01_pin-entry.tsx
import React from 'react';
import PropTypes from 'prop-types';
import { NexusPinEntry } from '@nexus/react';


const PinEntryComponent: React.FC = (props) => (
  <div className='nexus-center-xs nexus-mt-5'>
    <NexusPinEntry {...props} data-testid="pin-entry"></NexusPinEntry>
  </div>
);

PinEntryComponent.propTypes = {
  length: PropTypes.number,
  disabled: PropTypes.bool,
  type: PropTypes.string
};

export default PinEntryComponent;
