// ui-nexus-design-system/playbook/angular/src/app/sb/components/pin-entry/03_withCustomLength.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-pin-entry-with-custom-length',
  templateUrl: './03_withCustomLength.component.html'
})
export default class WithCustomLengthComponent {
}

<div class="nexus-center-xs nexus-mt-5">
    <nexus-pin-entry data-testid="pin-entry" length=6 type='tel'>
    </nexus-pin-entry>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/pin-entry/03_withCustomLength.tsx
import React from "react";
import { NexusPinEntry } from "@nexus/react";

const WithCustomLengthComponent: React.FC = () => {
    return(
        <div className="nexus-center-xs nexus-mt-5">
            <NexusPinEntry type='tel' length={6}></NexusPinEntry>
        </div>
    )
}

export default WithCustomLengthComponent;
