// ui-nexus-design-system/playbook/angular/src/app/sb/components/input/04_withPassword.component.ts
import { Component } from '@angular/core';
import { withPassword } from '../../constants';
@Component({
  selector: 'app-input-examples-password',
  templateUrl: './04_withPassword.component.html'
})
export default class InputPasswordComponent {
  text = withPassword.text;

  placeholder = withPassword.placeholder;
}

<nexus-label data-testid="label-pwd-field">{{ text }}</nexus-label>
<nexus-input data-testid="input-textbox-pwd" type="password" [placeholder]="placeholder"></nexus-input>

// ui-nexus-design-system/playbook/react/src/sb/components/input/04_withPassword.tsx
import { NexusFormField, NexusLabel, NexusInput } from '@nexus/react';
import { withPassword } from '../../constants';
const withPasswordComponent: React.FC = () => {
  return (
    <NexusFormField>
      <NexusLabel>{withPassword.text}</NexusLabel>
      <NexusInput
        data-testid="input-textbox-readonly"
        type="password"
        placeholder={withPassword.placeholder}
      ></NexusInput>
    </NexusFormField>
  );
};

export default withPasswordComponent;
