// ui-nexus-design-system/playbook/angular/src/app/sb/components/input/05_withDate.component.ts
import { Component } from '@angular/core';
import { withDate } from '../../constants';
@Component({
  selector: 'app-input-examples-date',
  templateUrl: './05_withDate.component.html'
})
export default class InputDateComponent {
  text = withDate.text;

  min = withDate.min;

  max = withDate.max;

  placeholder = withDate.placeholder;
}

<nexus-label data-testid="label-date-field">Date Field Example (Min 2022-01-01 and Max 2026-01-01)</nexus-label>
<nexus-input
  data-testid="input-textbox-date"
  type="date"
  [min]="min"
  [max]="max"
  [placeholder]="placeholder"
></nexus-input>

// ui-nexus-design-system/playbook/react/src/sb/components/input/05_withDate.tsx
import React from 'react';
import { NexusFormField, NexusInput, NexusLabel } from '@nexus/react';
import { withDate } from '../../constants';
const DateRangeInputComponent: React.FC = () => {
  return (
    <NexusFormField>
      <NexusLabel data-testid="label-first-name">{withDate.text}</NexusLabel>
      <NexusInput
        data-testid="input-textbox-date"
        type="date"
        min={withDate.min}
        max={withDate.max}
        placeholder={withDate.placeholder}
      ></NexusInput>
    </NexusFormField>
  );
};

export default DateRangeInputComponent;
