// ui-nexus-design-system/playbook/react/src/sb/components/pagination/01_pagination.tsx
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { NexusPagination } from '@nexus/react';
import { NexusPaginationCustomEvent } from '@nexus/core';
import { pagination } from '../../constants';


const PaginationComponent: React.FC = (props) => {
  const { current = pagination.current, max = pagination.max } = { ...props };
  const [currentPage, setCurrentPage] = useState(current);

  return (
    <>
      <NexusPagination
        data-testid="nexus-pagination"
        current={currentPage}
        max={max}
        onChangeEvent={(event: NexusPaginationCustomEvent<any>) => setCurrentPage(event.detail)}
      ></NexusPagination>
    </>
  );
};

PaginationComponent.propTypes = {
  current: PropTypes.number,
  max: PropTypes.number
};

export default PaginationComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/pagination/01_pagination.component.ts
import { Component, Input } from '@angular/core';
import { pagination } from '../../constants';

@Component({
  selector: 'app-pagination',
  templateUrl: './01_pagination.component.html'
})
export default class PaginationComponent {
  @Input() current: number = pagination.current;

  @Input() max: number = pagination.max;

  handleChange(event) {
    this.current = event.detail;
  }
}

<nexus-pagination data-testid="nexus-pagination" [current]="current" [max]="max"
    (changeEvent)="handleChange($event)"></nexus-pagination>
