// ui-nexus-design-system/playbook/react/src/sb/components/select/01_select.tsx
import React, { useState } from 'react';
import { NexusSelect, NexusFormField, NexusLabel } from '@nexus/react';


interface SelectComponentProps {
    delimiter: string;
    disabled: boolean;
    multiple: boolean;
    placeholder: string;
    required: boolean;
    type: 'native' | 'custom';
    value: string;
}

const SelectComponent: React.FC<SelectComponentProps> = (props) => {
    const { disabled, delimiter, multiple, placeholder, required, type, value } = { ...props };
    const [valueInfo, setValueInfo] = useState(value);

    return (
        <div>
            <NexusFormField>
                <NexusLabel>Select an option Native</NexusLabel>
                <NexusSelect
                    disabled={disabled}
                    delimiter={delimiter}
                    multiple={multiple}
                    placeholder={placeholder}
                    required={required}
                    type={type}
                    data-testid="select"
                    value={valueInfo}
                    onInput={(event: any) => setValueInfo(event.target.value)}
                >
                    <option data-testid="select-pls-sel" disabled selected value={value}>
                        Please Select
                    </option>
                    <option data-testid="select-opt1" value="option1">
                        Option 1
                    </option>
                    <option data-testid="select-opt2" value="option2">
                        Option 2
                    </option>
                    <option data-testid="select-opt3" value="option3">
                        Option 3
                    </option>
                </NexusSelect>
            </NexusFormField>
        </div>
    );
};

SelectComponent.defaultProps = {
    delimiter: '',
    disabled: false,
    multiple: false,
    placeholder: 'Please Select',
    required: false,
    type: 'native',
    value: 'Please Select'
};

export default SelectComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/select/01_select.component.ts
import { Component, Input } from '@angular/core';
import { FormControl, Validators } from '@angular/forms';
import { selectNative } from '../../constants';

@Component({
  selector: 'app-select',
  templateUrl: './01_select.component.html'
})
export default class SelectComponent {
  @Input() delimiter = ',';

  @Input() disabled = false;

  @Input() multiple = false;

  @Input() required = false;

  @Input() type = 'native';

  @Input() placeholder = 'Please Select';

  reactiveValue = new FormControl('', Validators.required);

  options = selectNative;

  handleChange(event) {
    this.reactiveValue.setValue(event.target.value);
  }
}

<nexus-form-field>
    <nexus-label>Select an option Native</nexus-label>
    <nexus-select data-testid="select" ngDefaultControl [formControl]="reactiveValue" [value]="reactiveValue.value"
        [delimiter]="delimiter" [disabled]="disabled" [multiple]="multiple" [required]="required" [type]="type" [placeholder]="placeholder">
        <option disabled selected value>Please Select</option>
        <option value="option1">Option 1</option>
        <option value="option2">Option 2</option>
        <option value="option3">Option 3</option>
    </nexus-select>
</nexus-form-field>
