// ui-nexus-design-system/playbook/angular/src/app/sb/components/search/02_filterTable.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { filterTableConstants } from '../../constants';

@Component({
  selector: 'app-search-examples',
  templateUrl: './02_filterTable.component.html'
})
export default class FilterTableComponent implements OnInit {
  debounce: any;

  columnDefs: any = filterTableConstants.colDefs;

  rowData: any = filterTableConstants.rowData;


  Items: any = [];

  filteredItem: any = [];

  rowDataNew: any = [];

  showHideDrawer = false;

  filteredRowData = filterTableConstants.rowData;

  filterTableData = filterTableConstants;

  ngOnInit(): void {
    this.Items.push('Nissan');
    this.Items.push('Tesla');
    this.Items.push('Toyota');
    this.filteredItem = this.Items;
  }

  performFilter(event: any) {
    clearTimeout(this.debounce);
    this.debounce = setTimeout(() => {
      const filterBy = event.target.value.toLocaleLowerCase();
      this.filteredItem = this.Items.filter((item: any) => item.toLocaleLowerCase().indexOf(filterBy) !== -1);
      if (!filterBy) {
        this.filteredRowData = this.rowData;
      }
    }, 500);
  }

  toggleDrawer() {
    this.showHideDrawer = !this.showHideDrawer;
  }

  setFilteredItemOnClickHandler = (item) => {
    this.filteredItem = [item];
    this.filteredRowData = [...this.rowData.filter((data) => data.make === item)];
  };
}

<nexus-search data-testid="search-bar" [debounceInterval]="3000">
  <nexus-input (input)="performFilter($event)" autocomplete="off" [placeholder]="filterTableData.placeholder" >
      <nexus-icon data-testid="search-icon" [src]="filterTableData.searchIconSrc"></nexus-icon>
    </nexus-input>
    <nexus-search-list>
      <nexus-search-list-item *ngFor="let item of filteredItem" (click)="setFilteredItemOnClickHandler(item)">
        <button>{{ item }}</button>
      </nexus-search-list-item>
    </nexus-search-list>
  </nexus-search>

  <table class="nexus-table">
    <thead>
      <tr>
        <th *ngFor="let cols of columnDefs">{{cols.label}}</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let tableContent of filteredRowData">
        <td>{{tableContent.make}}</td>
        <td>{{tableContent.model}}</td>
        <td>{{tableContent.year}}</td>
        <td>{{tableContent.price}}</td>
        <td>{{tableContent.owner}}</td>
        <td>{{tableContent.location}}</td>
      </tr>
    </tbody>
  </table>

// ui-nexus-design-system/playbook/react/src/sb/components/search/02_filterTable.tsx
import { NexusIcon, NexusInput, NexusSearch, NexusSearchList, NexusSearchListItem } from "@nexus/react";
import React, { useEffect, useState } from "react";
import { filterTableConstants } from "../../constants";

const FilterTable: React.FC = () => {
    const [tableData, setTableData] = useState(filterTableConstants.rowData);
    const items = Array.from(new Set(filterTableConstants.rowData.map(records => records.make)));
    const [filtereditem, setFiltereditem] = useState(items);


    const filterTable = (event: any) => {
        const filterItemList = items.filter((item) => item.toLowerCase().includes(event.target.value));
        setFiltereditem(filterItemList);
    }

    const Performfilter = (e: any) => {
        const keyword = e.target.value;

        if (keyword !== '') {
          const results = items.filter((item) => item.toLowerCase().includes(keyword.toLowerCase()));
          setFiltereditem(results);
        } else {
          setFiltereditem([...items]);
        }
      };

    useEffect(() => {
        if(filtereditem.length === 1) {
            const data = filterTableConstants.rowData.filter((makes) => makes.make.toLowerCase() === filtereditem[0].toLowerCase())
            if(data.length === 0) {
                setTableData(filterTableConstants.rowData)
            }
            else {
                setTableData(data);
            }

        }
    }, [filtereditem]);

    return (
        <div>
            <NexusSearch>
                <NexusInput data-testid="search-bar" onKeyUp={Performfilter} onInput={(event) => filterTable(event)} autocomplete="off" placeholder={filterTableConstants.placeholder}>
                    <NexusIcon data-testid="search-icon" src={filterTableConstants.searchIconSrc}></NexusIcon>
                </NexusInput>
                <NexusSearchList>
                    <div>
                        {filtereditem.length > 0 && (
                            <div>
                                {filtereditem.map((item) => (
                                    <NexusSearchListItem data-testid="search-list" key={item} onClick={() => setFiltereditem([item])}>
                                        <button>{item}</button>
                                    </NexusSearchListItem>
                                ))}
                            </div>
                        )}
                    </div>
                </NexusSearchList>
            </NexusSearch>

            <table className="nexus-table">
                <thead>
                    <tr>
                        {filterTableConstants.colDefs.map((labels) => <th key={labels.field}>{labels.field}</th>)}
                    </tr>
                </thead>
                <tbody>
                    {
                        tableData.map((records, idx) => <tr key={idx}>
                            <td>{records.make}</td>
                            <td>{records.model}</td>
                            <td>{records.year}</td>
                            <td>{records.owner}</td>
                            <td>{records.location}</td>
                            <td>{records.price}</td>
                        </tr>)
                    }
                </tbody>
            </table>
        </div>
    )
}

export default FilterTable;
