// ui-nexus-design-system/playbook/angular/src/app/sb/components/dropdown/02_withButton.component.ts
import { Component } from '@angular/core';
import { withButton } from '../../constants';
@Component({
  selector: 'app-dropdown-button',
  templateUrl: './02_withButton.component.html'
})
export default class WithButtonComponent {
  primaryOptions = withButton.primaryOptions;

  secondaryOptions = withButton.secondaryOptions;

  add = withButton.add;

  delete = withButton.delete;

  block = withButton.block;

  save = withButton.save;

  load = withButton.load;

  edit = withButton.edit;
}

<div class="nexus-container">
  <nexus-form-field class="nexus-flex-row">
    <button class="nexus-btn-primary nexus-col-xs-2">
      <nexus-select type="basic" value="">
        <option value="" disabled selected>
          {{ primaryOptions }}
        </option>
        <option value="option1">{{ add }}</option>
        <option value="option2" disabled selected>{{ delete }}</option>
        <option value="option3">{{ block }}</option>
      </nexus-select>
    </button>
    <button class="nexus-btn-warn nexus-col-xs-2">
      <nexus-select type="basic" value="">
        <option value="" disabled selected>{{ secondaryOptions }}</option>
        <option value="option1">{{ save }}</option>
        <option value="option2">{{ load }}</option>
        <option value="option3" disabled selected>{{ edit }}</option>
      </nexus-select>
    </button>
  </nexus-form-field>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/dropdown/02_withButton.tsx
import React from 'react';
import { NexusFormField, NexusSelect } from '@nexus/react';
import { withButton } from '../../constants';

const DropdownWithButtonComponent: React.FC = (props) => {
  const { type = 'native' } = { ...props };
  return (
    <>
      <div className="nexus-container">
        <NexusFormField className="nexus-flex-row">
          <button className="nexus-btn-primary nexus-col-xs-2">
            <NexusSelect type={type} value="">
              <option value="" disabled selected>
                {withButton.primaryOptions}
              </option>
              <option value="Option1">{withButton.add}</option>
              <option value="Option2" disabled selected>
                {withButton.delete}
              </option>
              <option value="Option3">{withButton.block}</option>
            </NexusSelect>
          </button>
          <button className="nexus-btn-warn nexus-col-xs-2">
            <NexusSelect type={type} value="">
              <option value="" disabled selected>
                {withButton.primaryOptions}
              </option>
              <option value="Option1">{withButton.save}</option>
              <option value="Option2" disabled selected>
                {withButton.load}
              </option>
              <option value="Option3">{withButton.edit}</option>
            </NexusSelect>
          </button>
        </NexusFormField>
      </div>
    </>
  );
};

export default DropdownWithButtonComponent;
