// ui-nexus-design-system/playbook/angular/src/app/sb/components/dropdown/03_withSelect.component.ts
import { Component } from '@angular/core';
import { withSelect } from '../../constants';
@Component({
  selector: 'app-dropdown-examples-select',
  templateUrl: './03_withSelect.component.html'
})
export default class WithSelectComponent {
  src = withSelect.src;

  text = withSelect.text;

  option1 = withSelect.option1;

  option2 = withSelect.option2;

  option3 = withSelect.option3;

  handleCloseEvent = (_event) => {};
}

<p>
  {{ text }}
  <nexus-dropdown dropdown-type="basic" placement="right" height="150" width="180">
    <nexus-icon slot="trigerelement" [src]="src"></nexus-icon>
    <nexus-option label="Option 1" value="Option1">{{ option1 }}</nexus-option>
    <nexus-option label="Option 2" value="Option2">{{ option2 }}</nexus-option>
    <nexus-option label="Option 3" value="Option3">{{ option3 }}</nexus-option>
  </nexus-dropdown>
</p>

<p>
  {{ text }}
  <nexus-dropdown dropdown-type="basic" placement="left" height="150" width="180">
    <nexus-icon slot="trigerelement" [src]="src"></nexus-icon>
    <nexus-option label="Option 1" value="Option1">{{ option1 }}</nexus-option>
    <nexus-option label="Option 2" value="Option2">{{ option2 }}</nexus-option>
    <nexus-option label="Option 3" value="Option3">{{ option3 }}</nexus-option>
  </nexus-dropdown>
</p>

<p>
  {{ text }}
  <nexus-dropdown dropdown-type="basic" placement="center" height="150" width="180">
    <nexus-icon slot="trigerelement" [src]="src"></nexus-icon>
    <nexus-option label="Option 1" value="Option1">{{ option1 }}</nexus-option>
    <nexus-option label="Option 2" value="Option2">{{ option2 }}</nexus-option>
    <nexus-option label="Option 3" value="Option3">{{ option3 }}</nexus-option>
  </nexus-dropdown>
</p>

// ui-nexus-design-system/playbook/react/src/sb/components/dropdown/03_withSelect.tsx
import { NexusDropdown, NexusIcon, NexusOption } from '@nexus/react';
import { withSelect } from '../../constants';

const DropdownExampleComponent: React.FC = () => {
  return (
    <>
      <p>
        {withSelect.text}
        <NexusDropdown placement={'right'} dropdown-type={'basic'} height={150} width={180}>
          <NexusIcon slot={'trigerelement'} id={'iconId'} src={withSelect.src}></NexusIcon>
          <NexusOption>{withSelect.option1}</NexusOption>
          <NexusOption>{withSelect.option2}</NexusOption>
          <NexusOption>{withSelect.option3}</NexusOption>
        </NexusDropdown>
      </p>

      <p>
        {withSelect.text}
        <NexusDropdown placement={'left'} dropdown-type={'basic'} height={150} width={180}>
          <NexusIcon slot={'trigerelement'} id={'iconId'} src={withSelect.src}></NexusIcon>
          <NexusOption label="Option 1" value="Option1">
            {withSelect.option1}
          </NexusOption>
          <NexusOption label="Option 2" value="Option2">
            {withSelect.option2}
          </NexusOption>
          <NexusOption label="Option 3" value="Option3">
            {withSelect.option3}
          </NexusOption>
        </NexusDropdown>
      </p>

      <p>
        {withSelect.text}
        <NexusDropdown placement={'center'} dropdown-type={'basic'} height={150} width={180}>
          <NexusIcon slot={'trigerelement'} id={'iconId'} src={withSelect.src}></NexusIcon>
          <NexusOption label="Option 1" value="Option1">
            {withSelect.option1}
          </NexusOption>
          <NexusOption label="Option 2" value="Option2">
            {withSelect.option2}
          </NexusOption>
          <NexusOption label="Option 3" value="Option3">
            {withSelect.option3}
          </NexusOption>
        </NexusDropdown>
      </p>
    </>
  );
};
export default DropdownExampleComponent;
