// ui-nexus-design-system/playbook/angular/src/app/components/notification/notification.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-notification',
  templateUrl: './notification.component.html',
  styleUrls: ['./notification.component.scss']
})
export class NotificationComponent {
  @Input() variant: string = 'info';

  message: string = 'Informational notification message';
}

<div class="nexus-rhythm-4">
  <nexus-notification data-testid="notification-info" [variant]="variant">{{ message }}</nexus-notification>
</div>

<div class="nexus-rhythm-4">
  <nexus-notification data-testid="notification-error" variant="error">Error notification message.</nexus-notification>
</div>

<div class="nexus-rhythm-4">
  <nexus-notification data-testid="notification-success" variant="success"
    >Success notification message.</nexus-notification
  >
</div>

<div class="nexus-rhythm-4">
  <nexus-notification data-testid="notification-warning" variant="warning"
    >Warning notification message.</nexus-notification
  >
</div>

// ui-nexus-design-system/playbook/react/src/components/notification/notification.tsx
import React from 'react';
import { NexusNotification } from '@nexus/react';

interface NotificationComponentProps {
  variant: 'info' | 'error' | 'warning' | 'success';
  message: string;
}

const NotificationComponent: React.FC<NotificationComponentProps> = (props) => (
  <>
    <div className="nexus-rhythm-4">
      <NexusNotification data-testid="informational-notification-message" {...props}>
        {props.message}
      </NexusNotification>
    </div>

    <div className="nexus-rhythm-4">
      <NexusNotification data-testid="error-notification-message" variant="error">
        Error notification message.
      </NexusNotification>
    </div>

    <div className="nexus-rhythm-4">
      <NexusNotification data-testid="success-notification-message" variant="success">
        Success notification message.
      </NexusNotification>
    </div>

    <div className="nexus-rhythm-4">
      <NexusNotification data-testid="warning-notification-message" variant="warning">
        Warning notification message.
      </NexusNotification>
    </div>
  </>
);

NotificationComponent.defaultProps = {
  variant: 'info',
  message: 'Informational notification message.'
};

export default NotificationComponent;
