// ui-nexus-design-system/playbook/react/src/components/radio/radio.tsx
import React, { useState } from 'react';

import { NexusRadio } from '@nexus/react';

interface RadioComponentProps {
  disabled: boolean;
  name: string;
  required: boolean;
  value: string;
}

const RadioComponent: React.FC<RadioComponentProps> = (props) => {
  const { disabled, name, required, value } = { ...props };
  const [radioButtonValue, setRadioButtonValue] = useState(value);

  return (
    <>
      <div>
        <NexusRadio
          disabled={disabled}
          data-testid="radio-btn-opt1"
          checked={radioButtonValue === 'option1'}
          name={name}
          required={required}
          onInput={(event: any) => setRadioButtonValue(event.target.value)}
        >
          Option 1
        </NexusRadio>

        <NexusRadio
          disabled={disabled}
          name={name}
          required={required}
          data-testid="radio-btn-opt2"
          checked={radioButtonValue === 'option2'}
          onInput={(event: any) => setRadioButtonValue(event.target.value)}
        >
          Option 2
        </NexusRadio>
      </div>
    </>
  );
};

RadioComponent.defaultProps = {
  disabled: false,
  name: 'mainGroup',
  required: false,
  value: ''
};

export default RadioComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/radio/radio.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-radio',
  templateUrl: './radio.component.html',
  styleUrls: ['./radio.component.scss']
})
export class RadioComponent {
  @Input() disabled: boolean;

  @Input() label: string;

  @Input() required: boolean;
}

<nexus-radio data-testid="radio-btn-opt1" name="group1" [disabled]="disabled" [label]="label" [required]="required"
  >Option 1</nexus-radio
>
<nexus-radio data-testid="radio-btn-opt2" name="group1" [disabled]="disabled" [label]="label" [required]="required"
  >Option 2</nexus-radio
>
