// ui-nexus-design-system/playbook/react/src/sb/components/tab-bar/02_withCustomContent.tsx
import React, { useState } from 'react';
import { tabBarCustomContent } from '../../../../../stories/data/tab-bar';
import { NexusTabBar } from '@nexus/react';

const WithCustomContentComponent: React.FC = () => {
  const [newtabOption, setnewtabOption] = useState(tabBarCustomContent);

  const ChangeActive = (index: number) => {
    const selectedTab = [...tabBarCustomContent];

    selectedTab.forEach((option) => {
      option.isActive = false;
    });
    selectedTab[index].isActive = true;
    setnewtabOption(selectedTab);
  };
  return (
    <div>
      <NexusTabBar>
        <span>
          {newtabOption.map((option, index) =>
            option.isActive ? (
              <button
                data-testid="tab-bar-active"
                key={index} className="nexus-link nexus-active" onClick={(_event) => ChangeActive(index)}>
                {option.title}
              </button>
            ) : (
              <button
                data-testid="tab-bar"
                key={index} className="nexus-link" onClick={(_event) => ChangeActive(index)}>
                {option.title}
              </button>
            )
          )}
        </span>
      </NexusTabBar>
      <div>
        {newtabOption.map(
          (option, index) =>
            option.isActive && (
              <div
                data-testid="tab-bar-selected-label"
                dangerouslySetInnerHTML={{ __html: option.value }}
                key={index} style={{ margin: '20px' }} />
            )
        )}
      </div>
    </div>
  );
};

export default WithCustomContentComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/tab-bar/02_withCustomContent.component.ts
import { Component } from '@angular/core';
import { tabBarCustomContent } from '../../constants';

@Component({
  selector: 'app-tab-bar-custom-content',
  templateUrl: './02_withCustomContent.component.html'
})
export default class WithCustomContentComponent {
  tabOption = tabBarCustomContent;

  ChangeActive(index: number) {
    this.tabOption.forEach((item) => {
      item.isActive = false;
    });
    this.tabOption[index].isActive = true;
  }
}

<nexus-tab-bar>
    <span>
        <button (click)="ChangeActive(i)" [ngClass]="option.isActive == true ? 'nexus-link nexus-active' : 'nexus-link'"
            *ngFor="let option of tabOption; let i = index"><a>{{ option.title }}</a></button>
    </span>
</nexus-tab-bar>

<div style="margin: 20px" *ngFor="let option of tabOption">
    <div *ngIf="option.isActive" [innerHTML]="option.value"></div>
</div>
