// ui-nexus-design-system/playbook/react/src/components/line-chart/line-chart.tsx
import React, { useEffect, useRef, useState } from 'react';
import { NexusLineChart, NexusCheckbox, NexusInput, NexusLabel, NexusSelect } from '@nexus/react';
import './line-chart';
import { JSX } from '@nexus/core';

const dat = new Date(1546318800000);

const msd = 86400000;

const data: Array<any> = [
  {
    label: 'User 1',
    name: 'Mark',
    data: [
      {
        x: dat.getTime() + msd * 10,
        y: 71
      },
      {
        x: dat.getTime() + msd * 20,
        y: 251
      },
      {
        x: dat.getTime() + msd * 30,
        y: 357
      },
      {
        x: dat.getTime() + msd * 40,
        y: 414
      },
      {
        x: dat.getTime() + msd * 50,
        y: 270
      },
      {
        x: dat.getTime() + msd * 60,
        y: 33
      }
    ]
  },
  {
    label: 'User 2',
    name: 'Fred',
    data: [
      {
        x: dat.getTime() + msd * 10,
        y: 418
      },
      {
        x: dat.getTime() + msd * 20,
        y: 380
      },
      {
        x: dat.getTime() + msd * 30,
        y: 393
      },
      {
        x: dat.getTime() + msd * 40,
        y: 107
      },
      {
        x: dat.getTime() + msd * 50,
        y: 3
      },
      {
        x: dat.getTime() + msd * 60,
        y: 333
      }
    ]
  },
  {
    label: 'User 3',
    name: 'Diane',
    data: [
      {
        x: dat.getTime() + msd * 10,
        y: 473
      },
      {
        x: dat.getTime() + msd * 20,
        y: 311
      },
      {
        x: dat.getTime() + msd * 30,
        y: 405
      },
      {
        x: dat.getTime() + msd * 40,
        y: 65
      },
      {
        x: dat.getTime() + msd * 50,
        y: 101
      },
      {
        x: dat.getTime() + msd * 60,
        y: 18
      }
    ]
  },
  {
    label: 'User 4',
    name: 'Jackie',
    data: [
      {
        x: dat.getTime() + msd * 10,
        y: 56
      },
      {
        x: dat.getTime() + msd * 20,
        y: -7
      },
      {
        x: dat.getTime() + msd * 30,
        y: 68
      },
      {
        x: dat.getTime() + msd * 40,
        y: -137
      },
      {
        x: dat.getTime() + msd * 50,
        y: 208
      },
      {
        x: dat.getTime() + msd * 60,
        y: 470
      }
    ]
  }
];

const initialValue = {
  showXLabel: true,
  showYLabel: true,
  chartData: data,
  chartId: 'NexusLineChart',
  axisLabelFontSize: 14,
  axisTickFontFamily: 'interstate',
  axisTickFontSize: 10,
  canvasHeight: 450,
  canvasWidth: 940,
  colorScheme: 'category10',
  gridlines: false,
  hideXAxis: false,
  hideXTicks: false,
  hideYAxis: false,
  hideYTicks: false,
  interpolation: 'linear',
  inverse: false,
  legend: true,
  legendFontSize: 12,
  legendMetric: 'label',
  legendWidth: 125,
  marginBottom: 25,
  marginLeft: 25,
  marginRight: 25,
  marginTop: 25,
  responsive: true,
  strokeWidth: 2,
  tooltips: true,
  vertices: true,
  xLabel: 'Date',
  xMetric: 'x',
  xTickFormat: 'M/D/YY',
  xTickSize: 2,
  yLabel: 'Score',
  yMetric: 'y',
  yTickFormat: 'localestring',
  yTickSize: 2
};

const App = () => {
  const chartElement = useRef(null);
  const [chartOptions, setChartOptions] = useState<any>(initialValue);
  const updateState = (field: any, target: any) => {
    console.log('target', target);
    let value = '';
    if (target.type === 'checkbox') {
      value = target.checked;
    } else {
      value = target.value;
    }
    setChartOptions({
      ...chartOptions,
      [field]: value
    });
  };

  useEffect(() => {
    console.log(chartOptions);
    if (chartOptions.hideXAxis) {
      chartOptions.hideXAxis = true;
      chartOptions.hideXTicks = true;
    } else {
      chartOptions.hideXAxis = false;
      chartOptions.hideXTicks = false;
    }
    if (chartOptions.hideYAxis) {
      chartOptions.hideYAxis = true;
      chartOptions.hideYTicks = true;
    } else {
      chartOptions.hideYAxis = false;
      chartOptions.hideYTicks = false;
    }
  }, [chartOptions]);

  const selectTopN = (num: number) => {
    setChartOptions({
      ...chartOptions,
      chartData: data.slice(0, num)
    });
  };

  const showHideXLabel = (event: any) => {
    if (event.target.checked) {
      setChartOptions({
        ...chartOptions,
        xLabel: 'Date'
      });
    } else {
      setChartOptions({
        ...chartOptions,
        xLabel: ''
      });
    }
  };
  const showHideYLabel = (event: any) => {
    if (event.target.checked) {
      setChartOptions({
        ...chartOptions,
        yLabel: 'Price'
      });
    } else {
      setChartOptions({
        ...chartOptions,
        yLabel: ''
      });
    }
  };
  interface IOptions {
    label: string;
    value: any;
  }

  /**
   *
   * @param component : Returns the component wrapped in a class for styling purpose
   */
  const wrapInControlItem = (component: React.ReactElement) => (
    <div className='control-item'>{component}</div>
  );
  /**
   *
   * @param field one of NexusLineChart Props
   * @param options options can be of anytype
   * @param label Label to be displayed above
   */
  const renderNexusSelect = (field: keyof JSX.NexusLineChart, options: any[], label: string) => (
    <>
      {' '}
      <NexusLabel className="select">{label}</NexusLabel>
      <NexusSelect value={chartOptions[field]?.toString()} onInput={(e: any) => updateState(field, e.target)}>
        {renderOptions(options)}
      </NexusSelect>
    </>
  );
  /**
   *
   * @param field one of NexusLineChart Props
   * @param options options can be IOptions type
   * @param label Label to be displayed above
   */
  const renderSelctWithCustomOptions = (field: keyof JSX.NexusLineChart, options: IOptions[], label: string) => (
    <>
      {' '}
      <NexusLabel className="select">{label}</NexusLabel>
      <NexusSelect value={chartOptions[field]?.toString()} onInput={(e: any) => updateState(field, e.target)}>
        {renderOptionsWithDifferentValue(options)}
      </NexusSelect>
    </>
  );
  /**
   * Returns <Option> by looping through the array
   * @param options array of any type
   */
  const renderOptions = (options: any[]) =>
    options.map((singleOption) => <option value={singleOption}>{singleOption}</option>);
  const renderOptionsWithDifferentValue = (options: IOptions[]) =>
    options.map((singleOption) => <option value={singleOption.value}>{singleOption.label}</option>);

  /**
   * Returns NexusInput
   * @param label : string, label to be displayed
   * @param field : Props of NexusLineChart component
   */
  const renderNexusInput = (label: string, field: keyof JSX.NexusLineChart) => (
    <>
      <NexusLabel>{label}</NexusLabel>
      <NexusInput
        value={chartOptions[field]?.toString()}
        onInput={(e: any) => updateState(field, e.target)}
      ></NexusInput>
    </>
  );
  /**
   * Returns a NexusCheckBox
   * @param field : Props of NexusLineChart component
   * @param label : string, label to be displayed
   */
  const renderCheckBox = (field: any, label: string) => (
    <NexusCheckbox checked={chartOptions[field] as boolean} onClick={(e: any) => updateState(field, e.target)}>
      {label}
    </NexusCheckbox>
  );

  const selectNumLines = (num: number) => {
    setChartOptions({
      ...chartOptions,
      chartData: data.slice(0, num)
    });
  };

  const generateRandomData = () => {
    setChartOptions({
      ...chartOptions,
      chartData: data.slice(0, Math.floor(Math.random() * 5))
    });
  };

  return (
    <>
      <div id="wrapper" className="nexus-row">
        <div className={`nexus-col-xs-4 nexus-col-lg-3 control-container'`}>
          <div className='control-category'>X-Axis</div>

          <NexusCheckbox checked={chartOptions.showXLabel as boolean} onClick={(e: any) => showHideXLabel(e)}>
            Show Label
          </NexusCheckbox>
          {wrapInControlItem(renderCheckBox('hideXTicks', 'Hide Tick Values'))}
          {wrapInControlItem(renderCheckBox('hideXAxis', 'Hide Entire X-axis'))}
          {wrapInControlItem(renderNexusSelect('xTickSize', [2, 4, 10, 12, 16], 'Tick Size / Length'))}
          {wrapInControlItem(renderNexusInput('Label', 'xLabel'))}
          <div className='control-category'>Y-Axis</div>
          <NexusCheckbox checked={chartOptions.showYLabel as boolean} onClick={(e: any) => showHideYLabel(e)}>
            Show Label
          </NexusCheckbox>
          {wrapInControlItem(renderCheckBox('hideYTicks', 'Hide Tick Values'))}
          {wrapInControlItem(renderCheckBox('hideYAxis', 'Hide Entire Y-axis'))}
          {wrapInControlItem(renderNexusSelect('yTickSize', [2, 4, 10, 12, 16], 'Tick Size / Length'))}
          {wrapInControlItem(renderNexusInput('Label', 'yLabel'))}
          <div className='control-category'>Options</div>
          {wrapInControlItem(renderCheckBox('gridlines', 'Grid Lines'))}
          {wrapInControlItem(renderCheckBox('inverse', 'Inverse'))}
          {wrapInControlItem(renderCheckBox('legend', 'Legend'))}
          {wrapInControlItem(renderCheckBox('vertices', 'Vertices'))}
          {wrapInControlItem(renderNexusSelect('axisLabelFontSize', [9, 12, 14, 16, 20], 'Axis Label Font Size'))}
          {wrapInControlItem(
            renderNexusSelect(
              'axisTickFontFamily',
              ['interstate', 'sans-serif', 'serif', 'monospace'],
              'Axis Label Font Family'
            )
          )}
          {wrapInControlItem(renderNexusSelect('axisTickFontSize', [8, 9, 10, 12], 'Axis Tick Font Size'))}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'colorScheme',
              [
                { label: 'Category 10', value: 'category10' },
                { label: 'accent', value: 'Accent' },
                { label: 'Paired', value: 'paired' },
                { label: 'Set 1', value: 'set1' },
                { label: 'Set 2', value: 'set2' },
                { label: 'Set 3', value: 'set3' },
                { label: 'Black', value: 'black' }
              ],
              'Color Scheme'
            )
          )}
          {wrapInControlItem(renderNexusSelect('legendFontSize', [8, 9, 10, 12, 14, 16], 'Legend Font Size'))}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'interpolation',
              [
                { value: 'linear', label: 'Linear' },
                { value: 'basis', label: 'Basis' },
                { value: 'monotone', label: 'Monotone' },
                { value: 'step', label: 'Step' },
                { value: 'step-before', label: 'Step Before' },
                { value: 'step-after', label: 'Step After' }
              ],
              'Line Interpolation'
            )
          )}
          {wrapInControlItem(renderNexusSelect('strokeWidth', [1, 2, 3, 4], 'Line Stroke'))}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginBottom',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Bottom'
            )
          )}

          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginLeft',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Left'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginRight',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Right'
            )
          )}
          {wrapInControlItem(
            renderSelctWithCustomOptions(
              'marginTop',
              [
                { value: '0', label: '0px' },
                { value: '25', label: '25px' },
                { value: '50', label: '50px' },
                { value: '100', label: '100px' },
                { value: '150', label: '150px' }
              ],
              'Margin Top'
            )
          )}
        </div>
        <div id="chart-container" className={`nexus-col-xs-4 nexus-col-lg-9 chart-container`}>
          <div className='page-title'>&lt;nexus-line-chart&gt;</div>
          <div className='hoz-group'>
            <span className='btn-item'>
              <button type="button" className="nexus-btn" onClick={(e: any) => selectNumLines(1)}>
                1 Line
              </button>
            </span>
            <span className='btn-item'>
              <button type="button" className="nexus-btn" onClick={(e: any) => selectNumLines(2)}>
                2 Lines
              </button>
            </span>
            <span className='btn-item'>
              <button type="button" className="nexus-btn" onClick={(e: any) => selectNumLines(3)}>
                3 Lines
              </button>
            </span>
            <span className='btn-item'>
              <button type="button" className="nexus-btn" onClick={(e: any) => selectNumLines(4)}>
                4 Lines
              </button>
            </span>
            <span className='btn-item'>
              <button type="button" className="nexus-btn" onClick={(e: any) => generateRandomData()}>
                Random
              </button>
            </span>
          </div>
          <div className={chartOptions['inverse'] ? 'chart-inverse' : 'chart'}>
            <NexusLineChart
              axisLabelFontSize={chartOptions.axisLabelFontSize}
              axisTickFontFamily={chartOptions.axisTickFontFamily}
              axisTickFontSize={chartOptions.axisTickFontSize}
              canvasHeight={chartOptions.canvasHeight}
              canvasWidth={chartOptions.canvasWidth}
              chartData={chartOptions.chartData}
              chartId={chartOptions.chartId}
              colorScheme={chartOptions.colorScheme}
              gridlines={chartOptions.gridlines}
              hideXAxis={chartOptions.hideXAxis}
              hideXTicks={chartOptions.hideXTicks}
              hideYAxis={chartOptions.hideYAxis}
              hideYTicks={chartOptions.hideYTicks}
              interpolation={chartOptions.interpolation}
              inverse={chartOptions.inverse}
              legend={chartOptions.legend}
              legendFontSize={chartOptions.legendFontSize}
              legendMetric={chartOptions.legendMetric}
              legendWidth={chartOptions.legendWidth}
              marginBottom={chartOptions.marginBottom}
              marginLeft={chartOptions.marginLeft}
              marginRight={chartOptions.marginRight}
              marginTop={chartOptions.marginTop}
              responsive={chartOptions.responsive}
              strokeWidth={chartOptions.strokeWidth}
              tooltips={chartOptions.tooltips}
              vertices={chartOptions.vertices}
              xLabel={chartOptions.xLabel}
              xMetric={chartOptions.xMetric}
              xTickFormat={chartOptions.xTickFormat}
              xTickSize={chartOptions.xTickSize}
              yLabel={chartOptions.yLabel}
              yMetric={chartOptions.yMetric}
              yTickFormat={chartOptions.yTickFormat}
              yTickSize={chartOptions.yTickSize}
            ></NexusLineChart>
          </div>
        </div>
      </div>
    </>
  );
};

export default App;

// ui-nexus-design-system/playbook/angular/src/app/components/line-chart/line-chart.component.ts
/* eslint-disable max-lines */
/* eslint-disable id-length */

import { Component, OnInit, ElementRef } from '@angular/core';

@Component({
  selector: 'app-line-chart',
  templateUrl: './line-chart.component.html',
  styleUrls: ['./line-chart.component.scss']
})
export class LineChartComponent implements OnInit {
  public gridlines: any;

  public inverse: any;

  public showLegend: any;

  public showPieLegend: any;

  public vertices: any;

  public hideXAxis: any;

  public showXLabel: any;

  public showXTicks: any;

  public showYLabel: any;

  public showYTicks: any;

  public dat = new Date();

  public msd = 86400000;

  public data: Array<any> = [
    {
      label: 'User 1',
      name: 'Mark',
      data: [
        {
          x: this.dat.getTime() + (this.msd * 10),
          y: 71
        },
        {
          x: this.dat.getTime() + (this.msd * 20),
          y: 251
        },
        {
          x: this.dat.getTime() + (this.msd * 30),
          y: 357
        },
        {
          x: this.dat.getTime() + (this.msd * 40),
          y: 414
        },
        {
          x: this.dat.getTime() + (this.msd * 50),
          y: 270
        },
        {
          x: this.dat.getTime() + (this.msd * 60),
          y: 33
        }
      ]
    },
    {
      label: 'User 2',
      name: 'Fred',
      data: [
        {
          x: this.dat.getTime() + (this.msd * 10),
          y: 418
        },
        {
          x: this.dat.getTime() + (this.msd * 20),
          y: 380
        },
        {
          x: this.dat.getTime() + (this.msd * 30),
          y: 393
        },
        {
          x: this.dat.getTime() + (this.msd * 40),
          y: 107
        },
        {
          x: this.dat.getTime() + (this.msd * 50),
          y: 3
        },
        {
          x: this.dat.getTime() + (this.msd * 60),
          y: 333
        }
      ]
    },
    {
      label: 'User 3',
      name: 'Diane',
      data: [
        {
          x: this.dat.getTime() + (this.msd * 10),
          y: 473
        },
        {
          x: this.dat.getTime() + (this.msd * 20),
          y: 311
        },
        {
          x: this.dat.getTime() + (this.msd * 30),
          y: 405
        },
        {
          x: this.dat.getTime() + (this.msd * 40),
          y: 65
        },
        {
          x: this.dat.getTime() + (this.msd * 50),
          y: 101
        },
        {
          x: this.dat.getTime() + (this.msd * 60),
          y: 18
        }
      ]
    },
    {
      label: 'User 4',
      name: 'Jackie',
      data: [
        {
          x: this.dat.getTime() + (this.msd * 10),
          y: 56
        },
        {
          x: this.dat.getTime() + (this.msd * 20),
          y: -7
        },
        {
          x: this.dat.getTime() + (this.msd * 30),
          y: 68
        },
        {
          x: this.dat.getTime() + (this.msd * 40),
          y: -137
        },
        {
          x: this.dat.getTime() + (this.msd * 50),
          y: 208
        },
        {
          x: this.dat.getTime() + (this.msd * 60),
          y: 470
        }
      ]
    }
  ];

  private htmlElement: HTMLElement;

  private hideYAxis: any;

  constructor(public elRef: ElementRef) {
    this.htmlElement = this.elRef.nativeElement;

    this.gridlines = false;
    this.inverse = false;
    this.showLegend = false;
    this.showPieLegend = true;
    this.vertices = true;
    this.hideXAxis = false;
    this.showXLabel = true;
    this.showXTicks = true;
  }

  public changeXLabel(args: any, value: any) {
    this.getChartEl(args).xLabel = value;
    const xLabelInput = this.htmlElement.querySelector('#xLabelInput') as HTMLInputElement;
    xLabelInput.value = '';
  }

  public changeYLabel(args: any, value: any) {
    this.getChartEl(args).yLabel = value;
    const yLabelInput = this.htmlElement.querySelector('#yLabelInput') as HTMLInputElement;
    yLabelInput.value = '';
  }

  public getChartEl(id: any): any {
    return this.htmlElement.querySelector(id);
  }

  public randomizer(): any {
    return Math.floor(Math.random() * 500) - 250;
  }

  public selectArcStroke(args: any): any {
    const arcStroke = this.htmlElement.querySelector('#arcStroke') as HTMLInputElement;
    this.getChartEl(args).stroke = arcStroke.value;
  }

  public selectAxisLabelFontSize(args: any): any {
    const axisLabelFontSize = this.htmlElement.querySelector('#axisLabelFontSize') as HTMLInputElement;
    this.getChartEl(args).axisLabelFontSize = axisLabelFontSize.value;
  }

  public selectAxisTickFontSize(args: any): any {
    const axisTickFontSize = this.htmlElement.querySelector('#axisTickFontSize') as HTMLInputElement;
    this.getChartEl(args).axisTickFontSize = axisTickFontSize.value;
  }

  public selectAxisTickFontFamily(args: any): any {
    const axisTickFontFamily = this.htmlElement.querySelector('#axisTickFontFamily') as HTMLInputElement;
    this.getChartEl(args).axisTickFontFamily = axisTickFontFamily.value;
  }

  public selectBarStroke(args: any): any {
    const barStroke = this.htmlElement.querySelector('#barStroke') as HTMLInputElement;
    this.getChartEl(args).barStroke = barStroke.value;
  }

  public selectBarStrokeWidth(args: any): any {
    const barStrokeWidth = this.htmlElement.querySelector('#barStrokeWidth') as HTMLInputElement;
    this.getChartEl(args).barStrokeWidth = barStrokeWidth.value;
  }

  public selectColorScheme(args: any): any {
    const colorScheme = this.htmlElement.querySelector('#colorScheme') as HTMLInputElement;
    this.getChartEl(args).colorScheme = colorScheme.value;
  }

  public selectInnerRadius(args: any): any {
    const innerRadius = this.htmlElement.querySelector('#innerRadius') as HTMLInputElement;
    this.getChartEl(args).innerRadius = innerRadius.value;
  }

  public selectInterpolation(args: any): any {
    const interpolation = this.htmlElement.querySelector('#interpolation') as HTMLInputElement;
    this.getChartEl(args).interpolation = interpolation.value;
  }

  public selectLegendFontSize(args: any): any {
    const legendFontSize = this.htmlElement.querySelector('#legendFontSize') as HTMLInputElement;
    this.getChartEl(args).legendFontSize = legendFontSize.value;
  }

  public selectLinearDomain(args: any): any {
    const val = this.htmlElement.querySelector('#linearDomain') as HTMLInputElement;
    const el = this.getChartEl(args);
    if (val.value === 'percent') {
      el.linearTickFormat = 'percent1d';
    } else {
      el.linearTickFormat = 'localestring';
    }
    this.getChartEl(args).linearDomain = val.value;
  }

  public selectLineStroke(args: any): any {
    const val = this.htmlElement.querySelector('#lineStroke') as HTMLInputElement;
    this.getChartEl(args).strokeWidth = val.value;
  }

  public selectMargin(marginAttribute: any, args: any): any {
    const val = this.htmlElement.querySelector(`#${marginAttribute}`) as HTMLInputElement;
    const el = this.getChartEl(args);
    el[marginAttribute] = val.value;
  }

  public selectMaxBarWidth(args: any): any {
    const val = this.htmlElement.querySelector('#maxBarWidth') as HTMLInputElement;
    this.getChartEl(args).maxBarWidth = val.value;
  }

  public selectXTickSize(args: any): any {
    const val = this.htmlElement.querySelector('#xTickSize') as HTMLInputElement;
    this.getChartEl(args).xTickSize = val.value;
  }

  public selectYTickSize(args: any): any {
    const val = this.htmlElement.querySelector('#yTickSize') as HTMLInputElement;
    this.getChartEl(args).yTickSize = val.value;
  }

  public toggleGridlines(args: any): any {
    this.gridlines = !this.gridlines;
    this.getChartEl(args).gridlines = this.gridlines;
  }

  public toggleInverse(args: any): any {
    this.inverse = !this.inverse;
    this.getChartEl(args).inverse = this.inverse;

    if (this.inverse) {
      this.htmlElement.querySelector('div.chart').classList.add('inverse');
    } else {
      this.htmlElement.querySelector('div.chart').classList.remove('inverse');
    }
  }

  public toggleLegend(args: any): any {
    if (args === 'nexus-pie-chart') {
      this.showPieLegend = !this.showPieLegend;
      this.getChartEl(args).legend = this.showPieLegend;

      return;
    }

    this.showLegend = !this.showLegend;

    this.getChartEl(args).legend = this.showLegend;
  }

  public toggleOrientation(args: any): any {
    const orientationValue = this.htmlElement.querySelector('#orientation') as HTMLInputElement;
    const val = orientationValue.value || 'vertical';
    const el = this.getChartEl(args);
    let xLabel: any;
    let yLabel: any;

    // horizontal orientation
    if (val === 'horizontal') {
      if (args === 'nexus-stacked-bar-chart') {
        xLabel = 'Production';
        yLabel = 'Year';
      } else {
        xLabel = 'Price';
        yLabel = 'Ticker Symbol';
      }
    } else if (args === 'nexus-stacked-bar-chart') {
      xLabel = 'Year';
      yLabel = 'Production';
    } else {
      xLabel = 'Ticker Symbol';
      yLabel = 'Price';
    }

    el.orientation = val;
    el.xLabel = xLabel;
    el.yLabel = yLabel;
  }

  public toggleVertices(args: any): any {
    this.vertices = !this.vertices;
    this.getChartEl(args).vertices = this.vertices;
  }

  public toggleShowHideXAxis(args: any): any {
    this.hideXAxis = !this.hideXAxis;
    const el = this.getChartEl(args);

    if (this.hideXAxis) {
      el.xLabel = '';
      el.hideXAxis = true;
      el.hideXTicks = true;

      this.showXLabel = false;
      this.showXTicks = false;

      const xLabelItem = this.htmlElement.querySelector('#xLabel') as HTMLInputElement;
      xLabelItem.checked = false;
      xLabelItem.disabled = true;

      const xTicksItem = this.htmlElement.querySelector('#xTicks') as HTMLInputElement;
      xTicksItem.checked = false;
      xTicksItem.disabled = true;
    } else {
      el.xLabel = 'Date';
      el.hideXAxis = false;
      el.hideXTicks = false;

      this.showXLabel = true;
      this.showXTicks = true;

      const xLabelItem1 = this.htmlElement.querySelector('#xLabel') as HTMLInputElement;
      xLabelItem1.checked = true;
      xLabelItem1.disabled = false;

      const xTicksItem1 = this.htmlElement.querySelector('#xTicks') as HTMLInputElement;
      xTicksItem1.checked = true;
      xTicksItem1.disabled = false;
    }
  }

  public toggleShowHideXLabel(args: any): any {
    this.showXLabel = !this.showXLabel;
    this.getChartEl(args).xLabel = this.showXLabel ? 'Date' : '';
  }

  public toggleShowHideYLabel(args: any) {
    this.showYLabel = !this.showYLabel;
    this.getChartEl(args).yLabel = this.showYLabel ? 'Score' : '';
  }

  public toggleShowHideXTicks(args: any) {
    this.showXTicks = !this.showXTicks;
    this.getChartEl(args).hideXTicks = !this.showXTicks;
  }

  public toggleShowHideYAxis(args: any): any {
    this.hideYAxis = !this.hideYAxis;
    const el = this.getChartEl(args);

    if (this.hideYAxis) {
      el.yLabel = '';
      el.hideYAxis = true;
      el.hideYTicks = true;

      this.showYLabel = false;
      this.showYTicks = false;

      const yLabelItem2 = this.htmlElement.querySelector('#yLabel') as HTMLInputElement;
      yLabelItem2.checked = false;
      yLabelItem2.disabled = true;

      const yTicksItem2 = this.htmlElement.querySelector('#yTicks') as HTMLInputElement;
      yTicksItem2.checked = false;
      yTicksItem2.disabled = true;
    } else {
      el.yLabel = 'Score';
      el.hideYAxis = false;
      el.hideYTicks = false;

      this.showYLabel = true;
      this.showYTicks = true;

      const yLabelItem3 = this.htmlElement.querySelector('#yLabel') as HTMLInputElement;
      yLabelItem3.checked = true;
      yLabelItem3.disabled = false;
      const yTicksItem3 = this.htmlElement.querySelector('#yTicks') as HTMLInputElement;
      yTicksItem3.checked = true;
      yTicksItem3.disabled = false;
    }
  }


  toggleShowHideYTicks(args: any): any {
    this.showYTicks = !this.showYTicks;
    this.getChartEl(args).hideYTicks = !this.showYTicks;
  }

  public generateLineChartData(numLines: any): any {
    const dat = new Date(1546318800000);
    const msd = 86400000;

    return this.data.slice(0, numLines);
  }

  public generateRandomLineChartData(): any {
    const dat = new Date(1546318800000);
    const msd = 86400000;
    const iterations = Math.floor(Math.random() * 6) + 1;
    /* const data = []; */

    for (let i = 0; i < iterations; i++) {
      const u = i + 1;
      const user = `User ${u}`;

      this.data.push({
        label: user,
        name: user.toUpperCase(),
        data: [
          {
            x: dat.getTime() + (this.msd * 10),
            y: this.randomizer()
          },
          {
            x: dat.getTime() + (this.msd * 20),
            y: this.randomizer()
          },
          {
            x: dat.getTime() + (this.msd * 30),
            y: this.randomizer()
          },
          {
            x: dat.getTime() + (this.msd * 40),
            y: this.randomizer()
          },
          {
            x: dat.getTime() + (this.msd * 50),
            y: this.randomizer()
          },
          {
            x: dat.getTime() + (this.msd * 60),
            y: this.randomizer()
          }
        ]
      });
    }

    return this.data;
  }

  public generateRandomData(): any {
    this.getChartEl('nexus-line-chart').chartData = this.generateRandomLineChartData();
  }

  public selectNumLines(numLines: any): any {
    const chData = this.generateLineChartData(numLines);
    this.getChartEl('nexus-line-chart').chartData = chData;
  }

  public addListeners(): any {
    const xLabelInputMethod = this.htmlElement.querySelector('#xLabelInput') as HTMLInputElement;
    xLabelInputMethod.addEventListener('keyup', (evt) => {
      if (evt.key === 'Enter') {
        const evtVal = evt.target as HTMLInputElement;
        this.changeXLabel('nexus-line-chart', evtVal.value);
      }
    });

    const yLabelInputMethod = this.htmlElement.querySelector('#yLabelInput') as HTMLInputElement;
    yLabelInputMethod.addEventListener('keyup', (evt) => {
      if (evt.key === 'Enter') {
        const evtVal = evt.target as HTMLInputElement;
        this.changeYLabel('nexus-line-chart', evtVal.value);
      }
    });
  }

  ngOnInit(): void {
    this.htmlElement.querySelector('nexus-line-chart').chartData = this.generateLineChartData(3);
    this.addListeners();
    this.selectNumLines(8);
    this.htmlElement.querySelector('nexus-line-chart').canvasHeight = 450;
  }
}

<div id="wrapper" class="nexus-row">
    <div id="control-container" class="nexus-col-xs-4 nexus-col-lg-3">
        <div class="control-category">X-axis</div>
        <div class="control-item">
            <nexus-checkbox name="x-label" id="xLabel" checked (change)="toggleShowHideXLabel('nexus-line-chart')">Show
                Label</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-checkbox name="x-ticks" id="xTicks" checked (change)="toggleShowHideXTicks('nexus-line-chart')">Show
                Tick Values</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-checkbox name="hide-x" id="hideX" (change)="toggleShowHideXAxis('nexus-line-chart')">Hide Entire
                X-axis</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-label for="xTickSize" class="select">Tick Size / Length</nexus-label>
            <select name="x-tick-size" id="xTickSize" (input)="selectXTickSize('nexus-line-chart')">
                <option value="2" selected>2</option>
                <option value="4">4</option>
                <option value="10">10</option>
                <option value="12">12</option>
                <option value="16">16</option>
            </select>
        </div>
        <div class="control-item">
            <nexus-label for="xLabelInput" class="select">Label</nexus-label>
            <nexus-input type="text" placeholder="Enter text" id="xLabelInput"></nexus-input>
        </div>

        <div class="control-category">Y-axis</div>
        <div class="control-item">
            <nexus-checkbox name="y-label" id="yLabel" checked (change)="toggleShowHideYLabel('nexus-line-chart')">Show
                Label</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-checkbox name="y-ticks" id="yTicks" checked (change)="toggleShowHideYTicks('nexus-line-chart')">Show
                Tick Values</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-checkbox name="hide-y" id="hideY" (change)="toggleShowHideYAxis('nexus-line-chart')">Hide Entire
                Y-axis</nexus-checkbox>
        </div>
        <div class="control-item">
            <nexus-label for="yTickSize" class="select">Tick Size / Length</nexus-label>
            <select name="y-tick-size" id="yTickSize" (input)="selectYTickSize('nexus-line-chart')">
                <option value="2" selected>2</option>
                <option value="4">4</option>
                <option value="10">10</option>
                <option value="12">12</option>
                <option value="16">16</option>
            </select>
        </div>
        <div class="control-item">
            <nexus-label for="yLabelInput" class="select">Label</nexus-label>
            <nexus-input type="text" placeholder="Enter text" id="yLabelInput"></nexus-input>
        </div>

        <!-- miscellaneous options -->
        <div class="control-category">Options</div>

        <div class="control-item">
            <nexus-checkbox name="show-gridlines" id="showGridlines"
                (change)="toggleGridlines('nexus-line-chart')">Gridlines</nexus-checkbox>
        </div>

        <div class="control-item">
            <nexus-checkbox name="inverse" id="inverse"
                (change)="toggleInverse('nexus-line-chart')">Inverse</nexus-checkbox>
        </div>

        <div class="control-item">
            <nexus-checkbox name="show-legend" id="showLegend"
                (change)="toggleLegend('nexus-line-chart')">Legend</nexus-checkbox>
        </div>

        <div class="control-item">
            <nexus-checkbox type="checkbox" name="show-vertices" id="showVertices" checked
                (change)="toggleVertices('nexus-line-chart')">Vertices</nexus-checkbox>
        </div>

        <!-- axis stuff -->
        <div class="control-item">
            <nexus-label for="axisLabelFontSize" class="select">Axis Label Font Size</nexus-label>
            <select name="axis-label-font-size" id="axisLabelFontSize"
                (input)="selectAxisLabelFontSize('nexus-line-chart')">
                <option value="9">9px</option>
                <option value="12">12px</option>
                <option value="14" selected>14px</option>
                <option value="16">16px</option>
                <option value="20">20px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="axisTickFontFamily" class="select">Axis Tick Font Family</nexus-label>
            <select name="axis-tick-font-family" id="axisTickFontFamily"
                (input)="selectAxisTickFontFamily('nexus-line-chart')">
                <option value="sans" selected>sans-serif</option>
                <option value="serif">serif</option>
                <option value="monospace">monospace</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="axisTickFontSize" class="select">Axis Tick Font Size</nexus-label>
            <select name="axis-tick-font-size" id="axisTickFontSize"
                (input)="selectAxisTickFontSize('nexus-line-chart')">
                <option value="8">8px</option>
                <option value="9">9px</option>
                <option value="10" selected>10px</option>
                <option value="12">12px</option>
            </select>
        </div>

        <!-- color scheme --->
        <div class="control-item">
            <nexus-label for="colorScheme" class="select">Color Scheme</nexus-label>
            <select name="color-scheme" id="colorScheme" (input)="selectColorScheme('nexus-line-chart')">
                <option value="category10" selected>Category 10</option>
                <option value="accent">Accent</option>
                <option value="paired">Paired</option>
                <option value="set1">Set 1</option>
                <option value="set2">Set 2</option>
                <option value="set3">Set 3</option>
                <option value="black">Black</option>
                <option value="gray">Gray</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="legendFontSize" class="select">Legend Font Size</nexus-label>
            <select name="legend_font_size" id="legendFontSize" (input)="selectLegendFontSize('nexus-line-chart')">
                <option value="10">10px</option>
                <option value="12" selected>12px</option>
                <option value="14">14px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="interpolation" class="select">Line Interpolation</nexus-label>
            <select name="interp" id="interpolation" (input)="selectInterpolation('nexus-line-chart')">
                <option value="linear" selected>linear</option>
                <option value="basis">basis</option>
                <option value="monotone">monotone</option>
                <option value="step">step</option>
                <option value="step-before">step before</option>
                <option value="step-after">step-after</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="lineStroke" class="select">Line Stroke</nexus-label>
            <select name="line_stroke" id="lineStroke" (input)="selectLineStroke('nexus-line-chart')">
                <option value="1" selected>1</option>
                <option value="2">2</option>
                <option value="3">3</option>
            </select>
        </div>

        <!-- top, right, bottom, left margins -->
        <div class="control-item">
            <nexus-label for="marginBottom" class="select">Margin Bottom</nexus-label>
            <select name="margin-bottom" id="marginBottom" (input)="selectMargin('marginBottom', 'nexus-line-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="marginLeft" class="select">Margin Left</nexus-label>
            <select name="margin_left" id="marginLeft" (input)="selectMargin('marginLeft', 'nexus-line-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="marginRight" class="select">Margin Right</nexus-label>
            <select name="margin_right" id="marginRight" (input)="selectMargin('marginRight', 'nexus-line-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>

        <div class="control-item">
            <nexus-label for="marginTop" class="select">Margin Top</nexus-label>
            <select name="margin_top" id="marginTop" (input)="selectMargin('marginTop', 'nexus-line-chart')">
                <option value="25" selected>25px</option>
                <option value="50">50px</option>
                <option value="75">75px</option>
            </select>
        </div>
    </div>

    <!-- chart container -->
    <div id="chart-container" class="nexus-col-xs-4 nexus-col-lg-9 position">
        <div class="page-title">&lt;nexus-line-chart&gt;</div>

        <div class="hoz-group">
            <span class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumLines(1)">1 Line</button>
            </span>
            <span class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumLines(2)">2 Lines</button>
            </span>
            <span class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumLines(3)">3 Lines</button>
            </span>
            <span class="btn-item">
                <button type="button" class="nexus-btn" (click)="selectNumLines(4)">4 Lines</button>
            </span>
            <span class="btn-item">
                <button type="button" class="nexus-btn" (click)="generateRandomData()">Random</button>
            </span>
        </div>

        <div class="chart">
            <nexus-line-chart chart-id="NexusLineChart" margin-left="50" margin-right="50" responsive vertices
                x-label="Date" x-tick-format="M/D/YY" y-label="Score" y-tick-format="localestring"
                [chartData]="data"></nexus-line-chart>
        </div>
    </div>
</div>
