// ui-nexus-design-system/playbook/angular/src/app/sb/components/avatar/01_avatar.component.ts
import { Component, Input } from '@angular/core';
import { avatar } from '../../constants';

@Component({
  selector: 'app-avatar',
  templateUrl: './01_avatar.component.html'
})
export default class AvatarComponent {
  @Input() userName: string;

  @Input() avatarImageSrc: string = avatar.image;

  @Input() avatarClassName: string = avatar.class;

  @Input() avatarSize: string = avatar.size;

  @Input() avatarStatus: string = avatar.status;

  @Input() description: string = avatar.descript;

  @Input() avatarNotification: string = avatar.notification;

  @Input() avatarLogoIcon: string = avatar.logoIcon;

  @Input() avatarNameDisplay: boolean = avatar.nameDisplay;

  @Input() avatarDark: boolean = avatar.dark;
}

// ui-nexus-design-system/playbook/react/src/sb/components/avatar/01_avatar.tsx
import React from 'react';
import PropTypes from 'prop-types';

import { NexusAvatar } from '@nexus/react';

export const AvatarComponent: React.FC = (props) => {
  const {
    userName = 'Name',
    avatarNotification = '',
    avatarImageSrc = '',
    avatarClassName = '',
    avatarSize = 'lg',
    avatarStatus = '',
    description = '',
    avatarNameDisplay = false,
    avatarDark = false,
    avatarLogoIcon = ''
  } = { ...props };

  return (
    <NexusAvatar
      userName={userName}
      avatarNotification={avatarNotification}
      avatarImageSrc={avatarImageSrc}
      avatarClassName={avatarClassName}
      avatarSize={avatarSize}
      avatarStatus={avatarStatus}
      description={description}
      avatarNameDisplay={avatarNameDisplay}
      avatarDark={avatarDark}
      avatarLogoIcon={avatarLogoIcon}
    ></NexusAvatar>
  );
};

AvatarComponent.propTypes = {
  userName: PropTypes.string,
  avatarNotification:  PropTypes.string,
  avatarImageSrc:  PropTypes.string,
  avatarClassName: PropTypes.string,
  avatarSize: PropTypes.string,
  avatarStatus:  PropTypes.string,
  description:  PropTypes.string,
  avatarNameDisplay:  PropTypes.bool,
  avatarDark:  PropTypes.bool,
  avatarLogoIcon:  PropTypes.string
};

export default AvatarComponent;
