// ui-nexus-design-system/playbook/angular/src/app/sb/components/avatar/03_status.component.ts
import { Component } from '@angular/core';
import { status } from '../../constants';
@Component({
  selector: 'app-avatar-examples-status',
  templateUrl: './03_status.component.html'
})
export default class StatusComponent {
  name = status.name;

  size = status.size;

  status = status.status;

  avatarNameDisplay = status.avatarNameDisplay;
}

<div class="nexus-col-xl-8">
  <p>
    <nexus-avatar
      [avatarSize]="size"
      [userName]="name"
      [avatarStatus]="status"
      [avatarNameDisplay]="avatarNameDisplay"
    ></nexus-avatar>
  </p>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/avatar/03_status.tsx
import React from 'react';

import { NexusAvatar } from '@nexus/react';

export const StatusComponent: React.FC = () => (
    <div className="nexus-col-xl-8">
        <NexusAvatar avatar-size='lg'
        user-name='Joseph Benjamin'
        avatar-status='online'
        avatar-name-display={false} />
    </div>
);

export default StatusComponent;
