// ui-nexus-design-system/playbook/angular/src/app/sb/components/avatar/04_imageAndName.component.ts
import { Component } from '@angular/core';
import { imageAndName } from '../../constants';
@Component({
  selector: 'app-avatar-examples-imageandname',
  templateUrl: './04_imageAndName.component.html'
})
export default class ImageAndNameComponent {
  name = imageAndName.name;

  size = imageAndName.size;

  image = imageAndName.image;
}

<div class="nexus-col-xl-8">
  <p>
    <nexus-avatar [avatarImageSrc]="image" [avatarSize]="size" [userName]="name"> </nexus-avatar>
  </p>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/avatar/04_imageAndName.tsx
import React from 'react';

import { NexusAvatar } from '@nexus/react';
import AvatarImage from '@nexus/core/dist/assets/images/avatar.png';


export const ImageAndNameComponent: React.FC = () => (
    <div className="nexus-col-xl-8">
        <NexusAvatar
        avatar-image-src={AvatarImage}
        avatar-size='lg'
        user-name='Emma Roberts'
    />
    </div>
)

export default ImageAndNameComponent;
