// ui-nexus-design-system/playbook/angular/src/app/sb/components/slider/02_disabled.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-slider-disabled',
  templateUrl: './02_disabled.component.html'
})
export default class SliderDisabledComponent {
  @Input() max: number = 100;

  @Input() min: number = 0;
}

<nexus-form-field>
    <nexus-slider data-testid="slider" [max]="max" [min]="min" disabled="disabled"></nexus-slider>
</nexus-form-field>

// ui-nexus-design-system/playbook/react/src/sb/components/slider/02_disabled.tsx
import React from 'react';

import { NexusFormField, NexusSlider } from '@nexus/react';

const SliderDisabledComponent: React.FC = () => (
    <>
        <NexusFormField>
            <NexusSlider
                disabled
                data-testid="slider-disabled"
            ></NexusSlider>
        </NexusFormField>
    </>
);
export default SliderDisabledComponent;
