// ui-nexus-design-system/playbook/angular/src/app/sb/components/slider/03_validation.component.ts
import { Component, Input } from '@angular/core';
import { validation } from '../../constants';


@Component({
  selector: 'app-validation',
  templateUrl: './03_validation.component.html'
})
export default class ValidationComponent {
  @Input() disabled: boolean = false;

  values = validation.values;

  text = validation.text;

  variable = validation.variable;

  onKey(event: any) {
    this.values = event.target.value;
    if (this.values >= 7) {
      this.variable = 'master';
    } else if (this.values >= 4) {
      this.variable = 'medium advanced';
    } else {
      this.variable = 'novice';
    }
  }
}

<div class="nexus-row nexus-center-xs">
    <div class="nexus-col-xs-3">
        <nexus-label>{{text}}</nexus-label>
    </div>
    <div class="nexus-col-xs-3">
        <nexus-slider data-testid="slider" max="10" min="0" [disabled]="disabled" (input)="onKey($event)">
        </nexus-slider>
    </div>
    <div class="nexus-col-xs-3">
        <p id="userScore">If you have {{values}} years of experience, you are
            {{variable}}.</p>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/slider/03_validation.tsx
import React, { useState } from 'react';
import { validation } from '../../constants';


import { NexusLabel, NexusSlider } from '@nexus/react';

interface ValidationProps {
    disabled: boolean;
    max: number;
    min: number;
    required: boolean;
}



const Validation: React.FC<ValidationProps> = (props) => {
    const [valueInfo, setValueInfo] = useState(5);
    const [experience, setExperience] = useState('medium advanced');

    const inputHandler = (event: any) => {
        setValueInfo(event.target.value)
        if (valueInfo >= 7) {
            setExperience('master')
        } else if (valueInfo >= 4) {
            setExperience('medium advanced')
        } else {
            setExperience('novice')
        }
    };

    return (
            <div className="nexus-row nexus-center-xs">
                <div className="nexus-col-xs-3">
                    <NexusLabel>{validation.text}</NexusLabel>
                </div>
                <div className="nexus-col-xs-3">
                    <NexusSlider
                        {...props} data-testid="slider"
                        onInput={inputHandler}
                    ></NexusSlider>
                </div>
                <div className="nexus-col-xs-3">
                    <p>If you have {valueInfo} years of experience, you are {experience}.</p>
                </div>
            </div >
    );
}

Validation.defaultProps = {
    disabled: false,
    max: 10,
    min: 0,
    required: false
};

export default Validation;
