// ui-nexus-design-system/playbook/react/src/sb/components/radio/01_radio.tsx
import PropTypes from 'prop-types';
import { NexusRadio } from '@nexus/react';

const RadioComponent: React.FC = (props) => {
  const {
    disabled = false,
    nameOption = 'Simple Radio Example',
    required = false,
    value = '',
    checked = false
  } = { ...props };

  return (
    <>
      <div className="nexus-center-xs nexus-mt-5">
        <div className="nexus-row nexus-center-xs">
          <NexusRadio
            data-testid="radio-btn-opt1"
            checked={checked}
            disabled={disabled}
            name={nameOption}
            required={required}
            value={value}
          >
            Option 1
          </NexusRadio>

          <NexusRadio
            data-testid="radio-btn-opt2"
            disabled={disabled}
            checked={checked}
            name={nameOption}
            required={required}
            value={value}
          >
            Option 2
          </NexusRadio>
        </div>
      </div>
    </>
  );
};

RadioComponent.propTypes = {
  disabled: PropTypes.bool,
  name: PropTypes.string,
  required: PropTypes.bool,
  value: PropTypes.string
};

export default RadioComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/radio/01_radio.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-radio',
  templateUrl: './01_radio.component.html'
})
export default class RadioComponent {
  @Input() attrId: string;

  @Input() checked: boolean = true;

  @Input() disabled: boolean = true;

  @Input() nameOption: string = 'Simple Radio Example';

  @Input() required: boolean;

  @Input() value: string;
}

<div class="nexus-center-xs nexus-mt-5">
  <div class="nexus-row nexus-center-xs">
    <nexus-radio
      [checked]="checked"
      data-testid="radio-btn-opt1"
      [attrId]="attrId"
      [name]="nameOption"
      [disabled]="disabled"
      [required]="required"
      [value]="value"
    >
      Option 1</nexus-radio
    >
    <nexus-radio
      data-testid="radio-btn-opt1"
      [attrId]="attrId"
      [name]="nameOption"
      [disabled]="disabled"
      [required]="required"
      [checked]="checked"
    >
      Option 2</nexus-radio
    >
  </div>
</div>
