// ui-nexus-design-system/playbook/react/src/sb/components/radio/05_groupDisabled.tsx
import React, { useState } from 'react';
import { groupDisabled } from '../../constants';


import { NexusRadio } from '@nexus/react';

const RadioExampleComponent: React.FC = () => {
  const [value1, setValue1] = useState('');

  return (
    <>
      <div className="nexus-center-xs nexus-mt-5">
        <div className="nexus-row nexus-center-xs">
          <NexusRadio
            data-testid="disabled-option1"
            checked={value1 === 'option1'}
            name="group1"
            disabled={true}
            onInput={(event: any) => setValue1(event.target.value)}
            aria-hidden="true"
          >
            {groupDisabled.first}
          </NexusRadio>

          <NexusRadio
            data-testid="disabled-option2"
            checked={value1 === 'option2'}
            name="group1"
            disabled={true}
            onInput={(event: any) => setValue1(event.target.value)}
            aria-hidden="true"
          >
            {groupDisabled.second}
          </NexusRadio>

          <NexusRadio
            data-testid="disabled-option3"
            checked={value1 === 'option3'}
            name="group1"
            disabled={true}
            onInput={(event: any) => setValue1(event.target.value)}
            aria-hidden="true"
          >
            {groupDisabled.third}
          </NexusRadio>
        </div>
      </div>
    </>
  );
};

export default RadioExampleComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/radio/05_groupDisabled.component.ts
import { Component, Input } from '@angular/core';
import { radio, groupDisabled } from '../../constants';

@Component({
  selector: 'app-group-disabled',
  templateUrl: './05_groupDisabled.component.html'
})
export default class GroupDisabledComponent {
  @Input() name = radio.name;

  @Input() disabled: boolean = true;

  groupDisabled = groupDisabled;
}

<div class="nexus-center-xs nexus-mt-5">
    <div class="nexus-row nexus-center-xs">
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="true">
            {{groupDisabled.first}}</nexus-radio>
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="true">
            {{groupDisabled.second}}</nexus-radio>
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="true">
            {{groupDisabled.third}}</nexus-radio>
    </div>
</div>
