// ui-nexus-design-system/playbook/react/src/sb/components/radio/06_disabledSelected.tsx
import React, { useState } from 'react';
import { disabledSelected } from '../../constants';


import { NexusRadio } from '@nexus/react';

const RadioExampleComponent: React.FC = () => {
  const [value2, setValue2] = useState('option1');

  return (
    <>
      <div className="nexus-center-xs nexus-mt-5">
        <div className="nexus-row nexus-center-xs">
          <NexusRadio
            data-testid="disabled-selected-option1"
            checked={value2 === 'option1'}
            name="group2"
            disabled={true}
            onInput={(event: any) => setValue2(event.target.value)}
            aria-hidden="true"
          >
            {disabledSelected.first}
          </NexusRadio>

          <NexusRadio
            data-testid="disabled-selected-option2"
            checked={value2 === 'option2'}
            name="group2"
            disabled={true}
            onInput={(event: any) => setValue2(event.target.value)}
            aria-hidden="true"
          >
            {disabledSelected.second}
          </NexusRadio>

          <NexusRadio
            data-testid="disabled-selected-option3"
            checked={value2 === 'option3'}
            name="group2"
            disabled={true}
            onInput={(event: any) => setValue2(event.target.value)}
            aria-hidden="true"
          >
            {disabledSelected.third}
          </NexusRadio>
        </div>
      </div>
    </>
  );
};

export default RadioExampleComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/radio/06_disabledSelected.component.ts
import { Component, Input } from '@angular/core';
import { radio, disabledSelected } from '../../constants';

@Component({
  selector: 'app-disabled-selected',
  templateUrl: './06_disabledSelected.component.html'
})
export default class DisabledSelectedComponent {
  @Input() name = radio.name;

  @Input() disabled: boolean = true;

  disabledSelected = disabledSelected;
}

<div class="nexus-center-xs nexus-mt-5">
    <div class="nexus-row nexus-center-xs">
        <nexus-radio data-testid="radio-btn-opt1" checked="true" [name]="name" [disabled]="true">
            {{disabledSelected.first}}</nexus-radio>
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="true">
            {{disabledSelected.second}}</nexus-radio>
        <nexus-radio data-testid="radio-btn-opt1" [name]="name" [disabled]="true">
            {{disabledSelected.third}}</nexus-radio>
    </div>
</div>
