// ui-nexus-design-system/playbook/angular/src/app/components/dropdown/dropdown.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-dropdown',
  templateUrl: './dropdown.component.html'
})
export class DropdownComponent {
}

<p class="nexus-h6">Basic Dopdown</p>

<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint
    <nexus-dropdown id="dropdownId" dropdown-type="basic" placement="right" height="150" width="180">
        <nexus-icon slot="trigerer" id="iconId" src="./assets/icons/navigation/ic_more_vert_24px.svg"></nexus-icon>
        <nexus-option label="Option 1" value="Option1">Option 1</nexus-option>
        <nexus-option label="Option 2" value="Option2">Option 2</nexus-option>
        <nexus-option label="Option 3" value="Option3">Option 3</nexus-option>
    </nexus-dropdown>
    dignissimos.
</p>

// ui-nexus-design-system/playbook/react/src/components/dropdown/dropdown.tsx
import { NexusDropdown, NexusIcon, NexusOption } from '@nexus/react';

import NavigationIcMoreVert24px from '@nexus/core/dist/assets/icons/navigation/ic_more_vert_24px.svg';


const DropdownComponent: React.FC = () => {
  return (
    <>
      <p className="nexus-h6">Basic Dopdown</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint
        <NexusDropdown placement={"right"} dropdown-type={"basic"} height={150} width={180}>
          <NexusIcon slot={"trigerer"} id={"iconId"} src={NavigationIcMoreVert24px}></NexusIcon>
          <NexusOption>Option 1</NexusOption>
          <NexusOption>Option 2</NexusOption>
          <NexusOption>Option 3</NexusOption>
        </NexusDropdown>
        dignissimos.
      </p>
    </>
  );
};

export default DropdownComponent;
