// ui-nexus-design-system/playbook/react/src/sb/components/checkbox/01_checkbox.tsx
import React from 'react';
import PropTypes from 'prop-types';

import { NexusCheckbox } from '@nexus/react';


const CheckboxComponent: React.FC = (props) => <NexusCheckbox {...props}>Check me!</NexusCheckbox>

CheckboxComponent.propTypes = {
  attrId: PropTypes.string,
  checked: PropTypes.bool,
  disabled: PropTypes.bool,
  indeterminate: PropTypes.bool,
  required: PropTypes.bool
};

export default CheckboxComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/checkbox/01_checkbox.component.ts
import { Component, Input } from '@angular/core';

import { checkBox } from '../../constants';
@Component({
  selector: 'app-checkbox',
  templateUrl: './01_checkbox.component.html'
})
export default class CheckboxComponent {
  @Input() disabled = checkBox.disabled;

  @Input() checked = checkBox.checked;

  @Input() indeterminate = checkBox.indeterminate;

  text = checkBox.text;

  attrId = checkBox.attrId;

  required = checkBox.required;
}

<nexus-checkbox [attrId]="attrId" [checked]="checked" [disabled]="disabled" [indeterminate]="indeterminate"
  >{{text}}</nexus-checkbox
>
