// ui-nexus-design-system/playbook/angular/src/app/components/radio-examples/radio-examples.component.ts
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-radio-examples',
  templateUrl: './radio-examples.component.html',
  styleUrls: ['./radio-examples.component.scss']
})
export class RadioExamplesComponent {
  radioGroup1 = [
    {
      name: 'Option 1',
      value: 'option1'
    },
    {
      name: 'Option 2',
      value: 'option2'
    },
    {
      name: 'Option 3',
      value: 'option3'
    }
  ];

  radioValue1 = new FormControl({ value: '',
    disabled: true });

  radioGroup2 = [
    {
      name: 'Option 1',
      value: 'option1'
    },
    {
      name: 'Option 2',
      value: 'option2'
    },
    {
      name: 'Option 3',
      value: 'option3'
    }
  ];

  radioValue2 = new FormControl({ value: 'option1',
    disabled: true });
}

<p class="nexus-h5">Disabled</p>

<section class="nexus-rhythm-5">
  <div *ngFor="let option of radioGroup1">
    <nexus-radio
      name="group3"
      ngDefaultControl
      [value]="option.value"
      [checked]="radioValue1.value === option.value"
      [formControl]="radioValue1"
      disabled
    >
      {{ option.name }}
    </nexus-radio>
  </div>
</section>

<p class="nexus-h5">Disabled - selected</p>

<section class="nexus-rhythm-5">
  <div *ngFor="let option of radioGroup2">
    <nexus-radio
      name="group2"
      ngDefaultControl
      [value]="option.value"
      [checked]="radioValue2.value === option.value"
      [formControl]="radioValue2"
      disabled
    >
      {{ option.name }}
    </nexus-radio>
  </div>
</section>

// ui-nexus-design-system/playbook/react/src/components/radio/radio-examples.tsx
import React, { useState } from 'react';

import { NexusRadio } from '@nexus/react';

const RadioExampleComponent: React.FC = () => {
  const [value1, setValue1] = useState('');

  const [value2, setValue2] = useState('option1');

  return (
    <>
      <p className="nexus-h5">Disabled</p>

      <section className="nexus-rhythm-5">
        <NexusRadio
          data-testid="disabled-option1"
          checked={value1 === 'option1'}
          name="group1"
          disabled={true}
          onInput={(event: any) => setValue1(event.target.value)}
          aria-hidden="true"
        >
          Option 1
        </NexusRadio>

        <NexusRadio
          data-testid="disabled-option2"
          checked={value1 === 'option2'}
          name="group1"
          disabled={true}
          onInput={(event: any) => setValue1(event.target.value)}
          aria-hidden="true"
        >
          Option 2
        </NexusRadio>

        <NexusRadio
          data-testid="disabled-option3"
          checked={value1 === 'option3'}
          name="group1"
          disabled={true}
          onInput={(event: any) => setValue1(event.target.value)}
          aria-hidden="true"
        >
          Option 3
        </NexusRadio>
      </section>

      <p className="nexus-h5">Disabled - selected</p>
      <section className="nexus-rhythm-5">
        <NexusRadio
          data-testid="disabled-selected-option1"
          checked={value2 === 'option1'}
          name="group2"
          disabled={true}
          onInput={(event: any) => setValue2(event.target.value)}
          aria-hidden="true"
        >
          Option 1
        </NexusRadio>

        <NexusRadio
          data-testid="disabled-selected-option2"
          checked={value2 === 'option2'}
          name="group2"
          disabled={true}
          onInput={(event: any) => setValue2(event.target.value)}
          aria-hidden="true"
        >
          Option 2
        </NexusRadio>

        <NexusRadio
          data-testid="disabled-selected-option3"
          checked={value2 === 'option3'}
          name="group2"
          disabled={true}
          onInput={(event: any) => setValue2(event.target.value)}
          aria-hidden="true"
        >
          Option 3
        </NexusRadio>
      </section>
    </>
  );
};

export default RadioExampleComponent;
