// ui-nexus-design-system/playbook/react/src/sb/components/modal/01_modal.tsx
import { useState } from 'react';
import { defaultModal } from '../../constants';
import PropTypes from 'prop-types';
import { NexusModal, NexusModalFooter, NexusModalBody, NexusModalHeader, NexusModalHeaderSubtitle, NexusFormField, NexusLabel, NexusInput } from '@nexus/react';


const ModalComponent: React.FC = (props) => {
  const { fullscreen = false, show = false, size = "md" } = { ...props };
  const [showModal, setShowModal] = useState(show);
  const [username, setUserName] = useState('');
  const [password, setPassword] = useState('');
  const [email, setEmail] = useState('');

  return (
    <>
      <div className="nexus-center-xs nexus-pt-6">
        <button
          data-testid="btn-show-modal"
          className="nexus-btn-primary nexus-btn-large"
          onClick={() => setShowModal(true)}
        >
          Show Modal
        </button>
      </div>

      <NexusModal data-testid="overlay" id="modal" show={showModal} fullscreen={fullscreen} size={size}>
        <NexusModalHeader data-testid="modal-header" onCloseEvent={() => setShowModal(false)}>
          Nexus
          <NexusModalHeaderSubtitle data-testid="modal-Placeholder">{defaultModal.header}</NexusModalHeaderSubtitle>
        </NexusModalHeader>
        <NexusModalBody>
          <NexusFormField>

            <NexusLabel data-testid="label-first-name">{defaultModal.usernameText}</NexusLabel>
            <NexusInput
              {...props}
              data-testid="input-text-box"
              placeholder={defaultModal.name}
              value={username}
              onInput={(event: any) => setUserName(event.target.value)}
            ></NexusInput>
            <NexusLabel data-testid="label-first-name">{defaultModal.emailText}</NexusLabel>
            <NexusInput
              {...props}
              data-testid="input-text-box"
              placeholder={defaultModal.emailAddress}
              value={email}
              onInput={(event: any) => setEmail(event.target.value)}
            ></NexusInput>
            <NexusLabel data-testid="label-first-name">{defaultModal.passwordText}</NexusLabel>
            <NexusInput
              {...props}
              data-testid="input-text-box"
              type={"password"}
              value={password}
              onInput={(event: any) => setPassword(event.target.value)}
            ></NexusInput>
          </NexusFormField>
        </NexusModalBody>
        <NexusModalFooter>
          <button onClick={() => setShowModal(false)} data-testid="btn-confirm" className="nexus-btn-primary">
            {defaultModal.confirm}
          </button>
          <button onClick={() => setShowModal(false)} data-testid="btn-cancel" className="nexus-btn">
            {defaultModal.cancel}
          </button>
        </NexusModalFooter>
      </NexusModal>
    </>
  );
};

ModalComponent.propTypes = {
  fullscreen: PropTypes.bool,
  show: PropTypes.bool,
  size: PropTypes.string
};

export default ModalComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/modal/01_modal.component.ts
import { Component, Input } from '@angular/core';
import { defaultModal } from '../../constants';

@Component({
  selector: 'app-modal',
  templateUrl: './01_modal.component.html'
})
export default class ModalComponent {
  @Input() show: boolean = false;

  @Input() size: string = 'md';

  @Input() fullscreen: boolean = false;

  defaultModal = defaultModal;

  userName = defaultModal.name;

  email = defaultModal.emailAddress;

  isUserNameValid = true;

  isPasswordValid = true;

  handleCloseEvent = () => {};

  validate(event) {
    return this.isUserNameValid && this.isPasswordValid;
  }

  updateUserName(event) {
    this.userName = event.target.value;
  }

  updateEmailAddress(event) {
    this.email = event.target.value;
  }
}

<div class="nexus-center-xs nexus-pt-6">
  <button class="nexus-btn-primary nexus-btn-large" (click)="show = true">{{defaultModal.buttonText}}</button>
</div>

<nexus-modal id="modal" [show]="show" [size]="size" [fullscreen]="fullscreen" (closeEvent)="handleCloseEvent()">
  <nexus-modal-header (closeEvent)="show = false">
    Nexus
    <nexus-modal-header-subtitle>{{defaultModal.header}}</nexus-modal-header-subtitle>
  </nexus-modal-header>
  <nexus-modal-body>
    <div className="nexus-row">
      <div className="nexus-col-md-4 nexus-col-lg-6 nexus-col-xl-6">
        <nexus-form-field>
          <nexus-label>{{defaultModal.usernameText}}</nexus-label>
          <nexus-input [placeholder]="userName" required (input)="updateUserName($event)"></nexus-input>

          <nexus-label>{{defaultModal.emailText}}</nexus-label>
          <nexus-input [placeholder]="email" required (input)="updateEmailAddress($event)"></nexus-input>

          <nexus-label>{{defaultModal.passwordText}}</nexus-label>
          <nexus-input required type="password"></nexus-input>
        </nexus-form-field>
      </div>
    </div>
  </nexus-modal-body>
  <nexus-modal-footer>
    <button (click)="show = false" class="nexus-btn-primary">{{defaultModal.confirm}}</button>
    <button (click)="show = false" class="nexus-btn">{{defaultModal.cancel}}</button>
  </nexus-modal-footer>
</nexus-modal>
