// ui-nexus-design-system/playbook/react/src/sb/components/modal/02_termsOfUse.tsx
import React, { useState } from 'react';
import { termsOfUse } from '../../constants';
import {
  NexusModal,
  NexusModalFooter,
  NexusModalBody,
  NexusModalHeader,
  NexusModalHeaderSubtitle,
  NexusNotification,
  NexusCheckbox
 } from '@nexus/react';


const ModalEventHandlerComponent: React.FC = (props) => {
  const { fullscreen = false, show = false } = { ...props };
  const [showModal, setShowModal] = useState(show);
  const [isTermsAccepted, setTermsAccepted] = useState(false);


  return (
    <>
      <div className="nexus-center-xs nexus-pt-6">
        <button
          data-testid="btn-show-modal"
          className="nexus-btn-primary nexus-btn-large"
          onClick={() => setShowModal(true)}
        >
          {termsOfUse.acceptTermsAndConditions}
        </button>
      </div>

      {isTermsAccepted ?
        <NexusNotification variant='success'>{termsOfUse.notificationSuccess}</NexusNotification>:
        <NexusNotification variant='error'>{termsOfUse.notificationFailure}</NexusNotification>
      }

      <NexusModal data-testid="overlay" id="modal" show={showModal} fullscreen={fullscreen} size='md' onCloseEvent = {() => console.log("Triggered close of modal.")}>
        <NexusModalHeader data-testid="modal-header" onCloseEvent={() => setShowModal(false)}>
          {termsOfUse.title}
          <NexusModalHeaderSubtitle data-testid="modal-Placeholder">{termsOfUse.subTitle}</NexusModalHeaderSubtitle>
        </NexusModalHeader>
        <NexusModalBody>
              <h4 className='nexus-h4'>{termsOfUse.agreement}</h4>
              <div dangerouslySetInnerHTML={{ __html: termsOfUse.details }}></div>

              <NexusCheckbox checked={isTermsAccepted} onInput={() => setTermsAccepted(!isTermsAccepted)}>{termsOfUse.checkBoxText}</NexusCheckbox>
        </NexusModalBody>
        <NexusModalFooter>
          <button onClick={() => setShowModal(false)} data-testid="btn-confirm" className="nexus-btn-primary">
            {termsOfUse.submit}
          </button>
          <button onClick={() => setShowModal(false)} data-testid="btn-cancel" className="nexus-btn">
            {termsOfUse.cancel}
          </button>
        </NexusModalFooter>
      </NexusModal>
    </>
  );
};

export default ModalEventHandlerComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/modal/02_termsOfUse.component.ts
import { Component, Input } from '@angular/core';
import { termsOfUse } from '../../constants';

@Component({
  selector: 'app-modal-tou',
  templateUrl: './02_termsOfUse.component.html'
})
export default class ModalTOUComponent {
  @Input() show: boolean = false;

  @Input() fullscreen: boolean = false;

  termsOfUse = termsOfUse;

  isChecked = false;

  notificationType = 'error';

  notificationMessage = termsOfUse.notificationFailure;

  handleCloseEvent = () => { };

  updateIsChecked(status: boolean) {
    this.isChecked = status;
    this.notificationType = this.isChecked ? 'success' : 'error';
    this.notificationMessage = this.isChecked ? termsOfUse.notificationSuccess : termsOfUse.notificationFailure;
  }
}

<div class="nexus-center-xs nexus-pt-6">
  <button class="nexus-btn-primary nexus-btn-large"
    (click)="show = true">{{termsOfUse.acceptTermsAndConditions}}</button>
</div>
<div class="nexus-center-xs nexus-mt-4">
  <nexus-notification [variant]="notificationType">{{notificationMessage}}</nexus-notification>
</div>

<nexus-modal id="modal" [show]="show" size="md" [fullscreen]="fullscreen" (closeEvent)="handleCloseEvent()">
  <nexus-modal-header (closeEvent)="show = false">
    {{termsOfUse.title}}
    <nexus-modal-header-subtitle>{{termsOfUse.subTitle}}</nexus-modal-header-subtitle>
  </nexus-modal-header>
  <nexus-modal-body>
    <h4 className='nexus-h4'>{{termsOfUse.agreement}}</h4>
    <p [innerHTML]="termsOfUse.details"></p>

    <nexus-checkbox [checked]="isChecked"
      (input)="updateIsChecked(!this.isChecked)">{{termsOfUse.checkBoxText}}</nexus-checkbox>
  </nexus-modal-body>
  <nexus-modal-footer>
    <button (click)="show = false" class="nexus-btn-primary">{{termsOfUse.submit}}</button>
    <button (click)="show = false" class="nexus-btn">{{termsOfUse.cancel}}</button>
  </nexus-modal-footer>
</nexus-modal>
