// ui-nexus-design-system/playbook/angular/src/app/sb/components/accordion/03_cardInsideAccordion.component.ts
import { Component, Input } from '@angular/core';
import { cardInsideAccordion } from '../../constants';

@Component({
  selector: 'app-card-inside-accordion',
  templateUrl: './03_cardInsideAccordion.component.html'
})
export default class CardInsideAccordionComponent {
  @Input() open: boolean = false;

  data = cardInsideAccordion;
}

<nexus-accordion [open]="open" (toggleEvent)="open = !open" size="md">
    <nexus-accordion-trigger>
        <h1 class="nexus-body">{{data.show}}</h1>
    </nexus-accordion-trigger>
    <nexus-accordion-content>
        <nexus-card bgColor="bgColor" height="height">
            <nexus-card-avatar>
                <img [src]="data.avatar" [alt]="data.name" />
            </nexus-card-avatar>
            <nexus-card-header>
                <nexus-card-header-title>{{data.name}}</nexus-card-header-title>
                <nexus-card-header-subtitle>{{data.profession}}</nexus-card-header-subtitle>
                <nexus-card-header-subtitle>{{data.education}}</nexus-card-header-subtitle>
                <nexus-card-header-details>{{data.lastLogin}}</nexus-card-header-details>
                <nexus-card-header-button style="display:block">
                    <div class="nexus-row" style="margin-bottom:5px">
                        <button class=" nexus-btn-primary nexus-btn-medium">{{data.viewProfile}}</button>
                    </div>
                    <div class="nexus-row">
                        <button class="nexus-btn nexus-btn-medium">{{data.contactUser}}</button>
                    </div>
                </nexus-card-header-button>
            </nexus-card-header>
            <nexus-card-footer>
            </nexus-card-footer>
        </nexus-card>
    </nexus-accordion-content>
</nexus-accordion>

// ui-nexus-design-system/playbook/react/src/sb/components/accordion/03_cardInsideAccordion.tsx
import { NexusAccordion, NexusAccordionContent, NexusAccordionTrigger, NexusCard, NexusCardAvatar, NexusCardHeader, NexusCardHeaderButton, NexusCardHeaderDetails, NexusCardHeaderSubtitle, NexusCardHeaderTitle } from "@nexus/react";
import React, { useState } from "react";
import { cardInsideAccordion } from "../../constants";


const CardInsideAccordionComponent: React.FC = () => {
    const [openAcccordion, setAccordionOpen] = useState(false);

return(
    <NexusAccordion open={openAcccordion} onToggleEvent={() => setAccordionOpen(!openAcccordion)} size="md">
    <NexusAccordionTrigger>
      <h1 className="nexus-body">{cardInsideAccordion.show}</h1>
    </NexusAccordionTrigger>
    <NexusAccordionContent>

    <NexusCard bgColor="bgColor" height="height">
            <NexusCardAvatar>
                <img src={cardInsideAccordion.avatar} alt={cardInsideAccordion.name} />
            </NexusCardAvatar>
            <NexusCardHeader>
                <NexusCardHeaderTitle>{cardInsideAccordion.name}</NexusCardHeaderTitle>
                <NexusCardHeaderSubtitle>{cardInsideAccordion.profession}</NexusCardHeaderSubtitle>
                <NexusCardHeaderSubtitle>{cardInsideAccordion.education}</NexusCardHeaderSubtitle>
                <NexusCardHeaderDetails>{cardInsideAccordion.lastLogin}</NexusCardHeaderDetails>
                <NexusCardHeaderButton style={{display: "block"}}>
                    <div className="nexus-row" style={{marginBottom: "5px"}}>
                        <button className=" nexus-btn-primary nexus-btn-medium">{cardInsideAccordion.viewProfile}</button>
                    </div>
                    <div className="nexus-row">
                        <button className="nexus-btn nexus-btn-medium">{cardInsideAccordion.contactUser}</button>
                    </div>
                </NexusCardHeaderButton>
            </NexusCardHeader>
        </NexusCard>

    </NexusAccordionContent>
  </NexusAccordion>
)

}

export default CardInsideAccordionComponent;
