// ui-nexus-design-system/playbook/react/src/sb/components/input/02_maxLength.tsx
import React, { useState } from 'react';
import { NexusErrorMessage, NexusFormField, NexusInput, NexusLabel } from '@nexus/react';
import { maxLength } from '../../constants';

const InputWithFixedLength: React.FC = () => {
  const [value, setValue] = useState('');
  const [showError, setShowError] = useState(false);

  const onInputChangeHandler = (event: any) => {
    setShowError(event.target.value.length > 19);
    setValue(event.target.value);
  };

  return (
    <NexusFormField>
      <NexusLabel data-testid="label-first-name">{maxLength.text}</NexusLabel>
      <NexusInput
        data-testid="input-textbox-maxlength"
        value={value}
        onInput={(event: any) => onInputChangeHandler(event)}
        maxLength={20}
        placeholder={maxLength.placeholder}
      ></NexusInput>
      {showError ? <NexusErrorMessage data-testid="error-message">{maxLength.warning}</NexusErrorMessage> : ''}
    </NexusFormField>
  );
};

export default InputWithFixedLength;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/input/02_maxLength.component.ts
import { Component, OnInit } from '@angular/core';
import { maxLength } from '../../constants';

@Component({
  selector: 'app-input-examples-max-length',
  templateUrl: './02_maxLength.component.html'
})
export default class InputMaxLengthComponent implements OnInit {
  maxLength = maxLength.maxLength;

  maxLengthText = maxLength.text;

  maxLengthPlaceholder = maxLength.placeholder;

  maxLengthWarning = maxLength.warning;

  showErrorMessage = false;

  constructor() {}

  ngOnInit() {}

  onInput(value: string) {
    if (value.length >= this.maxLength) {
      this.showErrorMessage = true;
    } else {
      this.showErrorMessage = false;
    }
  }
}

<nexus-form-field>
  <nexus-label data-testid="label-first-name">{{ maxLengthText }}</nexus-label>
  <nexus-input
    data-testid="input-textbox-maxlen"
    [maxLength]="maxLength"
    [placeholder]="maxLengthPlaceholder"
    (input)="onInput($event.target.value)"
  ></nexus-input>
  <nexus-error-message *ngIf="showErrorMessage">{{ maxLengthWarning }}</nexus-error-message>
</nexus-form-field>
