// ui-nexus-design-system/playbook/react/src/sb/components/input/03_withNumber.tsx
import { NexusFormField, NexusInput, NexusLabel } from '@nexus/react';
import { withNumber } from '../../constants';
const InputWithNumberRange: React.FC = () => {
  return (
    <NexusFormField>
      <NexusLabel data-testid="label-first-name">{withNumber.text}</NexusLabel>
      <NexusInput
        data-testid="input-textbox-num"
        type="number"
        placeholder={withNumber.placeholder}
      ></NexusInput>
    </NexusFormField>
  );
};

export default InputWithNumberRange;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/input/03_withNumber.component.ts
import { Component } from '@angular/core';
import { withNumber } from '../../constants';
@Component({
  selector: 'app-input-examples-number',
  templateUrl: './03_withNumber.component.html'
})
export default class InputNumberComponent {
  text = withNumber.text;

  placeholder = withNumber.placeholder;
}

<nexus-label data-testid="label-num-field">{{ text }}</nexus-label>
<nexus-input data-testid="input-textbox-num" type="number" placeholder="Value"></nexus-input>
