// ui-nexus-design-system/playbook/react/src/sb/components/input/06_readOnly.tsx
import React from 'react';
import { NexusFormField, NexusInput, NexusLabel } from '@nexus/react';
import { readOnly } from '../../constants';
const ReadOnlyInputComponent: React.FC = () => {
  return (
    <NexusFormField>
      <NexusLabel data-testid="label-first-name">{readOnly.text}</NexusLabel>
      <NexusInput
        data-testid="input-textbox-readonly"
        readonly={true}
        value={readOnly.value}
        placeholder="Value..."
      ></NexusInput>
    </NexusFormField>
  );
};

export default ReadOnlyInputComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/input/06_readOnly.component.ts
import { Component } from '@angular/core';
import { readOnly } from '../../constants';
@Component({
  selector: 'app-input-examples-read-only',
  templateUrl: './06_readOnly.component.html'
})
export default class InputReadOnlyComponent {
  text = readOnly.text;

  value = readOnly.value;
}

<nexus-label data-testid="label-readonly-field">{{ text }}</nexus-label>
<nexus-input data-testid="input-textbox-readonly" readonly="true" [value]="value"></nexus-input>
