// ui-nexus-design-system/playbook/angular/src/app/sb/components/select/03_multiselect.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { multiselectOptions } from '../../constants';

@Component({
  selector: 'app-multiselect',
  templateUrl: './03_multiselect.component.html'
})
export default class MultiselectComponent implements OnInit {
  multiSelectOption = multiselectOptions;

  multiSelectDefaultPlaceholder = 'Please Select';

  delimiter = '::';

  objectKeys = Object.keys;

  singleSelectValue = '';

  multiSelectValue = '';

  constructor(private readonly changeDetectorRef: ChangeDetectorRef) { }

  ngOnInit(): void {
    this.multiSelectValue = this.setMultiSelectPlaceholder();
  }

  handleMultiSelectData = (eventData) => {
    if (eventData.detail.key) {
      eventData.preventDefault();
      const updateSelectState = [...this.multiSelectOption];
      const objIndex = updateSelectState.findIndex((obj) => obj.value === eventData.detail.key);
      updateSelectState[objIndex].isSelected = eventData.detail.status;
      this.multiSelectOption = [...updateSelectState];
      this.multiSelectValue = this.setMultiSelectPlaceholder();
      // console.log(updateSelectState[objIndex].isSelected);
      // console.log(this.multiSelectOption);
      // multiselectOptions.forEach((obj) => {
      //   if (obj.isSelected === true)
      //     this.selectOrDeSelectAllOptions(event)
      // });
    }
  };

  setMultiSelectPlaceholder = () => {
    const selecteddataObj = [];
    const delimiter = '::';
    this.multiSelectOption.forEach((element) => {
      if (element.isSelected) {
        selecteddataObj.push(element);
      }
    });
    const resStr = selecteddataObj.map((elem) => elem.label ? elem.label : elem.value).join(delimiter);

    return resStr ? resStr : this.multiSelectDefaultPlaceholder;
  };

  selectOrDeSelectAllOptions = (event) => {
    const updateSelectState = [...this.multiSelectOption];
    updateSelectState.forEach((obj) => obj.isSelected = event.target.checked);
    this.multiSelectOption = [...updateSelectState];
    this.multiSelectValue = this.setMultiSelectPlaceholder();
  };

  handleCloseEvent = (_event) => { };
}


    <nexus-form-field>
        <nexus-label>Select an option MultiSelect</nexus-label>
        <nexus-select type="custom" value="{{ multiSelectValue }}" delimiter="::"
            (triggerSelection)="handleMultiSelectData($event)" multiple (closeEvent)="handleCloseEvent($event)">
            <nexus-option (click)="selectOrDeSelectAllOptions($event)">
                <nexus-checkbox>Select All</nexus-checkbox>
            </nexus-option>
            <nexus-option *ngFor="let element of multiSelectOption" value="{{ element.value }}"
                selected="{{ element.isSelected }}">
                <nexus-checkbox checked="{{ element.isSelected }}">{{ element.value }}</nexus-checkbox>
            </nexus-option>
        </nexus-select>
    </nexus-form-field>

// ui-nexus-design-system/playbook/react/src/sb/components/select/03_multiselect.tsx
import React, { useState } from 'react';

import { NexusFormField, NexusLabel, NexusSelect, NexusOption, NexusCheckbox } from '@nexus/react';

const multiSelectOptions = [
    {
        value: 'Option 1',
        isSelected: false
    },
    {
        label: 'Option 2',
        value: 'Option2',
        isSelected: false
    },
    {
        label: 'Option 3',
        value: 'Option3',
        isSelected: false
    }
];

const SelectExampleComponent: React.FC = () => {
    const delimit = '::';

    const [multiSelectData, setMultiSelectData] = useState(multiSelectOptions);

    const setOptionStatusForMultiSelect = (eventData: { detail: { key: string; status: boolean } }) => {
        if (eventData.detail.key) {
            const updateSelectState = [...multiSelectData];
            const objIndex = updateSelectState.findIndex((obj) => obj.value === eventData.detail.key);
            updateSelectState[objIndex].isSelected = eventData.detail.status;
            setMultiSelectData([...updateSelectState]);
        }
    };

    const setSelectedValue = (data: any[]) => {
        const selecteddataObj: any[] = [];
        data.forEach((element: { isSelected: any }) => {
            if (element.isSelected) {
                selecteddataObj.push(element);
            }
        });
        return selecteddataObj
            .map(function (elem) {
                return elem.label ? elem.label : elem.value;
            })
            .join(delimit);
    };

    const selectAndDeSelectAllElements = (event: { target: { checked: boolean } }) => {
        const updateSelectState = [...multiSelectOptions];
        updateSelectState.forEach((obj) => (obj.isSelected = event.target.checked));
        setMultiSelectData([...updateSelectState]);
    };

    const setCloseEvent = (_eventData: any) => {
        //do something
    };

    return (
        <>
                        <NexusFormField>
                            <NexusLabel>Select an option MultiSelect</NexusLabel>
                            <NexusSelect
                                data-testid="custom-multi-select"
                                attr-id="custom-multi-select-1"
                                type="custom"
                                delimiter={delimit}
                                value={setSelectedValue(multiSelectData) ? setSelectedValue(multiSelectData) : 'Please Select'}
                                onTriggerSelection={(eventData: any) => {
                                    setOptionStatusForMultiSelect(eventData);
                                }}
                                multiple
                                onCloseEvent={(eventData: any) => setCloseEvent(eventData)}
                            >
                                {' '}
                                <NexusOption onInput={(event: any) => selectAndDeSelectAllElements(event)}>
                                    <NexusCheckbox data-testid="select-all" >Select All</NexusCheckbox>
                                </NexusOption>
                                {multiSelectData.map((element, idx) => (
                                    <NexusOption key={idx} value={element.value} label={element.label} selected={element.isSelected}>
                                        <NexusCheckbox checked={element.isSelected}>
                                            {element.label ? element.label : element.value}
                                        </NexusCheckbox>
                                    </NexusOption>
                                ))}
                            </NexusSelect>
                        </NexusFormField>
        </>
    );
};

export default SelectExampleComponent;
