// ui-nexus-design-system/playbook/angular/src/app/sb/components/checkbox/02_configuration.component.ts
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';
import { configuration } from '../../constants';
@Component({
  selector: 'app-checkbox-configuration',
  templateUrl: './02_configuration.component.html'
})
export default class ConfigurationComponent {
  checkedValue = new FormControl(false);

  indeterminateValue = new FormControl(false);

  disabledValue = new FormControl(false);

  check = configuration.check;

  indeterminate = configuration.indeterminate;

  disabled = configuration.disabled;

  text = configuration.title;

  example = configuration.example;

  exampleTitle = configuration.exampleTitle;
}

<p class="nexus-h5">{{ text }}</p>

<nexus-checkbox data-testid="Check" ngDefaultControl [formControl]="checkedValue" class="nexus-rhythm-2">{{
  check
}}</nexus-checkbox>
<nexus-checkbox
  data-testid="Indeterminate"
  ngDefaultControl
  [formControl]="indeterminateValue"
  class="nexus-rhythm-2"
  >{{ indeterminate }}</nexus-checkbox
>
<nexus-checkbox data-testid="Disabled" ngDefaultControl [formControl]="disabledValue" class="nexus-rhythm-2">{{
  disabled
}}</nexus-checkbox>

<p class="nexus-h5">{{ exampleTitle }}</p>

<nexus-checkbox
  id="example"
  [checked]="checkedValue.value"
  [indeterminate]="indeterminateValue.value"
  [disabled]="disabledValue.value"
>
  {{ example }}
</nexus-checkbox>

// ui-nexus-design-system/playbook/react/src/sb/components/checkbox/02_configuration.tsx
import React, { useState } from 'react';
import { configuration } from '../../constants';
import { NexusCheckbox } from '@nexus/react';

const SetupComponent: React.FC = () => {
  const [checkedValue, setCheckedValue] = useState(false);

  const [indeterminateValue, setIndeterminateValue] = useState(false);

  const [disabledValue, setDisabledValue] = useState(false);

  return (
    <>
      <p className="nexus-h5">{configuration.title}</p>

      <NexusCheckbox
        data-testid="Check"
        className="nexus-rhythm-2"
        onInput={(event: any) => setCheckedValue(event.target.checked)}
      >
        {configuration.check}
      </NexusCheckbox>
      <NexusCheckbox
        data-testid="Indeterminate"
        className="nexus-rhythm-2"
        onInput={(event: any) => setIndeterminateValue(event.target.checked)}
      >
        {configuration.indeterminate}
      </NexusCheckbox>
      <NexusCheckbox
        data-testid="Disabled"
        className="nexus-rhythm-2"
        onInput={(event: any) => setDisabledValue(event.target.checked)}
      >
        {configuration.disabled}
      </NexusCheckbox>

      <p className="nexus-h5">Example:</p>

      <NexusCheckbox
        checked={checkedValue}
        indeterminate={indeterminateValue}
        disabled={disabledValue}
        data-testid="Example"
        className="nexus-rhythm-2">{configuration.example}
      </NexusCheckbox>
    </>
  );
};

export default SetupComponent;
