// ui-nexus-design-system/playbook/react/src/components/badge/badge.tsx
import React from 'react';

import { NexusBadge } from '@nexus/react';
import { propVariant } from '@nexus/core/dist/types/components/nexus-badge/nexus-badge';

interface BadgeComponentProps {
  variant: propVariant;
}

const BadgeComponent: React.FC<BadgeComponentProps> = (props) => <NexusBadge {...props}>1</NexusBadge>;

BadgeComponent.defaultProps = {
  variant: 'default'
};

export default BadgeComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/badge/badge.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-badge',
  templateUrl: './badge.component.html'
})
export class BadgeComponent {
  @Input() variant: string = 'default';

  @Input() text: string = '1';

  @Input() overlap: boolean = false;
}

<nexus-badge [variant]="variant" [overlap]="overlap">1</nexus-badge>
