// ui-nexus-design-system/playbook/angular/src/app/sb/components/button/05_disabled.component.ts
import { Component } from '@angular/core';
import { disabled } from '../../constants';

@Component({
  selector: 'app-button-disabled',
  templateUrl: './05_disabled.component.html'
})
export default class DisabledComponent {
  disabled = disabled;
}

<div class="nexus-center-xs nexus-mt-5">
    <button data-testid="btnButton" class="nexus-btn nexus-btn-primary nexus-btn-large" disabled>{{disabled.text}}</button>
</div>

// ui-nexus-design-system/playbook/react/src/sb/components/button/05_disabled.tsx
import React from 'react';
import { disabled } from '../../constants';

const DisabledComponent: React.FC = () => {
  return (
    <div className="nexus-center-xs nexus-mt-5">
      <button className="nexus-btn nexus-btn-large nexus-btn-primary" disabled>
        {disabled.text}
      </button>
    </div>
  );
};

export default DisabledComponent;
