// ui-nexus-design-system/playbook/react/src/sb/components/card/01_card.tsx
import React from 'react';

import {
  NexusCard,
  NexusCardAvatar,
  NexusCardFooter,
  NexusCardHeader,
  NexusCardHeaderButton,
  NexusCardHeaderDetails,
  NexusCardHeaderSubtitle,
  NexusCardHeaderTitle,
  NexusIcon
} from '@nexus/react';
import PropTypes from 'prop-types';
import { DefaultCard } from '../../constants';
import CardHeaderImage from '@nexus/core/dist/assets/images/card-header-image.png';


const CardComponent: React.FC = (props) => {
  const {
    bgColor = '',
    bgImage = CardHeaderImage,
    clickable = false,
    height = ''} = { ...props };
  return (
    <div className="nexus-row nexus-center-xs nexus-mt-2">
      <div className="nexus-col-xs-6">
        <NexusCard bgColor={bgColor} clickable={clickable} height={height}>
          <NexusCardAvatar>
            <img src={bgImage === '' ? DefaultCard.profile : bgImage} alt={DefaultCard.name} />
          </NexusCardAvatar>
          <NexusCardHeader>
            <NexusCardHeaderTitle>{DefaultCard.name}</NexusCardHeaderTitle>
            <NexusCardHeaderSubtitle>{DefaultCard.cardTitle}</NexusCardHeaderSubtitle>
            <NexusCardHeaderDetails>{DefaultCard.lastLogin}</NexusCardHeaderDetails>
            <NexusCardHeaderButton>
              <button className="nexus-btn-icon" id="btn" title="btn">
                <NexusIcon src={DefaultCard.src} />
              </button>
            </NexusCardHeaderButton>
          </NexusCardHeader>
          <NexusCardFooter>
            <button className="nexus-btn-primary nexus-btn-medium">{DefaultCard.viewProfile}</button>
            <button className="nexus-btn nexus-btn-medium">{DefaultCard.userProfile}</button>
          </NexusCardFooter>
        </NexusCard>
      </div>
    </div>
  );
};

CardComponent.propTypes = {
  bgColor: PropTypes.string,
  bgImage: PropTypes.string,
  clickable: PropTypes.bool,
  height: PropTypes.string
}

CardComponent.defaultProps = {
  bgColor: '',
  bgImage: CardHeaderImage,
  clickable: false,
  height: ''
};

export default CardComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/card/01_card.component.ts
import { Component, Input } from '@angular/core';
import { DefaultCard } from '../../constants';

@Component({
  selector: 'app-card',
  templateUrl: './01_card.component.html'
})
export default class CardComponent {
  @Input() bgColor: string = '';

  @Input() bgImage: string = DefaultCard.profile;

  @Input() clickable: boolean = false;

  @Input() height: string = '';

  defaultCard = DefaultCard;
}

<div class="nexus-row nexus-center-xs nexus-mt-2">
    <div class="nexus-col-xs-6">
      <nexus-card [bgColor]="bgColor" [clickable]="clickable" [height]="height">
        <nexus-card-avatar>
          <img [src]="bgImage === '' ? './assets/images/card-header-image.png':bgImage" [alt]="defaultCard.name" />
        </nexus-card-avatar>
        <nexus-card-header>
          <nexus-card-header-title>{{defaultCard.name}}</nexus-card-header-title>
          <nexus-card-header-subtitle>{{defaultCard.cardTitle}}</nexus-card-header-subtitle>
          <nexus-card-header-details>{{defaultCard.lastLogin}}</nexus-card-header-details>
          <nexus-card-header-button>
            <button class="nexus-btn-icon" id="btn" title="btn">
              <nexus-icon [src]="defaultCard.src"></nexus-icon>
            </button>
          </nexus-card-header-button>
        </nexus-card-header>
        <nexus-card-footer>
          <button class="nexus-btn-primary nexus-btn-medium">{{defaultCard.viewProfile}}</button>
          <button class="nexus-btn nexus-btn-medium">{{defaultCard.userProfile}}</button>
        </nexus-card-footer>
      </nexus-card>
    </div>
  </div>
