// ui-nexus-design-system/playbook/react/src/sb/components/card/03_fullBackgroundImage.tsx
import React from 'react';
import { NexusCard, NexusCardBody } from '@nexus/react';
import { Link } from 'react-router-dom';
import { FullBackground } from '../../constants';

const FullBackgroundImageComponent: React.FC = () => (

    <div className="nexus-row">
      <div className="nexus-col-xs-4 nexus-col-sm-4 nexus-col-md-6 nexus-col-lg-8 nexus-col-xl-8">
        <NexusCard data-testid="full-bg-image" bg-image={FullBackground.cardBgImage} height="316px" clickable={true}>
          <Link to="" className="nexus-visually-hidden">{FullBackground.readMore}</Link>
          <NexusCardBody>
            <h2 data-testid="full-bg-image-overline" className="nexus-overline nexus-rhythm-1">{FullBackground.nextStep}</h2>
            <h3 data-testid="full-bg-image-body" className="nexus-h6 nexus-rhythm-1">{FullBackground.detail}</h3>
          </NexusCardBody>
        </NexusCard>
      </div>
    </div>
);

export default FullBackgroundImageComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/card/03_fullBackgroundImage.component.ts
import { Component } from '@angular/core';
import { FullBackground } from '../../constants';

@Component({
  selector: 'app-card-with-bg-image',
  templateUrl: './03_fullBackgroundImage.component.html'
})
export default class CardWithFullBackgroundImageComponent {
  fullbackground = FullBackground;
}

<div class="nexus-row">
    <div class="nexus-col-xs-6 nexus-col-sm-6 nexus-col-md-6 nexus-col-lg-6 nexus-col-xl-6">
        <nexus-card [bgImage]="fullbackground.cardBgImage" height="316px" clickable="true">
            <a href="javascript:void(0)" class="nexus-visually-hidden">{{fullbackground.readMore}}</a>
            <nexus-card-body>
                <h2 class="nexus-overline nexus-rhythm-1">{{fullbackground.nextStep}}</h2>
                <h3 class="nexus-h6 nexus-rhythm-1">{{fullbackground.detail}}</h3>
            </nexus-card-body>
        </nexus-card>
    </div>
</div>
