// ui-nexus-design-system/playbook/react/src/sb/components/card/04_bodyWithImage.tsx
import React from 'react';
import { NexusCard, NexusCardBody, NexusCardBodyImage, NexusCardFooter } from '@nexus/react';
import CardImage from '@nexus/core/dist/assets/images/card-image.jpg';
import { BodyWithImage } from '../../constants';

const BodyWithImageComponent: React.FC = () => (
  <div className="nexus-row">
    <div className="nexus-col-xs-4 nexus-col-sm-4 nexus-col-md-6 nexus-col-lg-8 nexus-col-xl-8">
      <NexusCard>
        <NexusCardBody>
          <NexusCardBodyImage>
            <img src={CardImage} alt="Alt Text" />
          </NexusCardBodyImage>
          <p data-testid="body-with-image-caption" className="nexus-caption-copy nexus-rhythm-4">{BodyWithImage.caption}</p>
          <h2 data-testid="body-with-image-body" className="nexus-h5">{BodyWithImage.subTitle}</h2>
          <p data-testid="body-with-image-bodyend">{BodyWithImage.detail}</p>
        </NexusCardBody>
        <NexusCardFooter>
          <button data-testid="body-with-image-btn-MoreInfo" className="nexus-btn-primary nexus-btn-medium">{BodyWithImage.moreInfo}</button>
          <button data-testid="body-with-image-btn-Dismiss" className="nexus-link">{BodyWithImage.dismiss}</button>
        </NexusCardFooter>
      </NexusCard>
    </div>
  </div>
);

export default BodyWithImageComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/card/04_bodyWithImage.component.ts
import { Component } from '@angular/core';
import { BodyWithImage } from '../../constants';

@Component({
  selector: 'app-card-with-body-bg-image',
  templateUrl: './04_bodyWithImage.component.html'
})
export default class CardWithImageOnBodyComponent {
  bodyWithImage = BodyWithImage;
}

<div class="nexus-row">
    <div class="nexus-col-xs-6 nexus-col-sm-6 nexus-col-md-6 nexus-col-lg-6 nexus-col-xl-6">
        <nexus-card>
            <nexus-card-body>
                <nexus-card-body-image>
                    <img [src]="bodyWithImage.bgImage" alt="Alt Text" />
                </nexus-card-body-image>
                <p class="nexus-caption-copy nexus-rhythm-4">{{bodyWithImage.caption}}</p>
                <h2 class="nexus-h5">{{bodyWithImage.subTitle}}</h2>
                <p>{{bodyWithImage.detail}}</p>
            </nexus-card-body>
            <nexus-card-footer>
                <button class="nexus-btn-primary nexus-btn-medium">{{bodyWithImage.moreInfo}}</button>
                <button class="nexus-link">{{bodyWithImage.dismiss}}</button>
            </nexus-card-footer>
        </nexus-card>
    </div>
</div>
