// ui-nexus-design-system/playbook/react/src/components/error-message/error-message.tsx
import React from 'react';

import { NexusErrorMessage, NexusFormField, NexusInput, NexusLabel } from '@nexus/react';

const ErrorComponent: React.FC = () => (
  <NexusFormField>
    <NexusLabel data-testid="label-first-name">First name</NexusLabel>
    <NexusInput data-testid="input-text-box" value=""></NexusInput>
    <NexusErrorMessage data-testid="error-message">Please enter a first name.</NexusErrorMessage>
  </NexusFormField>
);

export default ErrorComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/error-message/error-message.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-error-message',
  templateUrl: './error-message.component.html',
  styleUrls: ['./error-message.component.scss']
})
export class ErrorMessageComponent {
}

<nexus-form-field>
  <nexus-label data-testid="label-first-name">First name</nexus-label>
  <nexus-input data-testid="input-text-box" value=""></nexus-input>
  <nexus-error-message data-testid="error-message">Please enter a first name.</nexus-error-message>
</nexus-form-field>
