// ui-nexus-design-system/playbook/react/src/sb/components/textarea/01_textarea.tsx
import React from 'react';
import { textarea } from '../../constants';

import { NexusTextarea, NexusFormField, NexusLabel } from '@nexus/react';

interface TextAreaComponentProps {
    disabled: boolean;
    maxLength: number;
    minLength: number;
    cols: number;
    rows: number;
    placeholder: string;
    required: boolean;
    value: string;
}

const TextAreaComponent: React.FC<TextAreaComponentProps> = (props) => {
    return (
        <NexusFormField>
            <NexusLabel data-testid="textarea-header">{textarea.text}</NexusLabel>
            <NexusTextarea {...props} data-testid="textarea-content" value=""></NexusTextarea>
        </NexusFormField>
    );
};

TextAreaComponent.defaultProps = {
    disabled: false,
    maxLength: 100,
    minLength: 0,
    cols: 100,
    rows: 3,
    placeholder: '',
    required: false,
    value: ''
};

export default TextAreaComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/textarea/01_textarea.component.ts
import { Component, Input } from '@angular/core';
import { textarea } from '../../constants';


@Component({
  selector: 'app-textarea',
  templateUrl: './01_textarea.component.html'
})
export default class TextareaComponent {
  @Input() attrId: string = '';

  @Input() disabled: boolean = false;

  @Input() maxLength: number;

  @Input() minLength: number;

  @Input() cols: number = 100;

  @Input() rows: number = 3;

  @Input() placeholder: string = '';

  @Input() required: boolean = false;

  @Input() value: string = '';

  textarea = textarea;
}

<nexus-form-field>
  <nexus-label data-testid="textarea-header">{{textarea.text}}</nexus-label>
  <nexus-textarea data-testid="textarea-content" [attrId]="attrId" [disabled]="disabled" [maxLength]="maxLength"
    [minLength]="minLength" [cols]="cols" [rows]="rows" [placeholder]="placeholder" [required]="required"
    [value]="value"></nexus-textarea>
</nexus-form-field>
