// ui-nexus-design-system/playbook/angular/src/app/components/pin-entry-examples/pin-entry-examples.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-pin-entry-examples',
  templateUrl: './pin-entry-examples.component.html',
  styleUrls: ['./pin-entry-examples.component.scss']
})
export class PinEntryExamplesComponent implements OnInit {
  constructor() {
    // This is intentional
  }

  ngOnInit(): void {
    // This is intentional
  }
}

<p class="nexus-h5">Default</p>
<nexus-pin-entry data-testid="pin-entry-default"></nexus-pin-entry>

<p class="nexus-h5">Custom Length</p>
<nexus-pin-entry data-testid="pin-entry-customLen" length="6"></nexus-pin-entry>

<p class="nexus-h5">Disabled</p>
<nexus-pin-entry data-testid="pin-entry-disabled" length="3" disabled></nexus-pin-entry>

// ui-nexus-design-system/playbook/react/src/components/pin-entry/pin-entry-examples.tsx
import React from 'react';

import { NexusPinEntry } from '@nexus/react';

const PinEntryExampleComponent: React.FC = () => (
  <>
    <p className="nexus-h5">Default</p>
    <NexusPinEntry data-testid="pin-entry-default"></NexusPinEntry>

    <p className="nexus-h5">Custom Length</p>
    <NexusPinEntry data-testid="pin-entry-customLen" length={6}></NexusPinEntry>

    <p className="nexus-h5">Disabled</p>
    <NexusPinEntry data-testid="pin-entry-disabled" length={3} disabled></NexusPinEntry>
  </>
);

export default PinEntryExampleComponent;
