// ui-nexus-design-system/playbook/react/src/sb/components/badge/01_badge.tsx
import React from 'react';
import { NexusBadge } from '@nexus/react';
import { propVariant } from '@nexus/core/dist/types/components/nexus-badge/nexus-badge';

export const BadgeComponent: React.FC<{variant: propVariant, overlap: boolean, label: string}> = (props) => {
  const label = props.label;

  return(<div className='nexus-center-xs nexus-mt-5'>
    <NexusBadge {...props} data-testid="nexus-badge">
      <span className="nexus-body">{label}</span>
    </NexusBadge>
  </div>);
};

export default BadgeComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/badge/01_badge.component.ts
import { Component, Input } from '@angular/core';
import { badge } from '../../constants';

@Component({
  selector: 'app-badge',
  templateUrl: './01_badge.component.html'
})
export default class BadgeComponent {
  @Input() variant: string = 'default';

  @Input() label = badge.text;

  @Input() overlap: boolean = false;
}

<div class="nexus-center-xs nexus-mt-5">
    <nexus-badge data-testid="nexus-badge" [variant]="variant" [overlap]="overlap">
        <span class="nexus-body">{{label}}</span>
    </nexus-badge>
</div>
