// ui-nexus-design-system/playbook/react/src/sb/components/badge/03_buttonOverlay.tsx
import React from 'react';
import { buttonOverlay } from '../../../../../stories/data/badge';
import { NexusBadge } from '@nexus/react';
import PropTypes from 'prop-types';

export const ButtonOverlayComponent: React.FC = (props) => (
    <div className='nexus-mt-5 nexus-center-xs'>
      <button className="nexus-btn">
        {buttonOverlay.text}
        <NexusBadge data-testid="badge-on-button" {...props} variant='default' overlap={true}>
          {buttonOverlay.label}
        </NexusBadge>
      </button>
    </div>
);

ButtonOverlayComponent.propTypes = {
  variant: PropTypes.string,
};

ButtonOverlayComponent.defaultProps = {
  variant: 'default'
};

export default ButtonOverlayComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/badge/03_buttonOverlay.component.ts
import { Component } from '@angular/core';
import { buttonOverlay } from '../../constants';

@Component({
  selector: 'app-button-overlay',
  templateUrl: './03_buttonOverlay.component.html',
  styleUrls: []
})
export default class ButtonOverlayComponent {
  text = buttonOverlay.text;

  label = buttonOverlay.label;
}

<div class="nexus-mt-5 nexus-center-xs">
  <button class="nexus-btn">
    {{text}}
    <nexus-badge overlap="true">{{label}}</nexus-badge>
  </button>
</div>
