// ui-nexus-design-system/playbook/react/src/components/dropdown/dropdown-examples.tsx
import { NexusDropdown, NexusIcon, NexusOption } from '@nexus/react';

import NavigationIcMoreVert24px from '@nexus/core/dist/assets/icons/navigation/ic_more_vert_24px.svg';


const DropdownExampleComponent: React.FC = () => {
  return (
    <>
      <p className="nexus-h6">Basic Dopdown examples</p>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint
        <NexusDropdown placement={"right"} dropdown-type={"basic"} height={150} width={180}>
          <NexusIcon slot={"trigerelement"} id={"iconId"} src={NavigationIcMoreVert24px}></NexusIcon>
          <NexusOption>Option 1</NexusOption>
          <NexusOption>Option 2</NexusOption>
          <NexusOption>Option 3</NexusOption>
        </NexusDropdown>
        dignissimos.
      </p>

      <p>Lorem ipsum
        <NexusDropdown placement={"left"} dropdown-type={"basic"} height={150} width={220}>
          <NexusIcon slot={"trigerelement"} id={"iconId"} src={NavigationIcMoreVert24px}></NexusIcon>
          <NexusOption label="Option 1" value="Option1">Option 1</NexusOption>
          <NexusOption label="Option 2" value="Option2">Option 2</NexusOption>
          <NexusOption label="Option 3" value="Option3">Option 3</NexusOption>
        </NexusDropdown>
        dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint dignissimos.</p>

      <p>Lorem ipsum dolor sit amet
        <NexusDropdown placement={"center"} dropdown-type={"basic"} height={150} width={180}>
          <NexusIcon slot={"trigerelement"} id={"iconId"} src={NavigationIcMoreVert24px}></NexusIcon>
          <NexusOption label="Option 1" value="Option1">Option 1</NexusOption>
          <NexusOption label="Option 2" value="Option2">Option 2</NexusOption>
          <NexusOption label="Option 3" value="Option3">Option 3</NexusOption>
          <NexusOption label="Option 4" value="Option4">Option 4</NexusOption>
          <NexusOption label="Option 5" value="Option5">Option 5</NexusOption>
          <NexusOption label="Option 6" value="Option6">Option 6</NexusOption>
          <NexusOption label="Option 7" value="Option7">Option 7</NexusOption>
        </NexusDropdown>
        consectetur, adipisicing elit. A quas nam doloremque sint dignissimos.</p>
    </>
  );
};

export default DropdownExampleComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/dropdown-examples/dropdown-examples.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-dropdown-examples',
  templateUrl: './dropdown-examples.component.html'
})
export class DropdownExamplesComponent {}

<p class="nexus-h6">Basic Dopdown Examples</p>

<p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint
    <nexus-dropdown dropdown-type="basic" placement="right" height="150" width="180">
        <nexus-icon slot="trigerelement" src="./assets/icons/navigation/ic_more_vert_24px.svg"></nexus-icon>
        <nexus-option label="Option 1" value="Option1">Option 1</nexus-option>
        <nexus-option label="Option 2" value="Option2">Option 2</nexus-option>
        <nexus-option label="Option 3" value="Option3">Option 3</nexus-option>
    </nexus-dropdown>
    dignissimos.
</p>

<p>Lorem ipsum
    <nexus-dropdown dropdown-type="basic" placement="left" height="150" width="220">
        <nexus-icon slot="trigerelement" src="./assets/icons/navigation/ic_more_vert_24px.svg"></nexus-icon>
        <nexus-option label="Option 1" value="Option1">Option 1</nexus-option>
        <nexus-option label="Option 2" value="Option2">Option 2</nexus-option>
        <nexus-option label="Option 3" value="Option3">Option 3</nexus-option>
    </nexus-dropdown>
    dolor sit amet consectetur, adipisicing elit. A quas nam doloremque sint dignissimos.
</p>

<p>Lorem ipsum dolor sit amet
    <nexus-dropdown dropdown-type="basic" placement="right" height="150" width="180">
        <nexus-icon slot="trigerelement" src="./assets/icons/navigation/ic_more_vert_24px.svg"></nexus-icon>
        <nexus-option label="Option 1" value="Option1">Option 1</nexus-option>
        <nexus-option label="Option 2" value="Option2">Option 2</nexus-option>
        <nexus-option label="Option 3" value="Option3">Option 3</nexus-option>
        <nexus-option label="Option 4" value="Option4">Option 4</nexus-option>
        <nexus-option label="Option 5" value="Option5">Option 5</nexus-option>
        <nexus-option label="Option 6" value="Option6">Option 6</nexus-option>
        <nexus-option label="Option 7" value="Option7">Option 7</nexus-option>
    </nexus-dropdown>
    consectetur, adipisicingelit. A quas nam doloremque sint dignissimos.
</p>
