// ui-nexus-design-system/playbook/angular/src/app/components/tooltip-examples/tooltip-examples.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-tooltip-examples',
  templateUrl: './tooltip-examples.component.html',
  styleUrls: ['./tooltip-examples.component.scss']
})
export class TooltipExamplesComponent {}

<p class="nexus-h5">Custom Content</p>

<p class="nexus-h6">Tooltip</p>
<p>
  Lorem ipsum dolor sit amet, <nexus-tooltip>
    <nexus-tooltip-trigger>
      consectetur
    </nexus-tooltip-trigger>

    <nexus-tooltip-content>Default Tooltip Content </nexus-tooltip-content>
  </nexus-tooltip> adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
</p>

<p class="nexus-h6">Tooltip Placement</p>
<p>
  Lorem ipsum dolor sit amet, <nexus-tooltip placement="bottom">
    <nexus-tooltip-trigger>
      consectetur
    </nexus-tooltip-trigger>

    <nexus-tooltip-content>Tooltip Content on bottom</nexus-tooltip-content>
  </nexus-tooltip> adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
</p>
<p>
  Lorem ipsum dolor sit amet, <nexus-tooltip placement="top">
    <nexus-tooltip-trigger>
      consectetur
    </nexus-tooltip-trigger>

    <nexus-tooltip-content>Tooltip Content on top</nexus-tooltip-content>
  </nexus-tooltip> adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
</p>
<p>
  Lorem ipsum dolor sit amet, <nexus-tooltip placement="right">
  <nexus-tooltip-trigger>
    consectetur
  </nexus-tooltip-trigger>

  <nexus-tooltip-content>Tooltip Content on right</nexus-tooltip-content>
</nexus-tooltip> adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
</p>
<p>
  Lorem ipsum dolor sit amet, <nexus-tooltip placement="left">
    <nexus-tooltip-trigger>
      consectetur
    </nexus-tooltip-trigger>
  
    <nexus-tooltip-content>Tooltip Content on left</nexus-tooltip-content>
  </nexus-tooltip> adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
</p>
<p>
  Lorem ipsum dolor sit amet, <nexus-tooltip placement="left">
  <nexus-tooltip-trigger>
    consectetur Tooltip Content on left, auto calculates in case of overflow.<br/>Tooltip Content on left, auto calculates in case of overflow.<br />
  </nexus-tooltip-trigger>

  <nexus-tooltip-content>Tooltip Content on left, auto calculates in case of overflow.</nexus-tooltip-content>
</nexus-tooltip> adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
</p>

<p class="nexus-h6">Tooltip click disabled</p> 
<p>
  This is a , <nexus-tooltip allow-click="false" placement="top">
    <nexus-tooltip-trigger>
      tooltip
    </nexus-tooltip-trigger>

    <nexus-tooltip-content>Tooltip Content</nexus-tooltip-content>
  </nexus-tooltip> that has click disabled.
</p>

// ui-nexus-design-system/playbook/react/src/components/tooltip/tooltip-examples.tsx
import React from 'react';

import { NexusTooltip, NexusTooltipTrigger, NexusTooltipContent } from '@nexus/react';

const TooltipExampleComponent: React.FC = () => (
  <>
    <p className="nexus-h5">Custom Content</p>

    <p className="nexus-h6">Tooltip</p>
    <p data-testid="tooltip-body">
      Lorem ipsum dolor sit amet,{' '}
      <NexusTooltip>
        <NexusTooltipTrigger data-testid="tooltip-default">consectetur</NexusTooltipTrigger>

        <NexusTooltipContent data-testid="tooltip-content-default">Default Tooltip Content</NexusTooltipContent>
      </NexusTooltip>{' '}
      adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
    </p>

    <p className="nexus-h6">Tooltip Placement (top, right, bottom, left)</p>
    <p>
      Lorem ipsum dolor sit amet,{' '}
      <NexusTooltip placement="bottom">
        <NexusTooltipTrigger data-testid="tooltip-bottom">consectetur</NexusTooltipTrigger>

        <NexusTooltipContent data-testid="tooltip-content-bottom">Tooltip Content on bottom</NexusTooltipContent>
      </NexusTooltip>{' '}
      adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
    </p>
    <p>
      Lorem ipsum dolor sit amet,{' '}
      <NexusTooltip placement="top">
        <NexusTooltipTrigger data-testid="tooltip-top">consectetur</NexusTooltipTrigger>

        <NexusTooltipContent data-testid="tooltip-content-top">Tooltip Content on top</NexusTooltipContent>
      </NexusTooltip>{' '}
      adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
    </p>
    <p>
      Lorem ipsum dolor sit amet,{' '}
      <NexusTooltip placement="right">
        <NexusTooltipTrigger data-testid="tooltip-right">consectetur</NexusTooltipTrigger>

        <NexusTooltipContent data-testid="tooltip-content-right">Tooltip Content on right</NexusTooltipContent>
      </NexusTooltip>{' '}
      adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
    </p>
    <p>
      Donec massa dui, bibendum et bibendum ut, facilisis nec lorem. Lorem ipsum dolor sit amet,{' '}
      <NexusTooltip placement="left">
        <NexusTooltipTrigger data-testid="tooltip-left">consectetur</NexusTooltipTrigger>

        <NexusTooltipContent>Tooltip Content on left</NexusTooltipContent>
      </NexusTooltip>{' '}
      adipiscing elit.
    </p>
    <p>
      Lorem ipsum dolor sit amet,{' '}
      <NexusTooltip placement="left">
        <NexusTooltipTrigger>consectetur Tooltip Content on left, auto calculates in case of overflow.</NexusTooltipTrigger>

        <NexusTooltipContent data-testid="tooltip-content-left">
          Tooltip Content on left, auto calculates in case of overflow.
        </NexusTooltipContent>
      </NexusTooltip>{' '}
      adipiscing elit. Donec massa dui, bibendum et bibendum ut, facilisis nec lorem.
      <br />Tooltip Content on left, auto calculates in case of overflow. <br/>
    </p>

    <p className="nexus-h6">Tooltip click disabled</p>
    <p>
      This is a ,{' '}
      <NexusTooltip allow-click="false" placement="top">
        <NexusTooltipTrigger>tooltip</NexusTooltipTrigger>

        <NexusTooltipContent data-testid="tooltip-content-Disabled">Tooltip Content</NexusTooltipContent>
      </NexusTooltip>{' '}
      that has click disabled.
    </p>
  </>
);

export default TooltipExampleComponent;
