// ui-nexus-design-system/playbook/angular/src/app/components/tooltip/tooltip.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tooltip',
  templateUrl: './tooltip.component.html',
  styleUrls: ['./tooltip.component.scss']
})
export class TooltipComponent {
  @Input() placement: string = 'right';

  @Input() allowClick: boolean = true;
}

<nexus-tooltip [placement]="placement" [allowClick]="allowClick">
  <nexus-tooltip-trigger>
    <nexus-icon src="./assets/icons/action/ic_help_outline_24px.svg"></nexus-icon>
    <span class="nexus-visually-hidden">Help</span>
  </nexus-tooltip-trigger>

  <nexus-tooltip-content>Tooltip Content</nexus-tooltip-content>
</nexus-tooltip>

// ui-nexus-design-system/playbook/react/src/components/tooltip/tooltip.tsx
import React from 'react';

import { NexusTooltip, NexusTooltipTrigger, NexusIcon, NexusTooltipContent } from '@nexus/react';
import ActionIcHelpOutline24px from '@nexus/core/dist/assets/icons/action/ic_help_outline_24px.svg';

interface TooltipComponentProps {
  allowClick: boolean;
  placement: 'top' | 'bottom' | 'left' | 'right';
}

const TooltipComponent: React.FC<TooltipComponentProps> = (props) => {
  const { allowClick, placement } = { ...props };

  return (
    <NexusTooltip allowClick={allowClick} placement={placement}>
      <NexusTooltipTrigger>
        <NexusIcon data-testid="tooltip-icon" src={ActionIcHelpOutline24px}></NexusIcon>
        <span data-testid="tooltip-content-main" className="nexus-visually-hidden">
          Help
        </span>
      </NexusTooltipTrigger>

      <NexusTooltipContent data-testid="tooltip-content">Tooltip Content</NexusTooltipContent>
    </NexusTooltip>
  );
};

TooltipComponent.defaultProps = {
  allowClick: true,
  placement: 'bottom'
};

export default TooltipComponent;
