// ui-nexus-design-system/playbook/react/src/sb/components/loader/02_overlay.tsx
import React from 'react';
import { loaderOverlay } from '../../constants';
import { NexusLoader } from '@nexus/react';

const LoaderOverButtonComponent: React.FC = () => (
  <div className='nexus-center-xs nexus-pt-5'>
    <button className="nexus-btn nexus-btn-large nexus-btn-primary">
      <NexusLoader show={loaderOverlay.show}></NexusLoader>
      {loaderOverlay.text}
    </button>
  </div>
);

export default LoaderOverButtonComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/loader/02_overlay.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-loader-with-overlay',
  templateUrl: './02_overlay.component.html'
})
export default class LoaderOverlayComponent {
}

<div class='nexus-center-xs nexus-pt-5'>
  <button class="nexus-btn nexus-btn-large nexus-btn-primary">
    <nexus-loader [show]="true"></nexus-loader>In Progress</button>
</div>
