// ui-nexus-design-system/playbook/react/src/components/tree/tree.tsx
import React from 'react';

import { NexusTree, NexusTreeTrigger, NexusTreeContent } from '@nexus/react';

interface TreeComponentProps {
  open: boolean;
}

const TreeComponent: React.FC<TreeComponentProps> = (props) => {
  const { open } = { ...props };

  return (
    <NexusTree open={open}>
      <NexusTreeTrigger data-testid="tree-trigger">Click to expand</NexusTreeTrigger>
      <NexusTreeContent>
        <ul data-testid="tree-content-item">
          <li>Tree content item</li>
          <li>Tree content item</li>
          <li>Tree content item</li>
        </ul>
      </NexusTreeContent>
    </NexusTree>
  );
};

TreeComponent.defaultProps = {
  open: false
};

export default TreeComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/tree/tree.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-tree',
  templateUrl: './tree.component.html',
  styleUrls: ['./tree.component.scss']
})
export class TreeComponent {
  @Input() open: boolean = false;
}

<nexus-tree [open]="open">
  <nexus-tree-trigger>Click to expand</nexus-tree-trigger>
  <nexus-tree-content>
    <ul>
      <li>Tree content item</li>
      <li>Tree content item</li>
      <li>Tree content item</li>
    </ul>
  </nexus-tree-content>
</nexus-tree>
