// ui-nexus-design-system/playbook/react/src/sb/components/file-upload/01_file-upload.tsx
import { useState } from 'react';
import PropTypes from 'prop-types';
import { NexusFileUpload, NexusFormField, NexusChipGroup, NexusChip } from '@nexus/react';


const FileUploadComponent: React.FC = (props) => {
  const {
    attrId = 'nexus-file-upload',
    disabled = false,
    multiple = false,
    required = false,
    accept = '*'
  } = { ...props };
  const [queue, setQueue] = useState<any>([]);
  const [uploaded, setUploaded] = useState<{ name: string; uploaded: boolean }[]>([]);

  const addToQueueUnique = (
    prevQueue: { name: string; uploaded: boolean }[],
    newFiles: { name: string; uploaded: boolean }[]
  ) => {
    const ids = new Set(prevQueue.map((prevFile: { name: string }) => prevFile.name));

    return [...prevQueue, ...newFiles.filter((newFile: { name: string }) => !ids.has(newFile.name))];
  };

  const handleChange = (event: any) => {
    setQueue(addToQueueUnique(queue, [...event.target.files]));
  };

  const handleSubmit = (event: any) => {
    event.preventDefault();
    const uploadURL = 'https://httpstat.us/200';
    const formData = new FormData();
    formData.append('files', queue);

    // Fake API request that returns a 200
    // Replace this with your API method
    fetch(uploadURL, {
      method: 'POST',
      body: formData
    })
      .then((response) => response)
      .then(() => {
        const nextQueue = queue.map((file: { name: string; uploaded: boolean }) => {
          file.uploaded = true;

          return file;
        });

        setQueue([]);
        setUploaded(addToQueueUnique(uploaded, nextQueue));
      });
  };

  const removeFile = (removedFile: { name: string }) => {
    setQueue(queue.filter((file: { name: string }) => file.name !== removedFile.name));
  };

  const removeUploadedFile = (removedFile: { name: string }) => {
    setUploaded(uploaded.filter((file: { name: string }) => file.name !== removedFile.name));
  };

  const renderQueue = (queue1: any, cb: any) =>
    queue1.map((file: { name: string; uploaded: boolean }) => (
      <NexusChip
        data-testid="doc-uploaded-chip"
        aria-label={`Click to remove file - ${file.name}`}
        removable={true}
        key={file.name}
        success={file.uploaded}
        onClick={() => cb(file)}
      >
        {file.name}
      </NexusChip>
    ));

  const fileDrop = (event: any) => {
    event.preventDefault();
    setQueue(addToQueueUnique(queue, [...event.dataTransfer.files]));
  };

  return (
    <div>
      <form onSubmit={(event) => handleSubmit(event)}>
        <NexusFormField>
          <NexusFileUpload
            attrId={attrId}
            disabled={disabled}
            multiple={multiple}
            required={required}
            accept={accept}
            onInput={(event: any) => handleChange(event)}
            onDrop={(event: any) => fileDrop(event)}
          >
            <p>Drop File here or click to upload</p>
            <p>Max file size is 25MB</p>
          </NexusFileUpload>
        </NexusFormField>

        {queue.length > 0 && (
          <NexusChipGroup className="nexus-rhythm-4">
            {/* span required for react to render dynamic content into the correct slot */}
            <span>{renderQueue(queue, removeFile)}</span>
          </NexusChipGroup>
        )}

        {uploaded.length > 0 && (
          <NexusChipGroup className="nexus-rhythm-4">
            {/* span required for react to render dynamic content into the correct slot */}
            <span>{renderQueue(uploaded, removeUploadedFile)}</span>
          </NexusChipGroup>
        )}

        <button type="submit" className="nexus-btn-primary">
          Upload
        </button>
      </form>
    </div>
  );
};

FileUploadComponent.propTypes = {
  attrId: PropTypes.string,
  disabled: PropTypes.bool,
  multiple: PropTypes.bool,
  required: PropTypes.bool
};

export default FileUploadComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/file-upload/01_file-upload.component.ts
import { Component, Input } from '@angular/core';
import { fileUpload } from '../../constants';


@Component({
  selector: 'app-file-upload',
  templateUrl: './01_file-upload.component.html'
})
export default class FileUploadComponent {
  @Input() accept: String = '';

  @Input() attrId: String = '';

  @Input() disabled: boolean = true;

  @Input() multiple: boolean = false;

  @Input() required: boolean = false;

  fileUpload = fileUpload;

  public queue: any = [];

  public uploaded: any = [];

  public handleChange = (event) => {
    this.queue = this.addToQueueUnique(this.queue, [...event.target.files]);
  };

  public handleSubmit = (event) => {
    event.preventDefault();
    const uploadURL = 'https://httpstat.us/200';
    const formData = new FormData();
    formData.append('files', this.queue);

    // Fake API request that returns a 200
    // Replace this with your API method
    fetch(uploadURL, {
      method: 'POST',
      body: formData
    })
      .then((response) => response)
      .then(() => {
        const nextQueue = this.queue.map((file) => {
          file.uploaded = true;

          return file;
        });

        this.queue = [];
        this.uploaded = this.addToQueueUnique(this.uploaded, nextQueue);
      });
  };

  public removeFile = (removedFile) => {
    this.queue = this.queue.filter((file) => file.name !== removedFile.name);
  };

  public removeUploadedFile = (removedFile) => {
    this.uploaded = this.uploaded.filter((file) => file.name !== removedFile.name);
  };

  private readonly addToQueueUnique = (prevQueue, newFiles) => {
    const ids = new Set(prevQueue.map((prevFile) => prevFile.name));

    return [...prevQueue, ...newFiles.filter((newFile) => !ids.has(newFile.name))];
  };
}

<form (submit)="handleSubmit($event)">
  <nexus-form-field>
    <nexus-file-upload [accept]="accept" [attrId]="attrId" [disabled]="disabled" [multiple]="multiple"
      [required]="required" (change)="handleChange($event)">
      <div [innerHTML]="fileUpload.content"></div>
    </nexus-file-upload>
  </nexus-form-field>

  <nexus-chip-group class="nexus-rhythm-4" *ngIf="queue.length">
    <nexus-chip *ngFor="let item of queue; trackBy: item?.name" removable success="{{ item.uploaded || false }}"
      (click)="removeFile(item)">
      {{ item.name }}
    </nexus-chip>
  </nexus-chip-group>

  <nexus-chip-group class="nexus-rhythm-4" *ngIf="uploaded.length">
    <nexus-chip *ngFor="let item of uploaded; trackBy: item?.name" removable success="{{ item.uploaded || false }}"
      (click)="removeUploadedFile(item)">
      {{ item.name }}
    </nexus-chip>
  </nexus-chip-group>

  <button type="submit" class="nexus-btn-primary">{{fileUpload.upload}}</button>
</form>
