// ui-nexus-design-system/playbook/react/src/sb/components/file-upload/02_uploadImage.tsx
import { useState } from 'react';
import PropTypes from 'prop-types';
import { NexusFileUpload, NexusFormField, NexusChipGroup, NexusChip, NexusToast } from '@nexus/react';
import { uploadImage } from '../../constants';



const UploadImageComponent: React.FC = (props) => {
    const {
        attrId = 'nexus-file-upload',
        disabled = false,
        multiple = false,
        required = false,
        accept = '*'
    } = { ...props };
    const [queue2, setQueue2] = useState<any>([]);
    const [toast, setToast] = useState<boolean>(false);
    const [uploaded2, setUploaded2] = useState<{ name: string; uploaded2: boolean }[]>([]);

    const addToQueueUnique = (
        prevQueue: { name: string; uploaded2: boolean }[],
        newFiles: { name: string; uploaded2: boolean }[]
    ) => {
        const ids = new Set(prevQueue.map((prevFile: { name: string }) => prevFile.name));

        return [...prevQueue, ...newFiles.filter((newFile: { name: string }) => !ids.has(newFile.name))];
    };

    const handleChange = (event: any) => {
        setQueue2(addToQueueUnique(queue2, [...event.target.files]));
    };

    const handleSubmit = (event: any) => {
        event.preventDefault();
        const uploadURL = 'https://httpstat.us/200';
        const formData = new FormData();
        formData.append('files', queue2);

        // Fake API request that returns a 200
        // Replace this with your API method
        fetch(uploadURL, {
            method: 'POST',
            body: formData
        })
            .then((response) => response)
            .then(() => {
                const nextQueue = queue2.map((file: { name: string; uploaded2: boolean }) => {
                    file.uploaded2 = true;
                    const format = file.name.split('.');
                    if (format[1] === 'png') {
                        return file;
                    } else {
                        setToast(true);
                    }
                    const fileName = format[0];
                });

                setQueue2([]);
                setUploaded2(addToQueueUnique(uploaded2, nextQueue));
            });
    };

    const removeFile = (removedFile: { name: string }) => {
        setQueue2(queue2.filter((file: { name: string }) => file.name !== removedFile.name));
    };

    const removeUploadedFile = (removedFile: { name: string }) => {
        setUploaded2(uploaded2.filter((file: { name: string }) => file.name !== removedFile.name));
    };

    const renderQueue = (queue21: any, cb: any) =>
        queue21.map((file: { name: string; uploaded2: boolean }) => (
            <NexusChip
                data-testid="doc-uploaded2-chip"
                aria-label={`Click to remove file - ${file.name}`}
                removable={true}
                key={file.name}
                success={file.uploaded2}
                onClick={() => cb(file)}
            >
                {file.name}
            </NexusChip>
        ));

    const fileDrop = (event: any) => {
        event.preventDefault();
        setQueue2(addToQueueUnique(queue2, [...event.dataTransfer.files]));
    };

    return (
        <div>
            <form onSubmit={(event) => handleSubmit(event)}>
                <NexusFormField>
                    <NexusFileUpload
                        attrId={attrId}
                        disabled={disabled}
                        multiple={multiple}
                        required={required}
                        accept={accept}
                        onInput={(event: any) => handleChange(event)}
                        onDrop={(event: any) => fileDrop(event)}
                    >
                        <div dangerouslySetInnerHTML={{ __html: uploadImage.content }}></div>
                    </NexusFileUpload>
                </NexusFormField>

                {queue2.length > 0 && (
                    <NexusChipGroup className="nexus-rhythm-4">
                        {/* span required for react to render dynamic content into the correct slot */}
                        <span>{renderQueue(queue2, removeFile)}</span>
                    </NexusChipGroup>
                )}

                {uploaded2.length > 0 && (
                    <NexusChipGroup className="nexus-rhythm-4">
                        {/* span required for react to render dynamic content into the correct slot */}
                        <span>{renderQueue(uploaded2, removeUploadedFile)}</span>
                    </NexusChipGroup>
                )}

                <button type="submit" className="nexus-btn-primary">
                    Upload
                </button>
                <NexusToast position="bottom" closeable={true} variant="error" show={toast} style={toast ? { zIndex: "10" } : { display: "none" }}>Name {uploadImage.text}</NexusToast>
            </form>
        </div>
    );
};

UploadImageComponent.propTypes = {
    attrId: PropTypes.string,
    disabled: PropTypes.bool,
    multiple: PropTypes.bool,
    required: PropTypes.bool
};

export default UploadImageComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/file-upload/02_uploadImage.component.ts
import { Component, Input } from '@angular/core';
import { uploadImage } from '../../constants';

@Component({
  selector: 'app-upload-image',
  templateUrl: './02_uploadImage.component.html'
})
export default class UploadImageComponent {
  @Input() accept: String = '';

  @Input() attrId: String = '';

  @Input() disabled: boolean = true;

  @Input() multiple: boolean = false;

  @Input() required: boolean = false;

  public queue: any = [];

  public uploaded: any = [];

  uploadImage = uploadImage;

  incorrectFile = false;

  errorFile = '';

  public handleChange = (event) => {
    this.queue = this.addToQueueUnique(this.queue, [...event.target.files]);
  };

  public handleSubmit = (event) => {
    event.preventDefault();
    const uploadURL = 'https://httpstat.us/200';
    const formData = new FormData();
    formData.append('files', this.queue);

    // Fake API request that returns a 200
    // Replace this with your API method
    fetch(uploadURL, {
      method: 'POST',
      body: formData
    })
      .then((response) => response)
      .then(() => {
        // eslint-disable-next-line array-callback-return
        const nextQueue = this.queue.map((file) => {
          file.uploaded = true;
          const format = file.name.split('.');
          if (format[1] === 'png') {
            return file;
          }
          // eslint-disable-next-line prefer-destructuring
          this.errorFile = format[0];
          this.incorrectFile = true;
        });

        this.queue = [];
        this.uploaded = this.addToQueueUnique(this.uploaded, nextQueue);
      });
  };

  public removeFile = (removedFile) => {
    this.queue = this.queue.filter((file) => file.name !== removedFile.name);
  };

  public removeUploadedFile = (removedFile) => {
    this.uploaded = this.uploaded.filter((file) => file.name !== removedFile.name);
  };

  private readonly addToQueueUnique = (prevQueue, newFiles) => {
    const ids = new Set(prevQueue.map((prevFile) => prevFile.name));

    return [...prevQueue, ...newFiles.filter((newFile) => !ids.has(newFile.name))];
  };
}

<form (submit)="handleSubmit($event)">
    <nexus-form-field>
        <nexus-file-upload [accept]="accept" [attrId]="attrId" [disabled]="disabled" [multiple]="multiple"
            [required]="required" (change)="handleChange($event)">
            <div [innerHTML]="uploadImage.content"></div>
        </nexus-file-upload>
    </nexus-form-field>

    <nexus-chip-group class="nexus-rhythm-4" *ngIf="queue.length">
        <nexus-chip *ngFor="let item of queue; trackBy: item?.name" removable success="{{ item.uploaded || false }}"
            (click)="removeFile(item)">
            {{ item.name }}
        </nexus-chip>
    </nexus-chip-group>

    <nexus-chip-group class="nexus-rhythm-4" *ngIf="uploaded.length">
        <nexus-chip *ngFor="let item of uploaded; trackBy: item?.name" removable success="{{ item.uploaded || false }}"
            (click)="removeUploadedFile(item)">
            {{ item.name }}
        </nexus-chip>
    </nexus-chip-group>

    <button type="submit" class="nexus-btn-primary">{{uploadImage.upload}}</button>
</form>

<nexus-toast data-testid="toast-error" closable="false" show="true" variant="error" position="bottom" closeable="true"
    [ngStyle]="{'display': (incorrectFile) ? 'flex' : 'none'}" style="z-index: 100">
    <strong>{{errorFile}} </strong>{{uploadImage.text}}
</nexus-toast>
