// ui-nexus-design-system/playbook/angular/src/app/components/checkbox/checkbox.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-checkbox',
  templateUrl: './checkbox.component.html',
  styleUrls: ['./checkbox.component.scss']
})
export class CheckboxComponent {
  @Input() text: string;

  @Input() attrId: string = '';

  @Input() checked: boolean = false;

  @Input() disabled: boolean = false;

  @Input() indeterminate: boolean = false;

  @Input() required: boolean = false;
}

<nexus-checkbox [attrId]="attrId" [checked]="checked" [disabled]="disabled" [indeterminate]="indeterminate"
  >Check me!</nexus-checkbox
>

// ui-nexus-design-system/playbook/react/src/components/checkbox/checkbox.tsx
import React from 'react';

import { NexusCheckbox } from '@nexus/react';
import Note from '../notecontainer/note';

interface CheckboxComponentProps {
  attrId: string;
  checked: boolean;
  disabled: boolean;
  indeterminate: boolean;
  required: boolean;
}

const CheckboxComponent: React.FC<CheckboxComponentProps> = (props) => {
  return (
    <>
      <NexusCheckbox {...props}>Check me!</NexusCheckbox>
      <Note noteType="eventNote" />
    </>
  );
};

CheckboxComponent.defaultProps = {
  attrId: '',
  checked: false,
  disabled: false,
  indeterminate: false,
  required: false
};

export default CheckboxComponent;
