// ui-nexus-design-system/playbook/angular/src/app/components/checkbox-examples/checkbox-examples.component.ts
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-checkbox-examples',
  templateUrl: './checkbox-examples.component.html',
  styleUrls: ['./checkbox-examples.component.scss']
})
export class CheckboxExamplesComponent {
  checkedValue = new FormControl(false);

  indeterminateValue = new FormControl(false);

  disabledValue = new FormControl(false);
}

<p class="nexus-h5">Checkbox configuration:</p>

<nexus-checkbox data-testid="Check" ngDefaultControl [formControl]="checkedValue" class="nexus-rhythm-2">Check</nexus-checkbox>
<nexus-checkbox data-testid="Indeterminate" ngDefaultControl [formControl]="indeterminateValue" class="nexus-rhythm-2">Indeterminate</nexus-checkbox>
<nexus-checkbox data-testid="Disabled" ngDefaultControl [formControl]="disabledValue" class="nexus-rhythm-2">Disabled</nexus-checkbox>

<p class="nexus-h5">Example:</p>

<nexus-checkbox id="example"
  [checked]="checkedValue.value"
  [indeterminate]="indeterminateValue.value"
  [disabled]="disabledValue.value"
>
  Example
</nexus-checkbox>

// ui-nexus-design-system/playbook/react/src/components/checkbox/checkbox-examples.tsx
import React, { useState } from 'react';

import { NexusCheckbox } from '@nexus/react';

const CheckboxExampleComponent: React.FC = () => {
  const [checkedValue, setCheckedValue] = useState(false);

  const [indeterminateValue, setIndeterminateValue] = useState(false);

  const [disabledValue, setDisabledValue] = useState(false);

  return (
    <>
      <p className="nexus-h5">Checkbox configuration:</p>

      <NexusCheckbox
        data-testid="Check"
        className="nexus-rhythm-2"
        onInput={(event: any) => setCheckedValue(event.target.checked)}
      >
        Check
      </NexusCheckbox>
      <NexusCheckbox
        data-testid="Indeterminate"
        className="nexus-rhythm-2"
        onInput={(event: any) => setIndeterminateValue(event.target.checked)}
      >
        Indeterminate
      </NexusCheckbox>
      <NexusCheckbox
        data-testid="Disabled"
        className="nexus-rhythm-2"
        onInput={(event: any) => setDisabledValue(event.target.checked)}
      >
        Disabled
      </NexusCheckbox>

      <p className="nexus-h5">Example:</p>

      <NexusCheckbox
        checked={checkedValue}
        indeterminate={indeterminateValue}
        disabled={disabledValue}
        data-testid="Example"
        className="nexus-rhythm-2">

        Example
      </NexusCheckbox>
    </>
  );
};

export default CheckboxExampleComponent;
