// ui-nexus-design-system/playbook/react/src/components/form-field/form-field-examples.tsx
import React, { useState } from 'react';
import { NexusMessage, NexusErrorMessage, NexusFormField, NexusInput, NexusLabel } from '@nexus/react';

const FormFieldExampleComponent: React.FC = () => {
  const [disabledValue, setDisabledValue] = useState('Value');

  const [messageValue, setMessageValue] = useState('');

  const [errorValue, setErrorValue] = useState('');

  return (
    <>
      <p className="nexus-h5">Disabled</p>

      <NexusFormField>
        <NexusLabel
          data-testid="label-first-name-disabled"
        >
          First name
        </NexusLabel>
        <NexusInput
          data-testid="textbox-disabled"
          value={disabledValue} onInput={(event: any) => setDisabledValue(event.target.value)} disabled></NexusInput>
      </NexusFormField>

      <p className="nexus-h5">With Message</p>

      <NexusFormField>
        <NexusLabel
          data-testid="label-first-name"
        >
          First name
        </NexusLabel>
        <NexusInput
          data-testid="textbox-message"
          value={messageValue} onInput={(event: any) => setMessageValue(event.target.value)}>

        </NexusInput>
        <NexusMessage
          data-testid="custom-message"
        >
          Custom message
        </NexusMessage>
      </NexusFormField>

      <p className="nexus-h5">With Error</p>

      <NexusFormField>
        <NexusLabel
          data-testid="label-first-name-error"
        >
          First name
        </NexusLabel>
        <NexusInput
          data-testid="textbox-error"
          value={errorValue} onInput={(event: any) => setErrorValue(event.target.value)}></NexusInput>
        <NexusErrorMessage
          data-testid="textbox-error-msg"
        >
          This is an error message
        </NexusErrorMessage>
      </NexusFormField>
    </>
  );
};

export default FormFieldExampleComponent;

// ui-nexus-design-system/playbook/angular/src/app/components/form-field-examples/form-field-examples.component.ts
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';

@Component({
  selector: 'app-form-field-examples',
  templateUrl: './form-field-examples.component.html',
  styleUrls: ['./form-field-examples.component.scss']
})
export class FormFieldExamplesComponent {
  disabledValue = new FormControl({ value: 'Value',
    disabled: true });

  messageValue = new FormControl('');

  errorValue = new FormControl('');
}

<p class="nexus-h5">Disabled</p>

<nexus-form-field>
  <nexus-label>First name</nexus-label>
  <nexus-input [disabled]="true" [formControl]="disabledValue" [value]="disabledValue.value"></nexus-input>

</nexus-form-field>

<p class="nexus-h5">With Message</p>

<nexus-form-field>
  <nexus-label>First name</nexus-label>
  <nexus-input [formControl]="messageValue" [value]="messageValue.value"></nexus-input>
  <nexus-message>Custom message</nexus-message>
</nexus-form-field>

<p class="nexus-h5">With Error</p>

<nexus-form-field>
  <nexus-label>First name</nexus-label>
  <nexus-input [formControl]="errorValue" [value]="errorValue.value"></nexus-input>
  <nexus-error-message>This is an error message</nexus-error-message>
</nexus-form-field>
