// ui-nexus-design-system/playbook/angular/src/app/components/toggle-examples/toggle-examples.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-toggle-examples',
  templateUrl: './toggle-examples.component.html',
  styleUrls: ['./toggle-examples.component.scss']
})
export class ToggleExamplesComponent {}

<p class="nexus-h5">Disabled</p>
<nexus-toggle disabled data-testid="toggle-disabled"></nexus-toggle>

<p class="nexus-h5">Add Labels</p>
<nexus-toggle data-testid="toggle-labels" label-inactive="hide" label-active="show" size="sm"></nexus-toggle>

<p class="nexus-h5">Toggle Types:</p>

<p class="nexus-h6">Default</p>
<nexus-toggle data-testid="toggle-default" label-inactive="hide" label-active="show" size="sm"></nexus-toggle>

<p class="nexus-h5">Button</p>
<nexus-toggle data-testid="toggle-button" type="button" label-inactive="hide" label-active="show" size="sm"></nexus-toggle>

<p class="nexus-h5">Toggle switch size variants.</p>
<div class="nexus-row">
    <div class="nexus-col-lg-1">
        <p class="nexus-h6">xs</p>
        <nexus-toggle data-testid="toggle-size-xs" size="xs"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-1">
        <p class="nexus-h6">sm</p>
        <nexus-toggle data-testid="toggle-size-sm" size="sm"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">md</p>
        <nexus-toggle data-testid="toggle-size-md" size="md"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">lg</p>
        <nexus-toggle data-testid="toggle-size-lg" size="lg"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">xl</p>
        <nexus-toggle data-testid="toggle-size-xl" size="xl"></nexus-toggle>
    </div>
</div>

<p class="nexus-h5">Toggle Button size variants.</p>
<div class="nexus-row">
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">xs</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="xs"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">sm</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="sm"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">md</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="md"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">lg</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="lg"></nexus-toggle>
    </div>
    <div class="nexus-col-lg-2">
        <p class="nexus-h6">xl</p>
        <nexus-toggle type="button" label-inactive="hide" label-active="show" size="xl"></nexus-toggle>
    </div>
</div>

// ui-nexus-design-system/playbook/react/src/components/toggle/toggle-examples.tsx
import React from 'react';

import { NexusToggle } from '@nexus/react';

const ToggleExampleComponent: React.FC = () => {
  return (
    <>
      <p className="nexus-h5">Disabled</p>
      <NexusToggle data-testid="toggle-disabled" disabled />

      <p className="nexus-h5">Add Labels</p>
      <NexusToggle data-testid="toggle-labels" labelActive="show" labelInactive="hide" size="sm" />

      <p className="nexus-h5">Toggle Types:</p>

      <p className="nexus-h6">Default</p>
      <NexusToggle data-testid="toggle-default" labelInactive="hide" labelActive="show" size="sm"></NexusToggle>

      <p className="nexus-h5">Button</p>
      <NexusToggle data-testid="toggle-button" type="button" labelInactive="hide" labelActive="show" size="sm"></NexusToggle>

      <p className="nexus-h5">Toggle switch size variants.</p>
      <div className="nexus-row">
        <div className="nexus-col-lg-1">
          <p className="nexus-h6">xs</p>
          <NexusToggle data-testid="toggle-size-xs" size="xs" />
        </div>
        <div className="nexus-col-lg-1">
          <p className="nexus-h6">sm</p>
          <NexusToggle data-testid="toggle-size-sm" size="sm" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">md</p>
          <NexusToggle data-testid="toggle-size-md" size="md" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">lg</p>
          <NexusToggle data-testid="toggle-size-lg" size="lg" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">xl</p>
          <NexusToggle data-testid="toggle-size-xl" size="xl" />
        </div>
      </div>

      <p className="nexus-h5">Toggle button size variants.</p>
      <div className="nexus-row">
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">xs</p>
          <NexusToggle data-testid="toggle-btn-size-xs" type="button" label-inactive="hide" label-active="show" size="xs" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">sm</p>
          <NexusToggle data-testid="toggle-btn-size-sm" type="button" label-inactive="hide" label-active="show" size="sm" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">md</p>
          <NexusToggle data-testid="toggle-btn-size-md" type="button" label-inactive="hide" label-active="show" size="md" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">lg</p>
          <NexusToggle data-testid="toggle-btn-size-lg" type="button" label-inactive="hide" label-active="show" size="lg" />
        </div>
        <div className="nexus-col-lg-2">
          <p className="nexus-h6">xl</p>
          <NexusToggle data-testid="toggle-btn-size-xl" type="button" label-inactive="hide" label-active="show" size="xl" />
        </div>
      </div>
    </>
  );
};

export default ToggleExampleComponent;
