// ui-nexus-design-system/playbook/angular/src/app/components/pagination/pagination.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html'
})
export class PaginationComponent {
  @Input() current: number = 2;

  @Input() max: number = 5;

  handleChange(event) {
    this.current = event.detail;
  }
}

<nexus-pagination [current]="current" [max]="max" (changeEvent)="handleChange($event)"></nexus-pagination>

// ui-nexus-design-system/playbook/react/src/components/pagination/pagination.tsx
import React, { useState } from 'react';

import { NexusPagination } from '@nexus/react';
import { NexusPaginationCustomEvent } from '@nexus/core';

interface PaginationComponentProps {
  current: number;
  max: number;
}

const PaginationComponent: React.FC<PaginationComponentProps> = (props) => {
  const { current, max } = { ...props };
  const [currentPage, setCurrentPage] = useState(current);

  return (
    <NexusPagination
      data-testid="pagination"
      current={currentPage}
      max={max}
      onChangeEvent={(event: NexusPaginationCustomEvent<any>) => setCurrentPage(event.detail)}
    ></NexusPagination>
  );
};

PaginationComponent.defaultProps = {
  current: 3,
  max: 5
};

export default PaginationComponent;
