// ui-nexus-design-system/playbook/angular/src/app/components/accordion/accordion.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-accordion',
  templateUrl: './accordion.component.html',
  styleUrls: ['./accordion.component.scss']
})
export class AccordionComponent {
  @Input() open: boolean = false;

  @Input() size: string = 'sm';
}

<nexus-accordion [open]="open" (toggleEvent)="open = !open" size="size">
  <nexus-accordion-trigger>
    <h1 class="nexus-body">Accordion Title</h1>
  </nexus-accordion-trigger>
  <nexus-accordion-content>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget aliquam justo, nec iaculis enim. Praesent at
    cursus nisl, vel molestie sapien. Donec gravida metus sem, non iaculis nisl sodales at. Cras tristique magna nisi,
    nec imperdiet lectus aliquet imperdiet. Quisque at hendrerit felis. Orci varius natoque penatibus et magnis dis
    parturient montes, nascetur ridiculus mus. Etiam vitae quam et lorem tincidunt feugiat. Sed id massa eu ex bibendum
    suscipit. Praesent urna est, vestibulum vitae porttitor sed, mattis id nisi. In eu semper augue. Sed viverra finibus
    pellentesque. Etiam non ultricies mauris. Nullam eu aliquet tellus.
  </nexus-accordion-content>
</nexus-accordion>

// ui-nexus-design-system/playbook/react/src/components/accordion/accordion.tsx
import React, { useState } from 'react';

import { NexusAccordion, NexusAccordionTrigger, NexusAccordionContent } from '@nexus/react';

interface AccordionComponentProps {
  open: boolean;
  size: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
}

const AccordionComponent: React.FC<AccordionComponentProps> = (props) => {
  const { open, size } = { ...props };
  const [openAcccordion, setAccordionOpen] = useState(open);

  return (
    <NexusAccordion open={openAcccordion} onToggleEvent={() => setAccordionOpen(!openAcccordion)} size={size}>
      <NexusAccordionTrigger>
        <h1 className="nexus-body">Accordion Title</h1>
      </NexusAccordionTrigger>
      <NexusAccordionContent>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget aliquam justo, nec iaculis enim. Praesent at
        cursus nisl, vel molestie sapien. Donec gravida metus sem, non iaculis nisl sodales at. Cras tristique magna
        nisi, nec imperdiet lectus aliquet imperdiet. Quisque at hendrerit felis. Orci varius natoque penatibus et
        magnis dis parturient montes, nascetur ridiculus mus. Etiam vitae quam et lorem tincidunt feugiat. Sed id massa
        eu ex bibendum suscipit. Praesent urna est, vestibulum vitae porttitor sed, mattis id nisi. In eu semper augue.
        Sed viverra finibus pellentesque. Etiam non ultricies mauris. Nullam eu aliquet tellus.
      </NexusAccordionContent>
    </NexusAccordion>
  );
};

AccordionComponent.defaultProps = {
  open: false,
  size: 'md'
};

export default AccordionComponent;
