// ui-nexus-design-system/playbook/angular/src/app/components/accordion-examples/accordion-examples.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-accordion-examples',
  templateUrl: './accordion-examples.component.html',
  styleUrls: ['./accordion-examples.component.scss']
})
export class AccordionExamplesComponent {
  public open = false;

  public openExample2 = false;

  public openExample3 = false;

  public openExampleXS = false;

  public openExampleS = false;

  public openExampleM = false;

  public openExampleL = false;

  public openExampleXL = false;
}

<div class="row">
  <div data-testid="acc-align-start" class="nexus-col-md-10">
    <p class="nexus-h5">Set <code>align="start | center | end"</code> to align nexus accordion title to float in
      "start | center | end". However the default accordion header aligns to left.</p>
    <nexus-accordion [open]="open" (toggleEvent)="open = !open" size="md">
      <nexus-accordion-trigger>
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget aliquam justo, nec iaculis enim. Praesent at
        cursus nisl, vel molestie sapien. Donec gravida metus sem, non iaculis nisl sodales at. Cras tristique magna
        nisi,
        nec imperdiet lectus aliquet imperdiet. Quisque at hendrerit felis. Orci varius natoque penatibus et magnis dis
        parturient montes, nascetur ridiculus mus. Etiam vitae quam et lorem tincidunt feugiat. Sed id massa eu ex
        bibendum
        suscipit. Praesent urna est, vestibulum vitae porttitor sed, mattis id nisi. In eu semper augue. Sed viverra
        finibus
        pellentesque. Etiam non ultricies mauris. Nullam eu aliquet tellus.
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />

<div class="row">
  <div data-testid="acc-align-center" class="nexus-col-md-10">
    <nexus-accordion [open]="openExample2" (toggleEvent)="openExample2 = !openExample2" size="md">
      <nexus-accordion-trigger align="center">
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget aliquam justo, nec iaculis enim. Praesent at
        cursus nisl, vel molestie sapien. Donec gravida metus sem, non iaculis nisl sodales at. Cras tristique magna
        nisi,
        nec imperdiet lectus aliquet imperdiet. Quisque at hendrerit felis. Orci varius natoque penatibus et magnis dis
        parturient montes, nascetur ridiculus mus. Etiam vitae quam et lorem tincidunt feugiat. Sed id massa eu ex
        bibendum
        suscipit. Praesent urna est, vestibulum vitae porttitor sed, mattis id nisi. In eu semper augue. Sed viverra
        finibus
        pellentesque. Etiam non ultricies mauris. Nullam eu aliquet tellus.
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />

<div class="row">
  <div data-testid="acc-align-end"  class="nexus-col-md-10">
    <nexus-accordion [open]="openExample3" (toggleEvent)="openExample3 = !openExample3" size="md">
      <nexus-accordion-trigger align="end">
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget aliquam justo, nec iaculis enim. Praesent at
        cursus nisl, vel molestie sapien. Donec gravida metus sem, non iaculis nisl sodales at. Cras tristique magna
        nisi,
        nec imperdiet lectus aliquet imperdiet. Quisque at hendrerit felis. Orci varius natoque penatibus et magnis dis
        parturient montes, nascetur ridiculus mus. Etiam vitae quam et lorem tincidunt feugiat. Sed id massa eu ex
        bibendum
        suscipit. Praesent urna est, vestibulum vitae porttitor sed, mattis id nisi. In eu semper augue. Sed viverra
        finibus
        pellentesque. Etiam non ultricies mauris. Nullam eu aliquet tellus.
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />

<div class="row">
  <div class="nexus-col-md-10">
    <p class="nexus-h5">Different size variants for accordion based on which the content is padded within the accordion.
    </p>
  </div>
</div>

<div class="row">
  <div data-testid="acc-size-xs" class="nexus-col-md-10">
    <p class="nexus-h5">Accordion Size: <code>xs | sm | md | lg | xl </code>.</p>
    <nexus-accordion [open]="openExampleXS" (toggleEvent)="openExampleXS = !openExampleXS" size="xs">
      <nexus-accordion-trigger>
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        <span>Ths accordion is an example for extremely <strong>mobile screen (xs) sized</strong> contents.</span>
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />


<div class="row">
  <div data-testid="acc-size-sm" class="nexus-col-md-10">
    <nexus-accordion [open]="openExampleS" (toggleEvent)="openExampleS = !openExampleS" size="sm">
      <nexus-accordion-trigger>
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        <span>Ths accordion is an example for extremely <strong>small sized</strong> contents.</span>
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />

<div class="row">
  <div data-testid="acc-size-md" class="nexus-col-md-10">
    <nexus-accordion [open]="openExampleM" (toggleEvent)="openExampleM = !openExampleM" size="md">
      <nexus-accordion-trigger>
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        <span>Ths accordion is an example for extremely <strong>medium sized</strong> contents.</span>
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />

<div class="row">
  <div data-testid="acc-size-lg" class="nexus-col-md-10">
    <nexus-accordion [open]="openExampleL" (toggleEvent)="openExampleL = !openExampleL" size="lg">
      <nexus-accordion-trigger>
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        <span>Ths accordion is an example for extremely <strong>large sized</strong> contents.</span>
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />

<div class="row">
  <div data-testid="acc-size-xl" class="nexus-col-md-10">
    <nexus-accordion [open]="openExampleXL" (toggleEvent)="openExampleXL = !openExampleXL" size="xl">
      <nexus-accordion-trigger>
        <h1 class="nexus-body">Accordion Title</h1>
      </nexus-accordion-trigger>
      <nexus-accordion-content>
        <span>Ths accordion is an example for extremely <strong>extra large sized</strong> contents.</span>
      </nexus-accordion-content>
    </nexus-accordion>
  </div>
</div>
<br />

<div class="row">
  <div class="nexus-col-md-10">
    <p class="nexus-h5">Accordion Group.</p>
    <app-accordion-group-examples></app-accordion-group-examples>
  </div>
</div>

// ui-nexus-design-system/playbook/react/src/components/accordion/accordion-examples.tsx
import React, { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { NexusAccordion, NexusAccordionTrigger, NexusAccordionContent, NexusAccordionGroup } from '@nexus/react';

const accordionData = [
  {
    title: 'Accordion Title 1',
    info: `The content belongs to first accordion group 1 . `
  },
  {
    title: 'Accordion Title 2',
    info: `The content belongs to first accordion group 2.`
  },
  {
    title: 'Accordion Title 3',
    info: `The content belongs to first accordion group 3.`
  },
  {
    title: 'Accordion Title 4',
    info: `The content belongs to first accordion group 4.`
  }
];

const AccordionExampleComponent = () => {
  const [open, setOpen] = useState(false);
  const [openExampleAlignCenter, setopenExampleAlignCenter] = useState(false);
  const [openExampleAlignEnd, setopenExampleAlignEnd] = useState(false);
  const [openExampleSizeXS, setOpenExampleSizeXS] = useState(false);
  const [openExampleSizeS, setOpenExampleSizeS] = useState(false);
  const [openExampleSizeM, setOpenExampleSizeM] = useState(false);
  const [openExampleSizeL, setOpenExampleSizeL] = useState(false);
  const [openExampleSizeXL, setOpenExampleSizeXL] = useState(false);
  const [accordionStates, setAccordionState] = useState(getData());

  const setAccordionStateHandler = (idx: string | number) => {
    const states = getData();
    states[idx] = !states[idx];
    setAccordionState(states);
  };

  return (
    <>
      <div className="row">
        <div data-testid="acc-align-start" className="nexus-col-md-10">
          <p className="nexus-h5">
            Set <code>align="start | center | end"</code> to align nexus accordion title to float in "start | center |
            end". However the default accordion header aligns to left.
          </p>
          <AccordionWrapperComponent toggleAccordion={open} setToggleHandler={setOpen} />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-align-center" className="nexus-col-md-10">
          <AccordionWrapperComponent
            toggleAccordion={openExampleAlignCenter}
            setToggleHandler={setopenExampleAlignCenter}
            position="center"
          />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-align-end" className="nexus-col-md-10">
          <AccordionWrapperComponent
            toggleAccordion={openExampleAlignEnd}
            setToggleHandler={setopenExampleAlignEnd}
            position="end"
          />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-size-xs" className="nexus-col-md-10">
          <p className="nexus-h5">
            Different size variants for accordion based on which the content is padded within the accordion.
          </p>
          <p className="nexus-h5">
            Accordion Size: <code>xs | sm | md | lg | xl </code>.
          </p>
          <AccordionWrapperComponent
            toggleAccordion={openExampleSizeXS}
            setToggleHandler={setOpenExampleSizeXS}
            size="xs"
          />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-size-sm" className="nexus-col-md-10">
          <AccordionWrapperComponent
            toggleAccordion={openExampleSizeS}
            setToggleHandler={setOpenExampleSizeS}
            size="sm"
          />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-size-md" className="nexus-col-md-10">
          <AccordionWrapperComponent
            toggleAccordion={openExampleSizeM}
            setToggleHandler={setOpenExampleSizeM}
            size="md"
          />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-size-lg" className="nexus-col-md-10">
          <AccordionWrapperComponent
            toggleAccordion={openExampleSizeL}
            setToggleHandler={setOpenExampleSizeL}
            size="lg"
          />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-size-xl" className="nexus-col-md-10">
          <AccordionWrapperComponent
            toggleAccordion={openExampleSizeXL}
            setToggleHandler={setOpenExampleSizeXL}
            size="xl"
          />
        </div>
      </div>
      <br />

      <div className="row">
        <div data-testid="acc-group" className="nexus-col-md-10">
          <p className="nexus-h5">Accordion Group.</p>
          <NexusAccordionGroup>
            {accordionData.map((rec, idx) => (
              <AccordionGroupExample
                key={idx}
                data-testid="acc-group"
                title={rec.title}
                info={rec.info}
                stateHandler={setAccordionStateHandler}
                index={idx}
                accordionState={accordionStates[idx]}
              />
            ))}
          </NexusAccordionGroup>
        </div>
      </div>
    </>
  );
};

const AccordionWrapperComponent = (props: {
  toggleAccordion: any;
  setToggleHandler: (arg0: boolean) => any;
  size: any;
  position: any;
  header:
  | string
  | number
  | boolean
  | React.ReactElement<any, string | React.JSXElementConstructor<any>>
  | React.ReactFragment
  | React.ReactPortal
  | null
  | undefined;
  content: any;
}) => (
  <NexusAccordion
    open={props.toggleAccordion}
    onToggleEvent={() => props.setToggleHandler(!props.toggleAccordion)}
    size={props.size}
  >
    <NexusAccordionTrigger align={props.position}>
      <h1 className="nexus-body">{props.header}</h1>
    </NexusAccordionTrigger>
    <NexusAccordionContent>{props.content}</NexusAccordionContent>
  </NexusAccordion>
);

AccordionWrapperComponent.propTypes = {
  toggleAccordion: PropTypes.bool,
  setToggleHandler: PropTypes.func,
  position: PropTypes.string,
  size: PropTypes.string,
  header: PropTypes.string,
  content: PropTypes.string
};

AccordionWrapperComponent.defaultProps = {
  position: 'start',
  size: 'md',
  header: 'Accordion Title',
  content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget aliquam justo, nec iaculis enim. Praesent at cursus nisl, vel molestie sapien.`
};

const AccordionGroupExample = (props: any) => {
  const [open, setOpen] = useState(props.accordionState[props.index]);
  useEffect(() => setOpen(props.accordionState), [props.accordionState]);

  return (
    <AccordionWrapperComponent
      toggleAccordion={open}
      header={accordionData[props.index].title}
      content={accordionData[props.index].info}
      setToggleHandler={() => props.stateHandler(props.index)}
    />
  );
};

const getData = (): { [id: string]: boolean } => {
  const states: { [id: string]: boolean } = {};
  accordionData.forEach((_, idx) => (states[idx] = false));
  return states;
};

export default AccordionExampleComponent;
