// ui-nexus-design-system/playbook/react/src/sb/components/avatar/02_size.tsx
import React from 'react';
import { sizeAvatar } from '../../constants';
import { NexusAvatar } from '@nexus/react';


const SizeComponent: React.FC = () => {
    return (
        <div className='nexus-row nexus-around-xs'>
            <div className='nexus-col-md-1'>
                <p className="nexus-h6">XS</p>
                <NexusAvatar
                    userName={sizeAvatar.name}
                    avatarNameDisplay={sizeAvatar.avatarNameDisplay === 'true'}
                    avatarSize={sizeAvatar.sizeXS}
                    avatarLogoIcon={sizeAvatar.logoIcon}
                ></NexusAvatar>
            </div>

            <div className='nexus-col-md-1'>
                <p className="nexus-h6">SM</p>
                <NexusAvatar
                    userName={sizeAvatar.name}
                    avatarNameDisplay={sizeAvatar.avatarNameDisplay === 'true'}
                    avatarSize={sizeAvatar.sizeSM}
                    avatarLogoIcon={sizeAvatar.logoIcon}
                ></NexusAvatar>
            </div>


            <div className='nexus-col-md-1'>
                <p className="nexus-h6">MD</p>
                <NexusAvatar
                    userName={sizeAvatar.name}
                    avatarNameDisplay={sizeAvatar.avatarNameDisplay === 'true'}
                    avatarSize={sizeAvatar.sizeMD}
                    avatarLogoIcon={sizeAvatar.logoIcon}
                ></NexusAvatar>
            </div>

            <div className='nexus-col-md-1'>
                <p className="nexus-h6">LG</p>
                <NexusAvatar
                    userName={sizeAvatar.name}
                    avatarNameDisplay={sizeAvatar.avatarNameDisplay === 'true'}
                    avatarSize={sizeAvatar.sizeLG}
                    avatarLogoIcon={sizeAvatar.logoIcon}
                ></NexusAvatar>
            </div>


            <div className='nexus-col-md-1'>
                <p className="nexus-h6">XL</p>
                <NexusAvatar
                    userName={sizeAvatar.name}
                    avatarNameDisplay={sizeAvatar.avatarNameDisplay === 'true'}
                    avatarSize={sizeAvatar.sizeXL}
                    avatarLogoIcon={sizeAvatar.logoIcon}
                ></NexusAvatar>
            </div>
        </div>
    );
};


export default SizeComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/avatar/02_size.component.ts
import { Component } from '@angular/core';
import { sizeAvatar } from '../../constants';
@Component({
  selector: 'app-avatar-examples-size',
  templateUrl: './02_size.component.html'
})
export default class AvatarSizeComponent {
  sizeXS = sizeAvatar.sizeXS;

  sizeSM = sizeAvatar.sizeSM;

  sizeMD = sizeAvatar.sizeMD;

  sizeLG = sizeAvatar.sizeLG;

  sizeXL = sizeAvatar.sizeXL;

  logoIcon = sizeAvatar.logoIcon;

  name = sizeAvatar.name;

  avatarNameDisplay = sizeAvatar.avatarNameDisplay;
}

<div class="nexus-row nexus-around-xs">
  <div class="nexus-col-md-1">
    <p class="nexus-h6">xs</p>
    <nexus-avatar
      [avatarSize]="sizeXS"
      [userName]="name"
      [avatarLogoIcon]="logoIcon"
      [avatarNameDisplay]="avatarNameDisplay"
    >
    </nexus-avatar>
  </div>
  <div class="nexus-col-md-1">
    <p class="nexus-h6">SM</p>
    <nexus-avatar
      [avatarSize]="sizeSM"
      [userName]="name"
      [avatarLogoIcon]="logoIcon"
      [avatarNameDisplay]="avatarNameDisplay"
    >
    </nexus-avatar>
  </div>
  <div class="nexus-col-md-1">
    <p class="nexus-h6">MD</p>
    <nexus-avatar
      [avatarSize]="sizeMD"
      [userName]="name"
      [avatarLogoIcon]="logoIcon"
      [avatarNameDisplay]="avatarNameDisplay"
    >
    </nexus-avatar>
  </div>
  <div class="nexus-col-md-1">
    <p class="nexus-h6">LG</p>
    <nexus-avatar
      [avatarSize]="sizeLG"
      [userName]="name"
      [avatarLogoIcon]="logoIcon"
      [avatarNameDisplay]="avatarNameDisplay"
    >
    </nexus-avatar>
  </div>
  <div class="nexus-col-md-1">
    <p class="nexus-h6">XL</p>
    <nexus-avatar
      [avatarSize]="sizeXL"
      [userName]="name"
      [avatarLogoIcon]="logoIcon"
      [avatarNameDisplay]="avatarNameDisplay"
    >
    </nexus-avatar>
  </div>
</div>
