// ui-nexus-design-system/playbook/react/src/sb/components/avatar/07_initialsNameAndNotification.tsx
import React from 'react';

import { NexusAvatar } from '@nexus/react';


export const InitialsNameAndNotificationComponent: React.FC = () => (
    <div className="nexus-col-xl-8">
        <NexusAvatar
            avatar-size='lg'
            user-name='Joseph Benjamin'
            avatar-notification='14' />
    </div>
);

export default InitialsNameAndNotificationComponent;

// ui-nexus-design-system/playbook/angular/src/app/sb/components/avatar/07_initialsNameAndNotification.component.ts
import { notification } from '../../../../../../stories/data/notification/notification';
import { Component } from '@angular/core';
import { initialsNameAndNotification } from '../../constants';
@Component({
  selector: 'app-avatar-examples-initial-name-notification',
  templateUrl: './07_initialsNameAndNotification.component.html'
})
export default class InitialsNameAndNotificationComponent {
  name = initialsNameAndNotification.name;

  size = initialsNameAndNotification.size;

  notification = initialsNameAndNotification.notification;
}

<div class="nexus-col-xl-2">
  <p><nexus-avatar [avatarSize]="size" [userName]="name" [avatarNotification]="notification"> </nexus-avatar></p>
</div>
