// ui-nexus-design-system/playbook/angular/src/app/sb/components/loader/01_loader.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-loader',
  templateUrl: './01_loader.component.html'
})
export default class LoaderComponent {
  @Input() show: boolean = true;

  @Input() fullscreen: boolean = false;
}

<nexus-loader [fullscreen]="fullscreen" [show]="show"></nexus-loader>

// ui-nexus-design-system/playbook/react/src/sb/components/loader/01_loader.tsx
import React from 'react';
import PropTypes from 'prop-types';
import { loader } from '../../constants';

import { NexusLoader } from '@nexus/react';

const LoaderComponent: React.FC = (props) => {
  const { show = loader.show, fullscreen = loader.fullScreen } = { ...props };
  return <NexusLoader show={show} fullscreen={fullscreen}></NexusLoader>;
};

LoaderComponent.propTypes = {
  show: PropTypes.bool,
  fullscreen: PropTypes.bool
};

export default LoaderComponent;
